// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: order_iface/v1/create.proto

package order_iface

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/pdcgo/schema/services/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShipmentPaymentType int32

const (
	ShipmentPaymentType_SHIPMENT_PAYMENT_TYPE_UNSPECIFIED ShipmentPaymentType = 0
	ShipmentPaymentType_SHIPMENT_PAYMENT_TYPE_WAREHOUSE   ShipmentPaymentType = 1
	ShipmentPaymentType_SHIPMENT_PAYMENT_TYPE_BUYER       ShipmentPaymentType = 2
)

// Enum value maps for ShipmentPaymentType.
var (
	ShipmentPaymentType_name = map[int32]string{
		0: "SHIPMENT_PAYMENT_TYPE_UNSPECIFIED",
		1: "SHIPMENT_PAYMENT_TYPE_WAREHOUSE",
		2: "SHIPMENT_PAYMENT_TYPE_BUYER",
	}
	ShipmentPaymentType_value = map[string]int32{
		"SHIPMENT_PAYMENT_TYPE_UNSPECIFIED": 0,
		"SHIPMENT_PAYMENT_TYPE_WAREHOUSE":   1,
		"SHIPMENT_PAYMENT_TYPE_BUYER":       2,
	}
)

func (x ShipmentPaymentType) Enum() *ShipmentPaymentType {
	p := new(ShipmentPaymentType)
	*p = x
	return p
}

func (x ShipmentPaymentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShipmentPaymentType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_iface_v1_create_proto_enumTypes[0].Descriptor()
}

func (ShipmentPaymentType) Type() protoreflect.EnumType {
	return &file_order_iface_v1_create_proto_enumTypes[0]
}

func (x ShipmentPaymentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShipmentPaymentType.Descriptor instead.
func (ShipmentPaymentType) EnumDescriptor() ([]byte, []int) {
	return file_order_iface_v1_create_proto_rawDescGZIP(), []int{0}
}

type OrderAddress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Phone         string                 `protobuf:"bytes,2,opt,name=phone,proto3" json:"phone,omitempty"`
	Province      string                 `protobuf:"bytes,3,opt,name=province,proto3" json:"province,omitempty"`
	City          string                 `protobuf:"bytes,4,opt,name=city,proto3" json:"city,omitempty"`
	District      string                 `protobuf:"bytes,5,opt,name=district,proto3" json:"district,omitempty"`
	PostalCode    string                 `protobuf:"bytes,6,opt,name=postal_code,json=postalCode,proto3" json:"postal_code,omitempty"`
	Address       string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderAddress) Reset() {
	*x = OrderAddress{}
	mi := &file_order_iface_v1_create_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderAddress) ProtoMessage() {}

func (x *OrderAddress) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_create_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderAddress.ProtoReflect.Descriptor instead.
func (*OrderAddress) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_create_proto_rawDescGZIP(), []int{0}
}

func (x *OrderAddress) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *OrderAddress) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *OrderAddress) GetProvince() string {
	if x != nil {
		return x.Province
	}
	return ""
}

func (x *OrderAddress) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *OrderAddress) GetDistrict() string {
	if x != nil {
		return x.District
	}
	return ""
}

func (x *OrderAddress) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *OrderAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type OrderItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProductId     uint64                 `protobuf:"varint,1,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	VariationId   uint64                 `protobuf:"varint,2,opt,name=variation_id,json=variationId,proto3" json:"variation_id,omitempty"`
	Count         int64                  `protobuf:"varint,3,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderItem) Reset() {
	*x = OrderItem{}
	mi := &file_order_iface_v1_create_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderItem) ProtoMessage() {}

func (x *OrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_create_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderItem.ProtoReflect.Descriptor instead.
func (*OrderItem) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_create_proto_rawDescGZIP(), []int{1}
}

func (x *OrderItem) GetProductId() uint64 {
	if x != nil {
		return x.ProductId
	}
	return 0
}

func (x *OrderItem) GetVariationId() uint64 {
	if x != nil {
		return x.VariationId
	}
	return 0
}

func (x *OrderItem) GetCount() int64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type OrderCreateRequest struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	OrderRefId          string                 `protobuf:"bytes,1,opt,name=order_ref_id,json=orderRefId,proto3" json:"order_ref_id,omitempty"`
	OrderMpId           uint64                 `protobuf:"varint,2,opt,name=order_mp_id,json=orderMpId,proto3" json:"order_mp_id,omitempty"`
	OrderFrom           v1.MarketplaceType     `protobuf:"varint,3,opt,name=order_from,json=orderFrom,proto3,enum=common.v1.MarketplaceType" json:"order_from,omitempty"`
	OrderTime           *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=order_time,json=orderTime,proto3" json:"order_time,omitempty"`
	OrderTotal          int64                  `protobuf:"varint,5,opt,name=order_total,json=orderTotal,proto3" json:"order_total,omitempty"`
	WarehouseId         uint64                 `protobuf:"varint,6,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	TeamId              uint64                 `protobuf:"varint,7,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ShippingId          uint64                 `protobuf:"varint,8,opt,name=shipping_id,json=shippingId,proto3" json:"shipping_id,omitempty"`
	ShipmentFee         float64                `protobuf:"fixed64,9,opt,name=shipment_fee,json=shipmentFee,proto3" json:"shipment_fee,omitempty"`
	ShipmentPaymentType ShipmentPaymentType    `protobuf:"varint,10,opt,name=shipment_payment_type,json=shipmentPaymentType,proto3,enum=order_iface.v1.ShipmentPaymentType" json:"shipment_payment_type,omitempty"`
	Receipt             string                 `protobuf:"bytes,11,opt,name=receipt,proto3" json:"receipt,omitempty"`
	ReceiptFile         string                 `protobuf:"bytes,12,opt,name=receipt_file,json=receiptFile,proto3" json:"receipt_file,omitempty"`
	Address             *OrderAddress          `protobuf:"bytes,13,opt,name=address,proto3" json:"address,omitempty"`
	Items               []*OrderItem           `protobuf:"bytes,14,rep,name=items,proto3" json:"items,omitempty"`
	BundleIds           []uint64               `protobuf:"varint,15,rep,packed,name=bundle_ids,json=bundleIds,proto3" json:"bundle_ids,omitempty"`
	DraftId             uint64                 `protobuf:"varint,16,opt,name=draft_id,json=draftId,proto3" json:"draft_id,omitempty"`
	OrderDeadline       *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=order_deadline,json=orderDeadline,proto3" json:"order_deadline,omitempty"`
	BuyerUsername       string                 `protobuf:"bytes,18,opt,name=buyer_username,json=buyerUsername,proto3" json:"buyer_username,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *OrderCreateRequest) Reset() {
	*x = OrderCreateRequest{}
	mi := &file_order_iface_v1_create_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateRequest) ProtoMessage() {}

func (x *OrderCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_create_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateRequest.ProtoReflect.Descriptor instead.
func (*OrderCreateRequest) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_create_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCreateRequest) GetOrderRefId() string {
	if x != nil {
		return x.OrderRefId
	}
	return ""
}

func (x *OrderCreateRequest) GetOrderMpId() uint64 {
	if x != nil {
		return x.OrderMpId
	}
	return 0
}

func (x *OrderCreateRequest) GetOrderFrom() v1.MarketplaceType {
	if x != nil {
		return x.OrderFrom
	}
	return v1.MarketplaceType(0)
}

func (x *OrderCreateRequest) GetOrderTime() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderTime
	}
	return nil
}

func (x *OrderCreateRequest) GetOrderTotal() int64 {
	if x != nil {
		return x.OrderTotal
	}
	return 0
}

func (x *OrderCreateRequest) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *OrderCreateRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *OrderCreateRequest) GetShippingId() uint64 {
	if x != nil {
		return x.ShippingId
	}
	return 0
}

func (x *OrderCreateRequest) GetShipmentFee() float64 {
	if x != nil {
		return x.ShipmentFee
	}
	return 0
}

func (x *OrderCreateRequest) GetShipmentPaymentType() ShipmentPaymentType {
	if x != nil {
		return x.ShipmentPaymentType
	}
	return ShipmentPaymentType_SHIPMENT_PAYMENT_TYPE_UNSPECIFIED
}

func (x *OrderCreateRequest) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

func (x *OrderCreateRequest) GetReceiptFile() string {
	if x != nil {
		return x.ReceiptFile
	}
	return ""
}

func (x *OrderCreateRequest) GetAddress() *OrderAddress {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *OrderCreateRequest) GetItems() []*OrderItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *OrderCreateRequest) GetBundleIds() []uint64 {
	if x != nil {
		return x.BundleIds
	}
	return nil
}

func (x *OrderCreateRequest) GetDraftId() uint64 {
	if x != nil {
		return x.DraftId
	}
	return 0
}

func (x *OrderCreateRequest) GetOrderDeadline() *timestamppb.Timestamp {
	if x != nil {
		return x.OrderDeadline
	}
	return nil
}

func (x *OrderCreateRequest) GetBuyerUsername() string {
	if x != nil {
		return x.BuyerUsername
	}
	return ""
}

type OrderCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCreateResponse) Reset() {
	*x = OrderCreateResponse{}
	mi := &file_order_iface_v1_create_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCreateResponse) ProtoMessage() {}

func (x *OrderCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_create_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCreateResponse.ProtoReflect.Descriptor instead.
func (*OrderCreateResponse) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_create_proto_rawDescGZIP(), []int{3}
}

var File_order_iface_v1_create_proto protoreflect.FileDescriptor

const file_order_iface_v1_create_proto_rawDesc = "" +
	"\n" +
	"\x1border_iface/v1/create.proto\x12\x0eorder_iface.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x8e\x02\n" +
	"\fOrderAddress\x12\x1e\n" +
	"\x04name\x18\x01 \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\x80\x01R\x04name\x12\x1f\n" +
	"\x05phone\x18\x02 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\x14R\x05phone\x12%\n" +
	"\bprovince\x18\x03 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\bprovince\x12\x1d\n" +
	"\x04city\x18\x04 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\x04city\x12%\n" +
	"\bdistrict\x18\x05 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\bdistrict\x12*\n" +
	"\vpostal_code\x18\x06 \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18\n" +
	"R\n" +
	"postalCode\x12$\n" +
	"\aaddress\x18\a \x01(\tB\n" +
	"\xbaH\ar\x05\x10\x01\x18\xac\x02R\aaddress\"~\n" +
	"\tOrderItem\x12&\n" +
	"\n" +
	"product_id\x18\x01 \x01(\x04B\a\xbaH\x042\x02 \x00R\tproductId\x12*\n" +
	"\fvariation_id\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\vvariationId\x12\x1d\n" +
	"\x05count\x18\x03 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x05count\"\xf4\x06\n" +
	"\x12OrderCreateRequest\x12)\n" +
	"\forder_ref_id\x18\x01 \x01(\tB\a\xbaH\x04r\x02\x10\x01R\n" +
	"orderRefId\x12'\n" +
	"\vorder_mp_id\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\torderMpId\x129\n" +
	"\n" +
	"order_from\x18\x03 \x01(\x0e2\x1a.common.v1.MarketplaceTypeR\torderFrom\x12A\n" +
	"\n" +
	"order_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\torderTime\x12(\n" +
	"\vorder_total\x18\x05 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\n" +
	"orderTotal\x12*\n" +
	"\fwarehouse_id\x18\x06 \x01(\x04B\a\xbaH\x042\x02 \x00R\vwarehouseId\x12 \n" +
	"\ateam_id\x18\a \x01(\x04B\a\xbaH\x042\x02 \x00R\x06teamId\x12(\n" +
	"\vshipping_id\x18\b \x01(\x04B\a\xbaH\x042\x02 \x00R\n" +
	"shippingId\x12!\n" +
	"\fshipment_fee\x18\t \x01(\x01R\vshipmentFee\x12W\n" +
	"\x15shipment_payment_type\x18\n" +
	" \x01(\x0e2#.order_iface.v1.ShipmentPaymentTypeR\x13shipmentPaymentType\x12#\n" +
	"\areceipt\x18\v \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\areceipt\x12,\n" +
	"\freceipt_file\x18\f \x01(\tB\t\xbaH\x06r\x04\x10\x01\x18dR\vreceiptFile\x12>\n" +
	"\aaddress\x18\r \x01(\v2\x1c.order_iface.v1.OrderAddressB\x06\xbaH\x03\xc8\x01\x01R\aaddress\x127\n" +
	"\x05items\x18\x0e \x03(\v2\x19.order_iface.v1.OrderItemB\x06\xbaH\x03\xc8\x01\x01R\x05items\x12\x1d\n" +
	"\n" +
	"bundle_ids\x18\x0f \x03(\x04R\tbundleIds\x12\x19\n" +
	"\bdraft_id\x18\x10 \x01(\x04R\adraftId\x12A\n" +
	"\x0eorder_deadline\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\rorderDeadline\x12%\n" +
	"\x0ebuyer_username\x18\x12 \x01(\tR\rbuyerUsername\"\x15\n" +
	"\x13OrderCreateResponse*\x82\x01\n" +
	"\x13ShipmentPaymentType\x12%\n" +
	"!SHIPMENT_PAYMENT_TYPE_UNSPECIFIED\x10\x00\x12#\n" +
	"\x1fSHIPMENT_PAYMENT_TYPE_WAREHOUSE\x10\x01\x12\x1f\n" +
	"\x1bSHIPMENT_PAYMENT_TYPE_BUYER\x10\x02B\xb3\x01\n" +
	"\x12com.order_iface.v1B\vCreateProtoP\x01Z;github.com/pdcgo/schema/services/order_iface/v1;order_iface\xa2\x02\x03OXX\xaa\x02\rOrderIface.V1\xca\x02\rOrderIface\\V1\xe2\x02\x19OrderIface\\V1\\GPBMetadata\xea\x02\x0eOrderIface::V1b\x06proto3"

var (
	file_order_iface_v1_create_proto_rawDescOnce sync.Once
	file_order_iface_v1_create_proto_rawDescData []byte
)

func file_order_iface_v1_create_proto_rawDescGZIP() []byte {
	file_order_iface_v1_create_proto_rawDescOnce.Do(func() {
		file_order_iface_v1_create_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_iface_v1_create_proto_rawDesc), len(file_order_iface_v1_create_proto_rawDesc)))
	})
	return file_order_iface_v1_create_proto_rawDescData
}

var file_order_iface_v1_create_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_iface_v1_create_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_order_iface_v1_create_proto_goTypes = []any{
	(ShipmentPaymentType)(0),      // 0: order_iface.v1.ShipmentPaymentType
	(*OrderAddress)(nil),          // 1: order_iface.v1.OrderAddress
	(*OrderItem)(nil),             // 2: order_iface.v1.OrderItem
	(*OrderCreateRequest)(nil),    // 3: order_iface.v1.OrderCreateRequest
	(*OrderCreateResponse)(nil),   // 4: order_iface.v1.OrderCreateResponse
	(v1.MarketplaceType)(0),       // 5: common.v1.MarketplaceType
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
}
var file_order_iface_v1_create_proto_depIdxs = []int32{
	5, // 0: order_iface.v1.OrderCreateRequest.order_from:type_name -> common.v1.MarketplaceType
	6, // 1: order_iface.v1.OrderCreateRequest.order_time:type_name -> google.protobuf.Timestamp
	0, // 2: order_iface.v1.OrderCreateRequest.shipment_payment_type:type_name -> order_iface.v1.ShipmentPaymentType
	1, // 3: order_iface.v1.OrderCreateRequest.address:type_name -> order_iface.v1.OrderAddress
	2, // 4: order_iface.v1.OrderCreateRequest.items:type_name -> order_iface.v1.OrderItem
	6, // 5: order_iface.v1.OrderCreateRequest.order_deadline:type_name -> google.protobuf.Timestamp
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_order_iface_v1_create_proto_init() }
func file_order_iface_v1_create_proto_init() {
	if File_order_iface_v1_create_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_iface_v1_create_proto_rawDesc), len(file_order_iface_v1_create_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_iface_v1_create_proto_goTypes,
		DependencyIndexes: file_order_iface_v1_create_proto_depIdxs,
		EnumInfos:         file_order_iface_v1_create_proto_enumTypes,
		MessageInfos:      file_order_iface_v1_create_proto_msgTypes,
	}.Build()
	File_order_iface_v1_create_proto = out.File
	file_order_iface_v1_create_proto_goTypes = nil
	file_order_iface_v1_create_proto_depIdxs = nil
}
