// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: order_iface/v1/order.proto

package order_iface

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagType int32

const (
	TagType_TAG_TYPE_UNSPECIFIED TagType = 0
	TagType_TAG_TYPE_TRACKING    TagType = 1
)

// Enum value maps for TagType.
var (
	TagType_name = map[int32]string{
		0: "TAG_TYPE_UNSPECIFIED",
		1: "TAG_TYPE_TRACKING",
	}
	TagType_value = map[string]int32{
		"TAG_TYPE_UNSPECIFIED": 0,
		"TAG_TYPE_TRACKING":    1,
	}
)

func (x TagType) Enum() *TagType {
	p := new(TagType)
	*p = x
	return p
}

func (x TagType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TagType) Descriptor() protoreflect.EnumDescriptor {
	return file_order_iface_v1_order_proto_enumTypes[0].Descriptor()
}

func (TagType) Type() protoreflect.EnumType {
	return &file_order_iface_v1_order_proto_enumTypes[0]
}

func (x TagType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TagType.Descriptor instead.
func (TagType) EnumDescriptor() ([]byte, []int) {
	return file_order_iface_v1_order_proto_rawDescGZIP(), []int{0}
}

type OrderTagRemoveRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	OrderId       uint64                 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	TagType       TagType                `protobuf:"varint,3,opt,name=tag_type,json=tagType,proto3,enum=order_iface.v1.TagType" json:"tag_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTagRemoveRequest) Reset() {
	*x = OrderTagRemoveRequest{}
	mi := &file_order_iface_v1_order_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTagRemoveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTagRemoveRequest) ProtoMessage() {}

func (x *OrderTagRemoveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_order_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTagRemoveRequest.ProtoReflect.Descriptor instead.
func (*OrderTagRemoveRequest) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_order_proto_rawDescGZIP(), []int{0}
}

func (x *OrderTagRemoveRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *OrderTagRemoveRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OrderTagRemoveRequest) GetTagType() TagType {
	if x != nil {
		return x.TagType
	}
	return TagType_TAG_TYPE_UNSPECIFIED
}

type OrderTagRemoveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderTagRemoveResponse) Reset() {
	*x = OrderTagRemoveResponse{}
	mi := &file_order_iface_v1_order_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderTagRemoveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderTagRemoveResponse) ProtoMessage() {}

func (x *OrderTagRemoveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_order_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderTagRemoveResponse.ProtoReflect.Descriptor instead.
func (*OrderTagRemoveResponse) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_order_proto_rawDescGZIP(), []int{1}
}

type OrderFundSet struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TeamId uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Types that are valid to be assigned to OrderIdentifier:
	//
	//	*OrderFundSet_OrderId
	//	*OrderFundSet_OrderRefId
	OrderIdentifier isOrderFundSet_OrderIdentifier `protobuf_oneof:"order_identifier"`
	Amount          float64                        `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	At              *timestamppb.Timestamp         `protobuf:"bytes,6,opt,name=at,proto3" json:"at,omitempty"`
	Desc            string                         `protobuf:"bytes,7,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderFundSet) Reset() {
	*x = OrderFundSet{}
	mi := &file_order_iface_v1_order_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFundSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFundSet) ProtoMessage() {}

func (x *OrderFundSet) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_order_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFundSet.ProtoReflect.Descriptor instead.
func (*OrderFundSet) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_order_proto_rawDescGZIP(), []int{2}
}

func (x *OrderFundSet) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *OrderFundSet) GetOrderIdentifier() isOrderFundSet_OrderIdentifier {
	if x != nil {
		return x.OrderIdentifier
	}
	return nil
}

func (x *OrderFundSet) GetOrderId() uint64 {
	if x != nil {
		if x, ok := x.OrderIdentifier.(*OrderFundSet_OrderId); ok {
			return x.OrderId
		}
	}
	return 0
}

func (x *OrderFundSet) GetOrderRefId() string {
	if x != nil {
		if x, ok := x.OrderIdentifier.(*OrderFundSet_OrderRefId); ok {
			return x.OrderRefId
		}
	}
	return ""
}

func (x *OrderFundSet) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *OrderFundSet) GetAt() *timestamppb.Timestamp {
	if x != nil {
		return x.At
	}
	return nil
}

func (x *OrderFundSet) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type isOrderFundSet_OrderIdentifier interface {
	isOrderFundSet_OrderIdentifier()
}

type OrderFundSet_OrderId struct {
	OrderId uint64 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3,oneof"`
}

type OrderFundSet_OrderRefId struct {
	OrderRefId string `protobuf:"bytes,3,opt,name=order_ref_id,json=orderRefId,proto3,oneof"`
}

func (*OrderFundSet_OrderId) isOrderFundSet_OrderIdentifier() {}

func (*OrderFundSet_OrderRefId) isOrderFundSet_OrderIdentifier() {}

type OrderCompletedSet struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TeamId uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	// Types that are valid to be assigned to OrderIdentifier:
	//
	//	*OrderCompletedSet_OrderId
	//	*OrderCompletedSet_OrderRefId
	OrderIdentifier isOrderCompletedSet_OrderIdentifier `protobuf_oneof:"order_identifier"`
	WdAt            *timestamppb.Timestamp              `protobuf:"bytes,6,opt,name=wd_at,json=wdAt,proto3" json:"wd_at,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *OrderCompletedSet) Reset() {
	*x = OrderCompletedSet{}
	mi := &file_order_iface_v1_order_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCompletedSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCompletedSet) ProtoMessage() {}

func (x *OrderCompletedSet) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_order_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCompletedSet.ProtoReflect.Descriptor instead.
func (*OrderCompletedSet) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_order_proto_rawDescGZIP(), []int{3}
}

func (x *OrderCompletedSet) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *OrderCompletedSet) GetOrderIdentifier() isOrderCompletedSet_OrderIdentifier {
	if x != nil {
		return x.OrderIdentifier
	}
	return nil
}

func (x *OrderCompletedSet) GetOrderId() uint64 {
	if x != nil {
		if x, ok := x.OrderIdentifier.(*OrderCompletedSet_OrderId); ok {
			return x.OrderId
		}
	}
	return 0
}

func (x *OrderCompletedSet) GetOrderRefId() string {
	if x != nil {
		if x, ok := x.OrderIdentifier.(*OrderCompletedSet_OrderRefId); ok {
			return x.OrderRefId
		}
	}
	return ""
}

func (x *OrderCompletedSet) GetWdAt() *timestamppb.Timestamp {
	if x != nil {
		return x.WdAt
	}
	return nil
}

type isOrderCompletedSet_OrderIdentifier interface {
	isOrderCompletedSet_OrderIdentifier()
}

type OrderCompletedSet_OrderId struct {
	OrderId uint64 `protobuf:"varint,2,opt,name=order_id,json=orderId,proto3,oneof"`
}

type OrderCompletedSet_OrderRefId struct {
	OrderRefId string `protobuf:"bytes,3,opt,name=order_ref_id,json=orderRefId,proto3,oneof"`
}

func (*OrderCompletedSet_OrderId) isOrderCompletedSet_OrderIdentifier() {}

func (*OrderCompletedSet_OrderRefId) isOrderCompletedSet_OrderIdentifier() {}

type OrderFundRollback struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFundRollback) Reset() {
	*x = OrderFundRollback{}
	mi := &file_order_iface_v1_order_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFundRollback) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFundRollback) ProtoMessage() {}

func (x *OrderFundRollback) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_order_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFundRollback.ProtoReflect.Descriptor instead.
func (*OrderFundRollback) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_order_proto_rawDescGZIP(), []int{4}
}

func (x *OrderFundRollback) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OrderFundSetRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*OrderFundSetRequest_OrderFundSet
	//	*OrderFundSetRequest_OrderCompletedSet
	//	*OrderFundSetRequest_OrderFundRollback
	Kind          isOrderFundSetRequest_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFundSetRequest) Reset() {
	*x = OrderFundSetRequest{}
	mi := &file_order_iface_v1_order_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFundSetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFundSetRequest) ProtoMessage() {}

func (x *OrderFundSetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_order_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFundSetRequest.ProtoReflect.Descriptor instead.
func (*OrderFundSetRequest) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_order_proto_rawDescGZIP(), []int{5}
}

func (x *OrderFundSetRequest) GetKind() isOrderFundSetRequest_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *OrderFundSetRequest) GetOrderFundSet() *OrderFundSet {
	if x != nil {
		if x, ok := x.Kind.(*OrderFundSetRequest_OrderFundSet); ok {
			return x.OrderFundSet
		}
	}
	return nil
}

func (x *OrderFundSetRequest) GetOrderCompletedSet() *OrderCompletedSet {
	if x != nil {
		if x, ok := x.Kind.(*OrderFundSetRequest_OrderCompletedSet); ok {
			return x.OrderCompletedSet
		}
	}
	return nil
}

func (x *OrderFundSetRequest) GetOrderFundRollback() *OrderFundRollback {
	if x != nil {
		if x, ok := x.Kind.(*OrderFundSetRequest_OrderFundRollback); ok {
			return x.OrderFundRollback
		}
	}
	return nil
}

type isOrderFundSetRequest_Kind interface {
	isOrderFundSetRequest_Kind()
}

type OrderFundSetRequest_OrderFundSet struct {
	OrderFundSet *OrderFundSet `protobuf:"bytes,1,opt,name=order_fund_set,json=orderFundSet,proto3,oneof"`
}

type OrderFundSetRequest_OrderCompletedSet struct {
	OrderCompletedSet *OrderCompletedSet `protobuf:"bytes,2,opt,name=order_completed_set,json=orderCompletedSet,proto3,oneof"`
}

type OrderFundSetRequest_OrderFundRollback struct {
	OrderFundRollback *OrderFundRollback `protobuf:"bytes,3,opt,name=order_fund_rollback,json=orderFundRollback,proto3,oneof"`
}

func (*OrderFundSetRequest_OrderFundSet) isOrderFundSetRequest_Kind() {}

func (*OrderFundSetRequest_OrderCompletedSet) isOrderFundSetRequest_Kind() {}

func (*OrderFundSetRequest_OrderFundRollback) isOrderFundSetRequest_Kind() {}

type OrderFundSetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderFundSetResponse) Reset() {
	*x = OrderFundSetResponse{}
	mi := &file_order_iface_v1_order_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderFundSetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderFundSetResponse) ProtoMessage() {}

func (x *OrderFundSetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_order_iface_v1_order_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderFundSetResponse.ProtoReflect.Descriptor instead.
func (*OrderFundSetResponse) Descriptor() ([]byte, []int) {
	return file_order_iface_v1_order_proto_rawDescGZIP(), []int{6}
}

var File_order_iface_v1_order_proto protoreflect.FileDescriptor

const file_order_iface_v1_order_proto_rawDesc = "" +
	"\n" +
	"\x1aorder_iface/v1/order.proto\x12\x0eorder_iface.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x7f\n" +
	"\x15OrderTagRemoveRequest\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\x12\x19\n" +
	"\border_id\x18\x02 \x01(\x04R\aorderId\x122\n" +
	"\btag_type\x18\x03 \x01(\x0e2\x17.order_iface.v1.TagTypeR\atagType\"\x18\n" +
	"\x16OrderTagRemoveResponse\"\x9c\x02\n" +
	"\fOrderFundSet\x12 \n" +
	"\ateam_id\x18\x01 \x01(\x04B\a\xbaH\x042\x02 \x00R\x06teamId\x12\x1b\n" +
	"\border_id\x18\x02 \x01(\x04H\x00R\aorderId\x12\"\n" +
	"\forder_ref_id\x18\x03 \x01(\tH\x00R\n" +
	"orderRefId\x12M\n" +
	"\x06amount\x18\x05 \x01(\x01B5\xbaH2\xba\x01/\n" +
	"\bnot_zero\x12\x15amount cannot be zero\x1a\fthis != 0.00R\x06amount\x122\n" +
	"\x02at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x02at\x12\x12\n" +
	"\x04desc\x18\a \x01(\tR\x04descB\x12\n" +
	"\x10order_identifier\"\xba\x01\n" +
	"\x11OrderCompletedSet\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\x12\x1b\n" +
	"\border_id\x18\x02 \x01(\x04H\x00R\aorderId\x12\"\n" +
	"\forder_ref_id\x18\x03 \x01(\tH\x00R\n" +
	"orderRefId\x127\n" +
	"\x05wd_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x04wdAtB\x12\n" +
	"\x10order_identifier\"-\n" +
	"\x11OrderFundRollback\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x8d\x02\n" +
	"\x13OrderFundSetRequest\x12D\n" +
	"\x0eorder_fund_set\x18\x01 \x01(\v2\x1c.order_iface.v1.OrderFundSetH\x00R\forderFundSet\x12S\n" +
	"\x13order_completed_set\x18\x02 \x01(\v2!.order_iface.v1.OrderCompletedSetH\x00R\x11orderCompletedSet\x12S\n" +
	"\x13order_fund_rollback\x18\x03 \x01(\v2!.order_iface.v1.OrderFundRollbackH\x00R\x11orderFundRollbackB\x06\n" +
	"\x04kind\"\x16\n" +
	"\x14OrderFundSetResponse*:\n" +
	"\aTagType\x12\x18\n" +
	"\x14TAG_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TAG_TYPE_TRACKING\x10\x012\xcc\x01\n" +
	"\fOrderService\x12[\n" +
	"\fOrderFundSet\x12#.order_iface.v1.OrderFundSetRequest\x1a$.order_iface.v1.OrderFundSetResponse(\x01\x12_\n" +
	"\x0eOrderTagRemove\x12%.order_iface.v1.OrderTagRemoveRequest\x1a&.order_iface.v1.OrderTagRemoveResponseB\xb2\x01\n" +
	"\x12com.order_iface.v1B\n" +
	"OrderProtoP\x01Z;github.com/pdcgo/schema/services/order_iface/v1;order_iface\xa2\x02\x03OXX\xaa\x02\rOrderIface.V1\xca\x02\rOrderIface\\V1\xe2\x02\x19OrderIface\\V1\\GPBMetadata\xea\x02\x0eOrderIface::V1b\x06proto3"

var (
	file_order_iface_v1_order_proto_rawDescOnce sync.Once
	file_order_iface_v1_order_proto_rawDescData []byte
)

func file_order_iface_v1_order_proto_rawDescGZIP() []byte {
	file_order_iface_v1_order_proto_rawDescOnce.Do(func() {
		file_order_iface_v1_order_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_iface_v1_order_proto_rawDesc), len(file_order_iface_v1_order_proto_rawDesc)))
	})
	return file_order_iface_v1_order_proto_rawDescData
}

var file_order_iface_v1_order_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_order_iface_v1_order_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_order_iface_v1_order_proto_goTypes = []any{
	(TagType)(0),                   // 0: order_iface.v1.TagType
	(*OrderTagRemoveRequest)(nil),  // 1: order_iface.v1.OrderTagRemoveRequest
	(*OrderTagRemoveResponse)(nil), // 2: order_iface.v1.OrderTagRemoveResponse
	(*OrderFundSet)(nil),           // 3: order_iface.v1.OrderFundSet
	(*OrderCompletedSet)(nil),      // 4: order_iface.v1.OrderCompletedSet
	(*OrderFundRollback)(nil),      // 5: order_iface.v1.OrderFundRollback
	(*OrderFundSetRequest)(nil),    // 6: order_iface.v1.OrderFundSetRequest
	(*OrderFundSetResponse)(nil),   // 7: order_iface.v1.OrderFundSetResponse
	(*timestamppb.Timestamp)(nil),  // 8: google.protobuf.Timestamp
}
var file_order_iface_v1_order_proto_depIdxs = []int32{
	0, // 0: order_iface.v1.OrderTagRemoveRequest.tag_type:type_name -> order_iface.v1.TagType
	8, // 1: order_iface.v1.OrderFundSet.at:type_name -> google.protobuf.Timestamp
	8, // 2: order_iface.v1.OrderCompletedSet.wd_at:type_name -> google.protobuf.Timestamp
	3, // 3: order_iface.v1.OrderFundSetRequest.order_fund_set:type_name -> order_iface.v1.OrderFundSet
	4, // 4: order_iface.v1.OrderFundSetRequest.order_completed_set:type_name -> order_iface.v1.OrderCompletedSet
	5, // 5: order_iface.v1.OrderFundSetRequest.order_fund_rollback:type_name -> order_iface.v1.OrderFundRollback
	6, // 6: order_iface.v1.OrderService.OrderFundSet:input_type -> order_iface.v1.OrderFundSetRequest
	1, // 7: order_iface.v1.OrderService.OrderTagRemove:input_type -> order_iface.v1.OrderTagRemoveRequest
	7, // 8: order_iface.v1.OrderService.OrderFundSet:output_type -> order_iface.v1.OrderFundSetResponse
	2, // 9: order_iface.v1.OrderService.OrderTagRemove:output_type -> order_iface.v1.OrderTagRemoveResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_order_iface_v1_order_proto_init() }
func file_order_iface_v1_order_proto_init() {
	if File_order_iface_v1_order_proto != nil {
		return
	}
	file_order_iface_v1_order_proto_msgTypes[2].OneofWrappers = []any{
		(*OrderFundSet_OrderId)(nil),
		(*OrderFundSet_OrderRefId)(nil),
	}
	file_order_iface_v1_order_proto_msgTypes[3].OneofWrappers = []any{
		(*OrderCompletedSet_OrderId)(nil),
		(*OrderCompletedSet_OrderRefId)(nil),
	}
	file_order_iface_v1_order_proto_msgTypes[5].OneofWrappers = []any{
		(*OrderFundSetRequest_OrderFundSet)(nil),
		(*OrderFundSetRequest_OrderCompletedSet)(nil),
		(*OrderFundSetRequest_OrderFundRollback)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_iface_v1_order_proto_rawDesc), len(file_order_iface_v1_order_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_order_iface_v1_order_proto_goTypes,
		DependencyIndexes: file_order_iface_v1_order_proto_depIdxs,
		EnumInfos:         file_order_iface_v1_order_proto_enumTypes,
		MessageInfos:      file_order_iface_v1_order_proto_msgTypes,
	}.Build()
	File_order_iface_v1_order_proto = out.File
	file_order_iface_v1_order_proto_goTypes = nil
	file_order_iface_v1_order_proto_depIdxs = nil
}
