// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: selling_iface/v1/revenue.proto

package selling_ifaceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pdcgo/schema/services/selling_iface/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// RevenueServiceName is the fully-qualified name of the RevenueService service.
	RevenueServiceName = "selling_iface.v1.RevenueService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// RevenueServiceHelloWorldProcedure is the fully-qualified name of the RevenueService's HelloWorld
	// RPC.
	RevenueServiceHelloWorldProcedure = "/selling_iface.v1.RevenueService/HelloWorld"
	// RevenueServiceWithdrawalCreateProcedure is the fully-qualified name of the RevenueService's
	// WithdrawalCreate RPC.
	RevenueServiceWithdrawalCreateProcedure = "/selling_iface.v1.RevenueService/WithdrawalCreate"
	// RevenueServiceWithdrawalUpdateProcedure is the fully-qualified name of the RevenueService's
	// WithdrawalUpdate RPC.
	RevenueServiceWithdrawalUpdateProcedure = "/selling_iface.v1.RevenueService/WithdrawalUpdate"
	// RevenueServiceWithdrawalDeleteProcedure is the fully-qualified name of the RevenueService's
	// WithdrawalDelete RPC.
	RevenueServiceWithdrawalDeleteProcedure = "/selling_iface.v1.RevenueService/WithdrawalDelete"
	// RevenueServiceWithdrawalListProcedure is the fully-qualified name of the RevenueService's
	// WithdrawalList RPC.
	RevenueServiceWithdrawalListProcedure = "/selling_iface.v1.RevenueService/WithdrawalList"
	// RevenueServiceWithdrawalLogListProcedure is the fully-qualified name of the RevenueService's
	// WithdrawalLogList RPC.
	RevenueServiceWithdrawalLogListProcedure = "/selling_iface.v1.RevenueService/WithdrawalLogList"
)

// RevenueServiceClient is a client for the selling_iface.v1.RevenueService service.
type RevenueServiceClient interface {
	HelloWorld(context.Context, *connect.Request[v1.HelloWorldRequest]) (*connect.Response[v1.HelloWorldResponse], error)
	// Withdrawal ledger — team-scoped, per-shop funds withdrawn from a marketplace.
	// Create/Update/Delete each write a WithdrawalLog row in the same transaction;
	// WithdrawalLogList returns that change history. Delete is a soft delete that frees
	// the (team_id, ref_id, source) unique key by renaming ref_id.
	WithdrawalCreate(context.Context, *connect.Request[v1.WithdrawalCreateRequest]) (*connect.Response[v1.WithdrawalCreateResponse], error)
	WithdrawalUpdate(context.Context, *connect.Request[v1.WithdrawalUpdateRequest]) (*connect.Response[v1.WithdrawalUpdateResponse], error)
	WithdrawalDelete(context.Context, *connect.Request[v1.WithdrawalDeleteRequest]) (*connect.Response[v1.WithdrawalDeleteResponse], error)
	WithdrawalList(context.Context, *connect.Request[v1.WithdrawalListRequest]) (*connect.Response[v1.WithdrawalListResponse], error)
	WithdrawalLogList(context.Context, *connect.Request[v1.WithdrawalLogListRequest]) (*connect.Response[v1.WithdrawalLogListResponse], error)
}

// NewRevenueServiceClient constructs a client for the selling_iface.v1.RevenueService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewRevenueServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) RevenueServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	revenueServiceMethods := v1.File_selling_iface_v1_revenue_proto.Services().ByName("RevenueService").Methods()
	return &revenueServiceClient{
		helloWorld: connect.NewClient[v1.HelloWorldRequest, v1.HelloWorldResponse](
			httpClient,
			baseURL+RevenueServiceHelloWorldProcedure,
			connect.WithSchema(revenueServiceMethods.ByName("HelloWorld")),
			connect.WithClientOptions(opts...),
		),
		withdrawalCreate: connect.NewClient[v1.WithdrawalCreateRequest, v1.WithdrawalCreateResponse](
			httpClient,
			baseURL+RevenueServiceWithdrawalCreateProcedure,
			connect.WithSchema(revenueServiceMethods.ByName("WithdrawalCreate")),
			connect.WithClientOptions(opts...),
		),
		withdrawalUpdate: connect.NewClient[v1.WithdrawalUpdateRequest, v1.WithdrawalUpdateResponse](
			httpClient,
			baseURL+RevenueServiceWithdrawalUpdateProcedure,
			connect.WithSchema(revenueServiceMethods.ByName("WithdrawalUpdate")),
			connect.WithClientOptions(opts...),
		),
		withdrawalDelete: connect.NewClient[v1.WithdrawalDeleteRequest, v1.WithdrawalDeleteResponse](
			httpClient,
			baseURL+RevenueServiceWithdrawalDeleteProcedure,
			connect.WithSchema(revenueServiceMethods.ByName("WithdrawalDelete")),
			connect.WithClientOptions(opts...),
		),
		withdrawalList: connect.NewClient[v1.WithdrawalListRequest, v1.WithdrawalListResponse](
			httpClient,
			baseURL+RevenueServiceWithdrawalListProcedure,
			connect.WithSchema(revenueServiceMethods.ByName("WithdrawalList")),
			connect.WithClientOptions(opts...),
		),
		withdrawalLogList: connect.NewClient[v1.WithdrawalLogListRequest, v1.WithdrawalLogListResponse](
			httpClient,
			baseURL+RevenueServiceWithdrawalLogListProcedure,
			connect.WithSchema(revenueServiceMethods.ByName("WithdrawalLogList")),
			connect.WithClientOptions(opts...),
		),
	}
}

// revenueServiceClient implements RevenueServiceClient.
type revenueServiceClient struct {
	helloWorld        *connect.Client[v1.HelloWorldRequest, v1.HelloWorldResponse]
	withdrawalCreate  *connect.Client[v1.WithdrawalCreateRequest, v1.WithdrawalCreateResponse]
	withdrawalUpdate  *connect.Client[v1.WithdrawalUpdateRequest, v1.WithdrawalUpdateResponse]
	withdrawalDelete  *connect.Client[v1.WithdrawalDeleteRequest, v1.WithdrawalDeleteResponse]
	withdrawalList    *connect.Client[v1.WithdrawalListRequest, v1.WithdrawalListResponse]
	withdrawalLogList *connect.Client[v1.WithdrawalLogListRequest, v1.WithdrawalLogListResponse]
}

// HelloWorld calls selling_iface.v1.RevenueService.HelloWorld.
func (c *revenueServiceClient) HelloWorld(ctx context.Context, req *connect.Request[v1.HelloWorldRequest]) (*connect.Response[v1.HelloWorldResponse], error) {
	return c.helloWorld.CallUnary(ctx, req)
}

// WithdrawalCreate calls selling_iface.v1.RevenueService.WithdrawalCreate.
func (c *revenueServiceClient) WithdrawalCreate(ctx context.Context, req *connect.Request[v1.WithdrawalCreateRequest]) (*connect.Response[v1.WithdrawalCreateResponse], error) {
	return c.withdrawalCreate.CallUnary(ctx, req)
}

// WithdrawalUpdate calls selling_iface.v1.RevenueService.WithdrawalUpdate.
func (c *revenueServiceClient) WithdrawalUpdate(ctx context.Context, req *connect.Request[v1.WithdrawalUpdateRequest]) (*connect.Response[v1.WithdrawalUpdateResponse], error) {
	return c.withdrawalUpdate.CallUnary(ctx, req)
}

// WithdrawalDelete calls selling_iface.v1.RevenueService.WithdrawalDelete.
func (c *revenueServiceClient) WithdrawalDelete(ctx context.Context, req *connect.Request[v1.WithdrawalDeleteRequest]) (*connect.Response[v1.WithdrawalDeleteResponse], error) {
	return c.withdrawalDelete.CallUnary(ctx, req)
}

// WithdrawalList calls selling_iface.v1.RevenueService.WithdrawalList.
func (c *revenueServiceClient) WithdrawalList(ctx context.Context, req *connect.Request[v1.WithdrawalListRequest]) (*connect.Response[v1.WithdrawalListResponse], error) {
	return c.withdrawalList.CallUnary(ctx, req)
}

// WithdrawalLogList calls selling_iface.v1.RevenueService.WithdrawalLogList.
func (c *revenueServiceClient) WithdrawalLogList(ctx context.Context, req *connect.Request[v1.WithdrawalLogListRequest]) (*connect.Response[v1.WithdrawalLogListResponse], error) {
	return c.withdrawalLogList.CallUnary(ctx, req)
}

// RevenueServiceHandler is an implementation of the selling_iface.v1.RevenueService service.
type RevenueServiceHandler interface {
	HelloWorld(context.Context, *connect.Request[v1.HelloWorldRequest]) (*connect.Response[v1.HelloWorldResponse], error)
	// Withdrawal ledger — team-scoped, per-shop funds withdrawn from a marketplace.
	// Create/Update/Delete each write a WithdrawalLog row in the same transaction;
	// WithdrawalLogList returns that change history. Delete is a soft delete that frees
	// the (team_id, ref_id, source) unique key by renaming ref_id.
	WithdrawalCreate(context.Context, *connect.Request[v1.WithdrawalCreateRequest]) (*connect.Response[v1.WithdrawalCreateResponse], error)
	WithdrawalUpdate(context.Context, *connect.Request[v1.WithdrawalUpdateRequest]) (*connect.Response[v1.WithdrawalUpdateResponse], error)
	WithdrawalDelete(context.Context, *connect.Request[v1.WithdrawalDeleteRequest]) (*connect.Response[v1.WithdrawalDeleteResponse], error)
	WithdrawalList(context.Context, *connect.Request[v1.WithdrawalListRequest]) (*connect.Response[v1.WithdrawalListResponse], error)
	WithdrawalLogList(context.Context, *connect.Request[v1.WithdrawalLogListRequest]) (*connect.Response[v1.WithdrawalLogListResponse], error)
}

// NewRevenueServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewRevenueServiceHandler(svc RevenueServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	revenueServiceMethods := v1.File_selling_iface_v1_revenue_proto.Services().ByName("RevenueService").Methods()
	revenueServiceHelloWorldHandler := connect.NewUnaryHandler(
		RevenueServiceHelloWorldProcedure,
		svc.HelloWorld,
		connect.WithSchema(revenueServiceMethods.ByName("HelloWorld")),
		connect.WithHandlerOptions(opts...),
	)
	revenueServiceWithdrawalCreateHandler := connect.NewUnaryHandler(
		RevenueServiceWithdrawalCreateProcedure,
		svc.WithdrawalCreate,
		connect.WithSchema(revenueServiceMethods.ByName("WithdrawalCreate")),
		connect.WithHandlerOptions(opts...),
	)
	revenueServiceWithdrawalUpdateHandler := connect.NewUnaryHandler(
		RevenueServiceWithdrawalUpdateProcedure,
		svc.WithdrawalUpdate,
		connect.WithSchema(revenueServiceMethods.ByName("WithdrawalUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	revenueServiceWithdrawalDeleteHandler := connect.NewUnaryHandler(
		RevenueServiceWithdrawalDeleteProcedure,
		svc.WithdrawalDelete,
		connect.WithSchema(revenueServiceMethods.ByName("WithdrawalDelete")),
		connect.WithHandlerOptions(opts...),
	)
	revenueServiceWithdrawalListHandler := connect.NewUnaryHandler(
		RevenueServiceWithdrawalListProcedure,
		svc.WithdrawalList,
		connect.WithSchema(revenueServiceMethods.ByName("WithdrawalList")),
		connect.WithHandlerOptions(opts...),
	)
	revenueServiceWithdrawalLogListHandler := connect.NewUnaryHandler(
		RevenueServiceWithdrawalLogListProcedure,
		svc.WithdrawalLogList,
		connect.WithSchema(revenueServiceMethods.ByName("WithdrawalLogList")),
		connect.WithHandlerOptions(opts...),
	)
	return "/selling_iface.v1.RevenueService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case RevenueServiceHelloWorldProcedure:
			revenueServiceHelloWorldHandler.ServeHTTP(w, r)
		case RevenueServiceWithdrawalCreateProcedure:
			revenueServiceWithdrawalCreateHandler.ServeHTTP(w, r)
		case RevenueServiceWithdrawalUpdateProcedure:
			revenueServiceWithdrawalUpdateHandler.ServeHTTP(w, r)
		case RevenueServiceWithdrawalDeleteProcedure:
			revenueServiceWithdrawalDeleteHandler.ServeHTTP(w, r)
		case RevenueServiceWithdrawalListProcedure:
			revenueServiceWithdrawalListHandler.ServeHTTP(w, r)
		case RevenueServiceWithdrawalLogListProcedure:
			revenueServiceWithdrawalLogListHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedRevenueServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedRevenueServiceHandler struct{}

func (UnimplementedRevenueServiceHandler) HelloWorld(context.Context, *connect.Request[v1.HelloWorldRequest]) (*connect.Response[v1.HelloWorldResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("selling_iface.v1.RevenueService.HelloWorld is not implemented"))
}

func (UnimplementedRevenueServiceHandler) WithdrawalCreate(context.Context, *connect.Request[v1.WithdrawalCreateRequest]) (*connect.Response[v1.WithdrawalCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("selling_iface.v1.RevenueService.WithdrawalCreate is not implemented"))
}

func (UnimplementedRevenueServiceHandler) WithdrawalUpdate(context.Context, *connect.Request[v1.WithdrawalUpdateRequest]) (*connect.Response[v1.WithdrawalUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("selling_iface.v1.RevenueService.WithdrawalUpdate is not implemented"))
}

func (UnimplementedRevenueServiceHandler) WithdrawalDelete(context.Context, *connect.Request[v1.WithdrawalDeleteRequest]) (*connect.Response[v1.WithdrawalDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("selling_iface.v1.RevenueService.WithdrawalDelete is not implemented"))
}

func (UnimplementedRevenueServiceHandler) WithdrawalList(context.Context, *connect.Request[v1.WithdrawalListRequest]) (*connect.Response[v1.WithdrawalListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("selling_iface.v1.RevenueService.WithdrawalList is not implemented"))
}

func (UnimplementedRevenueServiceHandler) WithdrawalLogList(context.Context, *connect.Request[v1.WithdrawalLogListRequest]) (*connect.Response[v1.WithdrawalLogListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("selling_iface.v1.RevenueService.WithdrawalLogList is not implemented"))
}
