// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: access_iface/v1/frontend.proto

package access_iface

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Policy int32

const (
	Policy_POLICY_UNSPECIFIED Policy = 0
	Policy_POLICY_ALLOW       Policy = 1
	Policy_POLICY_DENIED      Policy = 2
)

// Enum value maps for Policy.
var (
	Policy_name = map[int32]string{
		0: "POLICY_UNSPECIFIED",
		1: "POLICY_ALLOW",
		2: "POLICY_DENIED",
	}
	Policy_value = map[string]int32{
		"POLICY_UNSPECIFIED": 0,
		"POLICY_ALLOW":       1,
		"POLICY_DENIED":      2,
	}
)

func (x Policy) Enum() *Policy {
	p := new(Policy)
	*p = x
	return p
}

func (x Policy) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Policy) Descriptor() protoreflect.EnumDescriptor {
	return file_access_iface_v1_frontend_proto_enumTypes[0].Descriptor()
}

func (Policy) Type() protoreflect.EnumType {
	return &file_access_iface_v1_frontend_proto_enumTypes[0]
}

func (x Policy) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Policy.Descriptor instead.
func (Policy) EnumDescriptor() ([]byte, []int) {
	return file_access_iface_v1_frontend_proto_rawDescGZIP(), []int{0}
}

type SetupAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupAccessRequest) Reset() {
	*x = SetupAccessRequest{}
	mi := &file_access_iface_v1_frontend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupAccessRequest) ProtoMessage() {}

func (x *SetupAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_iface_v1_frontend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupAccessRequest.ProtoReflect.Descriptor instead.
func (*SetupAccessRequest) Descriptor() ([]byte, []int) {
	return file_access_iface_v1_frontend_proto_rawDescGZIP(), []int{0}
}

func (x *SetupAccessRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type SetupAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetupAccessResponse) Reset() {
	*x = SetupAccessResponse{}
	mi := &file_access_iface_v1_frontend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetupAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetupAccessResponse) ProtoMessage() {}

func (x *SetupAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_iface_v1_frontend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetupAccessResponse.ProtoReflect.Descriptor instead.
func (*SetupAccessResponse) Descriptor() ([]byte, []int) {
	return file_access_iface_v1_frontend_proto_rawDescGZIP(), []int{1}
}

type MenuAccessRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuAccessRequest) Reset() {
	*x = MenuAccessRequest{}
	mi := &file_access_iface_v1_frontend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuAccessRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuAccessRequest) ProtoMessage() {}

func (x *MenuAccessRequest) ProtoReflect() protoreflect.Message {
	mi := &file_access_iface_v1_frontend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuAccessRequest.ProtoReflect.Descriptor instead.
func (*MenuAccessRequest) Descriptor() ([]byte, []int) {
	return file_access_iface_v1_frontend_proto_rawDescGZIP(), []int{2}
}

func (x *MenuAccessRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type AccessItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policy        Policy                 `protobuf:"varint,1,opt,name=policy,proto3,enum=access_iface.v1.Policy" json:"policy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccessItem) Reset() {
	*x = AccessItem{}
	mi := &file_access_iface_v1_frontend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessItem) ProtoMessage() {}

func (x *AccessItem) ProtoReflect() protoreflect.Message {
	mi := &file_access_iface_v1_frontend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessItem.ProtoReflect.Descriptor instead.
func (*AccessItem) Descriptor() ([]byte, []int) {
	return file_access_iface_v1_frontend_proto_rawDescGZIP(), []int{3}
}

func (x *AccessItem) GetPolicy() Policy {
	if x != nil {
		return x.Policy
	}
	return Policy_POLICY_UNSPECIFIED
}

type MenuAccessResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[string]*AccessItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuAccessResponse) Reset() {
	*x = MenuAccessResponse{}
	mi := &file_access_iface_v1_frontend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuAccessResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuAccessResponse) ProtoMessage() {}

func (x *MenuAccessResponse) ProtoReflect() protoreflect.Message {
	mi := &file_access_iface_v1_frontend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuAccessResponse.ProtoReflect.Descriptor instead.
func (*MenuAccessResponse) Descriptor() ([]byte, []int) {
	return file_access_iface_v1_frontend_proto_rawDescGZIP(), []int{4}
}

func (x *MenuAccessResponse) GetData() map[string]*AccessItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_access_iface_v1_frontend_proto protoreflect.FileDescriptor

const file_access_iface_v1_frontend_proto_rawDesc = "" +
	"\n" +
	"\x1eaccess_iface/v1/frontend.proto\x12\x0faccess_iface.v1\x1a\x1bbuf/validate/validate.proto\"6\n" +
	"\x12SetupAccessRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\x04B\a\xbaH\x042\x02 \x00R\x06teamId\"\x15\n" +
	"\x13SetupAccessResponse\"5\n" +
	"\x11MenuAccessRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\x04B\a\xbaH\x042\x02 \x00R\x06teamId\"=\n" +
	"\n" +
	"AccessItem\x12/\n" +
	"\x06policy\x18\x01 \x01(\x0e2\x17.access_iface.v1.PolicyR\x06policy\"\xad\x01\n" +
	"\x12MenuAccessResponse\x12A\n" +
	"\x04data\x18\x01 \x03(\v2-.access_iface.v1.MenuAccessResponse.DataEntryR\x04data\x1aT\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.access_iface.v1.AccessItemR\x05value:\x028\x01*E\n" +
	"\x06Policy\x12\x16\n" +
	"\x12POLICY_UNSPECIFIED\x10\x00\x12\x10\n" +
	"\fPOLICY_ALLOW\x10\x01\x12\x11\n" +
	"\rPOLICY_DENIED\x10\x022\xca\x01\n" +
	"\x15FrontendAccessService\x12Z\n" +
	"\vSetupAccess\x12#.access_iface.v1.SetupAccessRequest\x1a$.access_iface.v1.SetupAccessResponse0\x01\x12U\n" +
	"\n" +
	"MenuAccess\x12\".access_iface.v1.MenuAccessRequest\x1a#.access_iface.v1.MenuAccessResponseB\xbc\x01\n" +
	"\x13com.access_iface.v1B\rFrontendProtoP\x01Z=github.com/pdcgo/schema/services/access_iface/v1;access_iface\xa2\x02\x03AXX\xaa\x02\x0eAccessIface.V1\xca\x02\x0eAccessIface\\V1\xe2\x02\x1aAccessIface\\V1\\GPBMetadata\xea\x02\x0fAccessIface::V1b\x06proto3"

var (
	file_access_iface_v1_frontend_proto_rawDescOnce sync.Once
	file_access_iface_v1_frontend_proto_rawDescData []byte
)

func file_access_iface_v1_frontend_proto_rawDescGZIP() []byte {
	file_access_iface_v1_frontend_proto_rawDescOnce.Do(func() {
		file_access_iface_v1_frontend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_access_iface_v1_frontend_proto_rawDesc), len(file_access_iface_v1_frontend_proto_rawDesc)))
	})
	return file_access_iface_v1_frontend_proto_rawDescData
}

var file_access_iface_v1_frontend_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_access_iface_v1_frontend_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_access_iface_v1_frontend_proto_goTypes = []any{
	(Policy)(0),                 // 0: access_iface.v1.Policy
	(*SetupAccessRequest)(nil),  // 1: access_iface.v1.SetupAccessRequest
	(*SetupAccessResponse)(nil), // 2: access_iface.v1.SetupAccessResponse
	(*MenuAccessRequest)(nil),   // 3: access_iface.v1.MenuAccessRequest
	(*AccessItem)(nil),          // 4: access_iface.v1.AccessItem
	(*MenuAccessResponse)(nil),  // 5: access_iface.v1.MenuAccessResponse
	nil,                         // 6: access_iface.v1.MenuAccessResponse.DataEntry
}
var file_access_iface_v1_frontend_proto_depIdxs = []int32{
	0, // 0: access_iface.v1.AccessItem.policy:type_name -> access_iface.v1.Policy
	6, // 1: access_iface.v1.MenuAccessResponse.data:type_name -> access_iface.v1.MenuAccessResponse.DataEntry
	4, // 2: access_iface.v1.MenuAccessResponse.DataEntry.value:type_name -> access_iface.v1.AccessItem
	1, // 3: access_iface.v1.FrontendAccessService.SetupAccess:input_type -> access_iface.v1.SetupAccessRequest
	3, // 4: access_iface.v1.FrontendAccessService.MenuAccess:input_type -> access_iface.v1.MenuAccessRequest
	2, // 5: access_iface.v1.FrontendAccessService.SetupAccess:output_type -> access_iface.v1.SetupAccessResponse
	5, // 6: access_iface.v1.FrontendAccessService.MenuAccess:output_type -> access_iface.v1.MenuAccessResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_access_iface_v1_frontend_proto_init() }
func file_access_iface_v1_frontend_proto_init() {
	if File_access_iface_v1_frontend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_access_iface_v1_frontend_proto_rawDesc), len(file_access_iface_v1_frontend_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_access_iface_v1_frontend_proto_goTypes,
		DependencyIndexes: file_access_iface_v1_frontend_proto_depIdxs,
		EnumInfos:         file_access_iface_v1_frontend_proto_enumTypes,
		MessageInfos:      file_access_iface_v1_frontend_proto_msgTypes,
	}.Build()
	File_access_iface_v1_frontend_proto = out.File
	file_access_iface_v1_frontend_proto_goTypes = nil
	file_access_iface_v1_frontend_proto_depIdxs = nil
}
