// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: invoice_iface/v2/v2_overview.proto

package invoice_iface

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/pdcgo/schema/services/common/v1"
	_ "github.com/pdcgo/schema/services/role_base/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverviewMetricType int32

const (
	OverviewMetricType_OVERVIEW_METRIC_TYPE_UNSPECIFIED      OverviewMetricType = 0
	OverviewMetricType_OVERVIEW_METRIC_TYPE_PAYABLE          OverviewMetricType = 1
	OverviewMetricType_OVERVIEW_METRIC_TYPE_RECEIVABLE       OverviewMetricType = 2
	OverviewMetricType_OVERVIEW_METRIC_TYPE_PENDING_PAYMENT  OverviewMetricType = 3
	OverviewMetricType_OVERVIEW_METRIC_TYPE_TOTAL_PAYMENT    OverviewMetricType = 4
	OverviewMetricType_OVERVIEW_METRIC_TYPE_TOTAL_PAYABLE    OverviewMetricType = 5
	OverviewMetricType_OVERVIEW_METRIC_TYPE_TOTAL_RECEIVABLE OverviewMetricType = 6
)

// Enum value maps for OverviewMetricType.
var (
	OverviewMetricType_name = map[int32]string{
		0: "OVERVIEW_METRIC_TYPE_UNSPECIFIED",
		1: "OVERVIEW_METRIC_TYPE_PAYABLE",
		2: "OVERVIEW_METRIC_TYPE_RECEIVABLE",
		3: "OVERVIEW_METRIC_TYPE_PENDING_PAYMENT",
		4: "OVERVIEW_METRIC_TYPE_TOTAL_PAYMENT",
		5: "OVERVIEW_METRIC_TYPE_TOTAL_PAYABLE",
		6: "OVERVIEW_METRIC_TYPE_TOTAL_RECEIVABLE",
	}
	OverviewMetricType_value = map[string]int32{
		"OVERVIEW_METRIC_TYPE_UNSPECIFIED":      0,
		"OVERVIEW_METRIC_TYPE_PAYABLE":          1,
		"OVERVIEW_METRIC_TYPE_RECEIVABLE":       2,
		"OVERVIEW_METRIC_TYPE_PENDING_PAYMENT":  3,
		"OVERVIEW_METRIC_TYPE_TOTAL_PAYMENT":    4,
		"OVERVIEW_METRIC_TYPE_TOTAL_PAYABLE":    5,
		"OVERVIEW_METRIC_TYPE_TOTAL_RECEIVABLE": 6,
	}
)

func (x OverviewMetricType) Enum() *OverviewMetricType {
	p := new(OverviewMetricType)
	*p = x
	return p
}

func (x OverviewMetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverviewMetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_invoice_iface_v2_v2_overview_proto_enumTypes[0].Descriptor()
}

func (OverviewMetricType) Type() protoreflect.EnumType {
	return &file_invoice_iface_v2_v2_overview_proto_enumTypes[0]
}

func (x OverviewMetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverviewMetricType.Descriptor instead.
func (OverviewMetricType) EnumDescriptor() ([]byte, []int) {
	return file_invoice_iface_v2_v2_overview_proto_rawDescGZIP(), []int{0}
}

type OverviewTimeFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewTimeFilter) Reset() {
	*x = OverviewTimeFilter{}
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewTimeFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewTimeFilter) ProtoMessage() {}

func (x *OverviewTimeFilter) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewTimeFilter.ProtoReflect.Descriptor instead.
func (*OverviewTimeFilter) Descriptor() ([]byte, []int) {
	return file_invoice_iface_v2_v2_overview_proto_rawDescGZIP(), []int{0}
}

func (x *OverviewTimeFilter) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *OverviewTimeFilter) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type OverviewFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	ForTeamId     uint64                 `protobuf:"varint,3,opt,name=for_team_id,json=forTeamId,proto3" json:"for_team_id,omitempty"`
	TeamType      v1.TeamType            `protobuf:"varint,4,opt,name=team_type,json=teamType,proto3,enum=common.v1.TeamType" json:"team_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewFilter) Reset() {
	*x = OverviewFilter{}
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewFilter) ProtoMessage() {}

func (x *OverviewFilter) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewFilter.ProtoReflect.Descriptor instead.
func (*OverviewFilter) Descriptor() ([]byte, []int) {
	return file_invoice_iface_v2_v2_overview_proto_rawDescGZIP(), []int{1}
}

func (x *OverviewFilter) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *OverviewFilter) GetForTeamId() uint64 {
	if x != nil {
		return x.ForTeamId
	}
	return 0
}

func (x *OverviewFilter) GetTeamType() v1.TeamType {
	if x != nil {
		return x.TeamType
	}
	return v1.TeamType(0)
}

type OverviewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimeRange     *OverviewTimeFilter    `protobuf:"bytes,1,opt,name=time_range,json=timeRange,proto3" json:"time_range,omitempty"`
	Filter        *OverviewFilter        `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	MetricType    []OverviewMetricType   `protobuf:"varint,3,rep,packed,name=metric_type,json=metricType,proto3,enum=invoice_iface.v2.OverviewMetricType" json:"metric_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewRequest) Reset() {
	*x = OverviewRequest{}
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewRequest) ProtoMessage() {}

func (x *OverviewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewRequest.ProtoReflect.Descriptor instead.
func (*OverviewRequest) Descriptor() ([]byte, []int) {
	return file_invoice_iface_v2_v2_overview_proto_rawDescGZIP(), []int{2}
}

func (x *OverviewRequest) GetTimeRange() *OverviewTimeFilter {
	if x != nil {
		return x.TimeRange
	}
	return nil
}

func (x *OverviewRequest) GetFilter() *OverviewFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *OverviewRequest) GetMetricType() []OverviewMetricType {
	if x != nil {
		return x.MetricType
	}
	return nil
}

type OverviewDataItem struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*OverviewDataItem_Payable
	//	*OverviewDataItem_Receivable
	//	*OverviewDataItem_PendingPayment
	//	*OverviewDataItem_TotalPayment
	//	*OverviewDataItem_TotalPayable
	//	*OverviewDataItem_TotalReceivable
	Data          isOverviewDataItem_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewDataItem) Reset() {
	*x = OverviewDataItem{}
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewDataItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewDataItem) ProtoMessage() {}

func (x *OverviewDataItem) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewDataItem.ProtoReflect.Descriptor instead.
func (*OverviewDataItem) Descriptor() ([]byte, []int) {
	return file_invoice_iface_v2_v2_overview_proto_rawDescGZIP(), []int{3}
}

func (x *OverviewDataItem) GetData() isOverviewDataItem_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OverviewDataItem) GetPayable() float64 {
	if x != nil {
		if x, ok := x.Data.(*OverviewDataItem_Payable); ok {
			return x.Payable
		}
	}
	return 0
}

func (x *OverviewDataItem) GetReceivable() float64 {
	if x != nil {
		if x, ok := x.Data.(*OverviewDataItem_Receivable); ok {
			return x.Receivable
		}
	}
	return 0
}

func (x *OverviewDataItem) GetPendingPayment() float64 {
	if x != nil {
		if x, ok := x.Data.(*OverviewDataItem_PendingPayment); ok {
			return x.PendingPayment
		}
	}
	return 0
}

func (x *OverviewDataItem) GetTotalPayment() float64 {
	if x != nil {
		if x, ok := x.Data.(*OverviewDataItem_TotalPayment); ok {
			return x.TotalPayment
		}
	}
	return 0
}

func (x *OverviewDataItem) GetTotalPayable() float64 {
	if x != nil {
		if x, ok := x.Data.(*OverviewDataItem_TotalPayable); ok {
			return x.TotalPayable
		}
	}
	return 0
}

func (x *OverviewDataItem) GetTotalReceivable() float64 {
	if x != nil {
		if x, ok := x.Data.(*OverviewDataItem_TotalReceivable); ok {
			return x.TotalReceivable
		}
	}
	return 0
}

type isOverviewDataItem_Data interface {
	isOverviewDataItem_Data()
}

type OverviewDataItem_Payable struct {
	Payable float64 `protobuf:"fixed64,1,opt,name=payable,proto3,oneof"`
}

type OverviewDataItem_Receivable struct {
	Receivable float64 `protobuf:"fixed64,2,opt,name=receivable,proto3,oneof"`
}

type OverviewDataItem_PendingPayment struct {
	PendingPayment float64 `protobuf:"fixed64,3,opt,name=pending_payment,json=pendingPayment,proto3,oneof"`
}

type OverviewDataItem_TotalPayment struct {
	TotalPayment float64 `protobuf:"fixed64,4,opt,name=total_payment,json=totalPayment,proto3,oneof"`
}

type OverviewDataItem_TotalPayable struct {
	TotalPayable float64 `protobuf:"fixed64,5,opt,name=total_payable,json=totalPayable,proto3,oneof"`
}

type OverviewDataItem_TotalReceivable struct {
	TotalReceivable float64 `protobuf:"fixed64,6,opt,name=total_receivable,json=totalReceivable,proto3,oneof"`
}

func (*OverviewDataItem_Payable) isOverviewDataItem_Data() {}

func (*OverviewDataItem_Receivable) isOverviewDataItem_Data() {}

func (*OverviewDataItem_PendingPayment) isOverviewDataItem_Data() {}

func (*OverviewDataItem_TotalPayment) isOverviewDataItem_Data() {}

func (*OverviewDataItem_TotalPayable) isOverviewDataItem_Data() {}

func (*OverviewDataItem_TotalReceivable) isOverviewDataItem_Data() {}

type OverviewResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*OverviewDataItem    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverviewResponse) Reset() {
	*x = OverviewResponse{}
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverviewResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverviewResponse) ProtoMessage() {}

func (x *OverviewResponse) ProtoReflect() protoreflect.Message {
	mi := &file_invoice_iface_v2_v2_overview_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverviewResponse.ProtoReflect.Descriptor instead.
func (*OverviewResponse) Descriptor() ([]byte, []int) {
	return file_invoice_iface_v2_v2_overview_proto_rawDescGZIP(), []int{4}
}

func (x *OverviewResponse) GetData() []*OverviewDataItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_invoice_iface_v2_v2_overview_proto protoreflect.FileDescriptor

const file_invoice_iface_v2_v2_overview_proto_rawDesc = "" +
	"\n" +
	"\"invoice_iface/v2/v2_overview.proto\x12\x10invoice_iface.v2\x1a\x1bbuf/validate/validate.proto\x1a\x14common/v1/team.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x17role_base/v1/role.proto\"\x84\x01\n" +
	"\x12OverviewTimeFilter\x128\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x05start\x124\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x03end\"{\n" +
	"\x0eOverviewFilter\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x04R\x06teamId\x12\x1e\n" +
	"\vfor_team_id\x18\x03 \x01(\x04R\tforTeamId\x120\n" +
	"\tteam_type\x18\x04 \x01(\x0e2\x13.common.v1.TeamTypeR\bteamType\"\x82\x02\n" +
	"\x0fOverviewRequest\x12K\n" +
	"\n" +
	"time_range\x18\x01 \x01(\v2$.invoice_iface.v2.OverviewTimeFilterB\x06\xbaH\x03\xc8\x01\x01R\ttimeRange\x12@\n" +
	"\x06filter\x18\x02 \x01(\v2 .invoice_iface.v2.OverviewFilterB\x06\xbaH\x03\xc8\x01\x01R\x06filter\x12X\n" +
	"\vmetric_type\x18\x03 \x03(\x0e2$.invoice_iface.v2.OverviewMetricTypeB\x11\xbaH\x0e\x92\x01\v\b\x01\"\a\x82\x01\x04\x10\x01 \x00R\n" +
	"metricType:\x06\x92\xb5\x18\x02 \x01\"\xfe\x01\n" +
	"\x10OverviewDataItem\x12\x1a\n" +
	"\apayable\x18\x01 \x01(\x01H\x00R\apayable\x12 \n" +
	"\n" +
	"receivable\x18\x02 \x01(\x01H\x00R\n" +
	"receivable\x12)\n" +
	"\x0fpending_payment\x18\x03 \x01(\x01H\x00R\x0ependingPayment\x12%\n" +
	"\rtotal_payment\x18\x04 \x01(\x01H\x00R\ftotalPayment\x12%\n" +
	"\rtotal_payable\x18\x05 \x01(\x01H\x00R\ftotalPayable\x12+\n" +
	"\x10total_receivable\x18\x06 \x01(\x01H\x00R\x0ftotalReceivableB\x06\n" +
	"\x04data\"J\n" +
	"\x10OverviewResponse\x126\n" +
	"\x04data\x18\x01 \x03(\v2\".invoice_iface.v2.OverviewDataItemR\x04data*\xa6\x02\n" +
	"\x12OverviewMetricType\x12$\n" +
	" OVERVIEW_METRIC_TYPE_UNSPECIFIED\x10\x00\x12 \n" +
	"\x1cOVERVIEW_METRIC_TYPE_PAYABLE\x10\x01\x12#\n" +
	"\x1fOVERVIEW_METRIC_TYPE_RECEIVABLE\x10\x02\x12(\n" +
	"$OVERVIEW_METRIC_TYPE_PENDING_PAYMENT\x10\x03\x12&\n" +
	"\"OVERVIEW_METRIC_TYPE_TOTAL_PAYMENT\x10\x04\x12&\n" +
	"\"OVERVIEW_METRIC_TYPE_TOTAL_PAYABLE\x10\x05\x12)\n" +
	"%OVERVIEW_METRIC_TYPE_TOTAL_RECEIVABLE\x10\x06B\xc5\x01\n" +
	"\x14com.invoice_iface.v2B\x0fV2OverviewProtoP\x01Z?github.com/pdcgo/schema/services/invoice_iface/v2;invoice_iface\xa2\x02\x03IXX\xaa\x02\x0fInvoiceIface.V2\xca\x02\x0fInvoiceIface\\V2\xe2\x02\x1bInvoiceIface\\V2\\GPBMetadata\xea\x02\x10InvoiceIface::V2b\x06proto3"

var (
	file_invoice_iface_v2_v2_overview_proto_rawDescOnce sync.Once
	file_invoice_iface_v2_v2_overview_proto_rawDescData []byte
)

func file_invoice_iface_v2_v2_overview_proto_rawDescGZIP() []byte {
	file_invoice_iface_v2_v2_overview_proto_rawDescOnce.Do(func() {
		file_invoice_iface_v2_v2_overview_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_invoice_iface_v2_v2_overview_proto_rawDesc), len(file_invoice_iface_v2_v2_overview_proto_rawDesc)))
	})
	return file_invoice_iface_v2_v2_overview_proto_rawDescData
}

var file_invoice_iface_v2_v2_overview_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_invoice_iface_v2_v2_overview_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_invoice_iface_v2_v2_overview_proto_goTypes = []any{
	(OverviewMetricType)(0),       // 0: invoice_iface.v2.OverviewMetricType
	(*OverviewTimeFilter)(nil),    // 1: invoice_iface.v2.OverviewTimeFilter
	(*OverviewFilter)(nil),        // 2: invoice_iface.v2.OverviewFilter
	(*OverviewRequest)(nil),       // 3: invoice_iface.v2.OverviewRequest
	(*OverviewDataItem)(nil),      // 4: invoice_iface.v2.OverviewDataItem
	(*OverviewResponse)(nil),      // 5: invoice_iface.v2.OverviewResponse
	(*timestamppb.Timestamp)(nil), // 6: google.protobuf.Timestamp
	(v1.TeamType)(0),              // 7: common.v1.TeamType
}
var file_invoice_iface_v2_v2_overview_proto_depIdxs = []int32{
	6, // 0: invoice_iface.v2.OverviewTimeFilter.start:type_name -> google.protobuf.Timestamp
	6, // 1: invoice_iface.v2.OverviewTimeFilter.end:type_name -> google.protobuf.Timestamp
	7, // 2: invoice_iface.v2.OverviewFilter.team_type:type_name -> common.v1.TeamType
	1, // 3: invoice_iface.v2.OverviewRequest.time_range:type_name -> invoice_iface.v2.OverviewTimeFilter
	2, // 4: invoice_iface.v2.OverviewRequest.filter:type_name -> invoice_iface.v2.OverviewFilter
	0, // 5: invoice_iface.v2.OverviewRequest.metric_type:type_name -> invoice_iface.v2.OverviewMetricType
	4, // 6: invoice_iface.v2.OverviewResponse.data:type_name -> invoice_iface.v2.OverviewDataItem
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_invoice_iface_v2_v2_overview_proto_init() }
func file_invoice_iface_v2_v2_overview_proto_init() {
	if File_invoice_iface_v2_v2_overview_proto != nil {
		return
	}
	file_invoice_iface_v2_v2_overview_proto_msgTypes[3].OneofWrappers = []any{
		(*OverviewDataItem_Payable)(nil),
		(*OverviewDataItem_Receivable)(nil),
		(*OverviewDataItem_PendingPayment)(nil),
		(*OverviewDataItem_TotalPayment)(nil),
		(*OverviewDataItem_TotalPayable)(nil),
		(*OverviewDataItem_TotalReceivable)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_invoice_iface_v2_v2_overview_proto_rawDesc), len(file_invoice_iface_v2_v2_overview_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_invoice_iface_v2_v2_overview_proto_goTypes,
		DependencyIndexes: file_invoice_iface_v2_v2_overview_proto_depIdxs,
		EnumInfos:         file_invoice_iface_v2_v2_overview_proto_enumTypes,
		MessageInfos:      file_invoice_iface_v2_v2_overview_proto_msgTypes,
	}.Build()
	File_invoice_iface_v2_v2_overview_proto = out.File
	file_invoice_iface_v2_v2_overview_proto_goTypes = nil
	file_invoice_iface_v2_v2_overview_proto_depIdxs = nil
}
