// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: product_iface/v1/product_discovery.proto

package product_ifaceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pdcgo/schema/services/product_iface/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProductDiscoveryServiceName is the fully-qualified name of the ProductDiscoveryService service.
	ProductDiscoveryServiceName = "product_iface.v1.ProductDiscoveryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProductDiscoveryServiceProductDiscoveryProcedure is the fully-qualified name of the
	// ProductDiscoveryService's ProductDiscovery RPC.
	ProductDiscoveryServiceProductDiscoveryProcedure = "/product_iface.v1.ProductDiscoveryService/ProductDiscovery"
	// ProductDiscoveryServiceIndexAddProcedure is the fully-qualified name of the
	// ProductDiscoveryService's IndexAdd RPC.
	ProductDiscoveryServiceIndexAddProcedure = "/product_iface.v1.ProductDiscoveryService/IndexAdd"
)

// ProductDiscoveryServiceClient is a client for the product_iface.v1.ProductDiscoveryService
// service.
type ProductDiscoveryServiceClient interface {
	ProductDiscovery(context.Context, *connect.Request[v1.ProductDiscoveryRequest]) (*connect.Response[v1.ProductDiscoveryResponse], error)
	IndexAdd(context.Context, *connect.Request[v1.IndexAddRequest]) (*connect.Response[v1.IndexAddResponse], error)
}

// NewProductDiscoveryServiceClient constructs a client for the
// product_iface.v1.ProductDiscoveryService service. By default, it uses the Connect protocol with
// the binary Protobuf Codec, asks for gzipped responses, and sends uncompressed requests. To use
// the gRPC or gRPC-Web protocols, supply the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProductDiscoveryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProductDiscoveryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	productDiscoveryServiceMethods := v1.File_product_iface_v1_product_discovery_proto.Services().ByName("ProductDiscoveryService").Methods()
	return &productDiscoveryServiceClient{
		productDiscovery: connect.NewClient[v1.ProductDiscoveryRequest, v1.ProductDiscoveryResponse](
			httpClient,
			baseURL+ProductDiscoveryServiceProductDiscoveryProcedure,
			connect.WithSchema(productDiscoveryServiceMethods.ByName("ProductDiscovery")),
			connect.WithClientOptions(opts...),
		),
		indexAdd: connect.NewClient[v1.IndexAddRequest, v1.IndexAddResponse](
			httpClient,
			baseURL+ProductDiscoveryServiceIndexAddProcedure,
			connect.WithSchema(productDiscoveryServiceMethods.ByName("IndexAdd")),
			connect.WithClientOptions(opts...),
		),
	}
}

// productDiscoveryServiceClient implements ProductDiscoveryServiceClient.
type productDiscoveryServiceClient struct {
	productDiscovery *connect.Client[v1.ProductDiscoveryRequest, v1.ProductDiscoveryResponse]
	indexAdd         *connect.Client[v1.IndexAddRequest, v1.IndexAddResponse]
}

// ProductDiscovery calls product_iface.v1.ProductDiscoveryService.ProductDiscovery.
func (c *productDiscoveryServiceClient) ProductDiscovery(ctx context.Context, req *connect.Request[v1.ProductDiscoveryRequest]) (*connect.Response[v1.ProductDiscoveryResponse], error) {
	return c.productDiscovery.CallUnary(ctx, req)
}

// IndexAdd calls product_iface.v1.ProductDiscoveryService.IndexAdd.
func (c *productDiscoveryServiceClient) IndexAdd(ctx context.Context, req *connect.Request[v1.IndexAddRequest]) (*connect.Response[v1.IndexAddResponse], error) {
	return c.indexAdd.CallUnary(ctx, req)
}

// ProductDiscoveryServiceHandler is an implementation of the
// product_iface.v1.ProductDiscoveryService service.
type ProductDiscoveryServiceHandler interface {
	ProductDiscovery(context.Context, *connect.Request[v1.ProductDiscoveryRequest]) (*connect.Response[v1.ProductDiscoveryResponse], error)
	IndexAdd(context.Context, *connect.Request[v1.IndexAddRequest]) (*connect.Response[v1.IndexAddResponse], error)
}

// NewProductDiscoveryServiceHandler builds an HTTP handler from the service implementation. It
// returns the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProductDiscoveryServiceHandler(svc ProductDiscoveryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	productDiscoveryServiceMethods := v1.File_product_iface_v1_product_discovery_proto.Services().ByName("ProductDiscoveryService").Methods()
	productDiscoveryServiceProductDiscoveryHandler := connect.NewUnaryHandler(
		ProductDiscoveryServiceProductDiscoveryProcedure,
		svc.ProductDiscovery,
		connect.WithSchema(productDiscoveryServiceMethods.ByName("ProductDiscovery")),
		connect.WithHandlerOptions(opts...),
	)
	productDiscoveryServiceIndexAddHandler := connect.NewUnaryHandler(
		ProductDiscoveryServiceIndexAddProcedure,
		svc.IndexAdd,
		connect.WithSchema(productDiscoveryServiceMethods.ByName("IndexAdd")),
		connect.WithHandlerOptions(opts...),
	)
	return "/product_iface.v1.ProductDiscoveryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProductDiscoveryServiceProductDiscoveryProcedure:
			productDiscoveryServiceProductDiscoveryHandler.ServeHTTP(w, r)
		case ProductDiscoveryServiceIndexAddProcedure:
			productDiscoveryServiceIndexAddHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProductDiscoveryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProductDiscoveryServiceHandler struct{}

func (UnimplementedProductDiscoveryServiceHandler) ProductDiscovery(context.Context, *connect.Request[v1.ProductDiscoveryRequest]) (*connect.Response[v1.ProductDiscoveryResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product_iface.v1.ProductDiscoveryService.ProductDiscovery is not implemented"))
}

func (UnimplementedProductDiscoveryServiceHandler) IndexAdd(context.Context, *connect.Request[v1.IndexAddRequest]) (*connect.Response[v1.IndexAddResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product_iface.v1.ProductDiscoveryService.IndexAdd is not implemented"))
}
