// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: product_iface/v1/product.proto

package product_ifaceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pdcgo/schema/services/product_iface/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ProductServiceName is the fully-qualified name of the ProductService service.
	ProductServiceName = "product_iface.v1.ProductService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ProductServiceProductDuplicateProcedure is the fully-qualified name of the ProductService's
	// ProductDuplicate RPC.
	ProductServiceProductDuplicateProcedure = "/product_iface.v1.ProductService/ProductDuplicate"
	// ProductServiceProductMapGetProcedure is the fully-qualified name of the ProductService's
	// ProductMapGet RPC.
	ProductServiceProductMapGetProcedure = "/product_iface.v1.ProductService/ProductMapGet"
	// ProductServiceProductMapConnectProcedure is the fully-qualified name of the ProductService's
	// ProductMapConnect RPC.
	ProductServiceProductMapConnectProcedure = "/product_iface.v1.ProductService/ProductMapConnect"
	// ProductServiceProductByIDsProcedure is the fully-qualified name of the ProductService's
	// ProductByIDs RPC.
	ProductServiceProductByIDsProcedure = "/product_iface.v1.ProductService/ProductByIDs"
)

// ProductServiceClient is a client for the product_iface.v1.ProductService service.
type ProductServiceClient interface {
	ProductDuplicate(context.Context, *connect.Request[v1.ProductDuplicateRequest]) (*connect.Response[v1.ProductDuplicateResponse], error)
	ProductMapGet(context.Context, *connect.Request[v1.ProductMapGetRequest]) (*connect.Response[v1.ProductMapGetResponse], error)
	ProductMapConnect(context.Context, *connect.Request[v1.ProductMapConnectRequest]) (*connect.Response[v1.ProductMapConnectResponse], error)
	// info Product
	ProductByIDs(context.Context, *connect.Request[v1.ProductByIDsRequest]) (*connect.Response[v1.ProductByIDsResponse], error)
}

// NewProductServiceClient constructs a client for the product_iface.v1.ProductService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewProductServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ProductServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	productServiceMethods := v1.File_product_iface_v1_product_proto.Services().ByName("ProductService").Methods()
	return &productServiceClient{
		productDuplicate: connect.NewClient[v1.ProductDuplicateRequest, v1.ProductDuplicateResponse](
			httpClient,
			baseURL+ProductServiceProductDuplicateProcedure,
			connect.WithSchema(productServiceMethods.ByName("ProductDuplicate")),
			connect.WithClientOptions(opts...),
		),
		productMapGet: connect.NewClient[v1.ProductMapGetRequest, v1.ProductMapGetResponse](
			httpClient,
			baseURL+ProductServiceProductMapGetProcedure,
			connect.WithSchema(productServiceMethods.ByName("ProductMapGet")),
			connect.WithClientOptions(opts...),
		),
		productMapConnect: connect.NewClient[v1.ProductMapConnectRequest, v1.ProductMapConnectResponse](
			httpClient,
			baseURL+ProductServiceProductMapConnectProcedure,
			connect.WithSchema(productServiceMethods.ByName("ProductMapConnect")),
			connect.WithClientOptions(opts...),
		),
		productByIDs: connect.NewClient[v1.ProductByIDsRequest, v1.ProductByIDsResponse](
			httpClient,
			baseURL+ProductServiceProductByIDsProcedure,
			connect.WithSchema(productServiceMethods.ByName("ProductByIDs")),
			connect.WithClientOptions(opts...),
		),
	}
}

// productServiceClient implements ProductServiceClient.
type productServiceClient struct {
	productDuplicate  *connect.Client[v1.ProductDuplicateRequest, v1.ProductDuplicateResponse]
	productMapGet     *connect.Client[v1.ProductMapGetRequest, v1.ProductMapGetResponse]
	productMapConnect *connect.Client[v1.ProductMapConnectRequest, v1.ProductMapConnectResponse]
	productByIDs      *connect.Client[v1.ProductByIDsRequest, v1.ProductByIDsResponse]
}

// ProductDuplicate calls product_iface.v1.ProductService.ProductDuplicate.
func (c *productServiceClient) ProductDuplicate(ctx context.Context, req *connect.Request[v1.ProductDuplicateRequest]) (*connect.Response[v1.ProductDuplicateResponse], error) {
	return c.productDuplicate.CallUnary(ctx, req)
}

// ProductMapGet calls product_iface.v1.ProductService.ProductMapGet.
func (c *productServiceClient) ProductMapGet(ctx context.Context, req *connect.Request[v1.ProductMapGetRequest]) (*connect.Response[v1.ProductMapGetResponse], error) {
	return c.productMapGet.CallUnary(ctx, req)
}

// ProductMapConnect calls product_iface.v1.ProductService.ProductMapConnect.
func (c *productServiceClient) ProductMapConnect(ctx context.Context, req *connect.Request[v1.ProductMapConnectRequest]) (*connect.Response[v1.ProductMapConnectResponse], error) {
	return c.productMapConnect.CallUnary(ctx, req)
}

// ProductByIDs calls product_iface.v1.ProductService.ProductByIDs.
func (c *productServiceClient) ProductByIDs(ctx context.Context, req *connect.Request[v1.ProductByIDsRequest]) (*connect.Response[v1.ProductByIDsResponse], error) {
	return c.productByIDs.CallUnary(ctx, req)
}

// ProductServiceHandler is an implementation of the product_iface.v1.ProductService service.
type ProductServiceHandler interface {
	ProductDuplicate(context.Context, *connect.Request[v1.ProductDuplicateRequest]) (*connect.Response[v1.ProductDuplicateResponse], error)
	ProductMapGet(context.Context, *connect.Request[v1.ProductMapGetRequest]) (*connect.Response[v1.ProductMapGetResponse], error)
	ProductMapConnect(context.Context, *connect.Request[v1.ProductMapConnectRequest]) (*connect.Response[v1.ProductMapConnectResponse], error)
	// info Product
	ProductByIDs(context.Context, *connect.Request[v1.ProductByIDsRequest]) (*connect.Response[v1.ProductByIDsResponse], error)
}

// NewProductServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewProductServiceHandler(svc ProductServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	productServiceMethods := v1.File_product_iface_v1_product_proto.Services().ByName("ProductService").Methods()
	productServiceProductDuplicateHandler := connect.NewUnaryHandler(
		ProductServiceProductDuplicateProcedure,
		svc.ProductDuplicate,
		connect.WithSchema(productServiceMethods.ByName("ProductDuplicate")),
		connect.WithHandlerOptions(opts...),
	)
	productServiceProductMapGetHandler := connect.NewUnaryHandler(
		ProductServiceProductMapGetProcedure,
		svc.ProductMapGet,
		connect.WithSchema(productServiceMethods.ByName("ProductMapGet")),
		connect.WithHandlerOptions(opts...),
	)
	productServiceProductMapConnectHandler := connect.NewUnaryHandler(
		ProductServiceProductMapConnectProcedure,
		svc.ProductMapConnect,
		connect.WithSchema(productServiceMethods.ByName("ProductMapConnect")),
		connect.WithHandlerOptions(opts...),
	)
	productServiceProductByIDsHandler := connect.NewUnaryHandler(
		ProductServiceProductByIDsProcedure,
		svc.ProductByIDs,
		connect.WithSchema(productServiceMethods.ByName("ProductByIDs")),
		connect.WithHandlerOptions(opts...),
	)
	return "/product_iface.v1.ProductService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ProductServiceProductDuplicateProcedure:
			productServiceProductDuplicateHandler.ServeHTTP(w, r)
		case ProductServiceProductMapGetProcedure:
			productServiceProductMapGetHandler.ServeHTTP(w, r)
		case ProductServiceProductMapConnectProcedure:
			productServiceProductMapConnectHandler.ServeHTTP(w, r)
		case ProductServiceProductByIDsProcedure:
			productServiceProductByIDsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedProductServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedProductServiceHandler struct{}

func (UnimplementedProductServiceHandler) ProductDuplicate(context.Context, *connect.Request[v1.ProductDuplicateRequest]) (*connect.Response[v1.ProductDuplicateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product_iface.v1.ProductService.ProductDuplicate is not implemented"))
}

func (UnimplementedProductServiceHandler) ProductMapGet(context.Context, *connect.Request[v1.ProductMapGetRequest]) (*connect.Response[v1.ProductMapGetResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product_iface.v1.ProductService.ProductMapGet is not implemented"))
}

func (UnimplementedProductServiceHandler) ProductMapConnect(context.Context, *connect.Request[v1.ProductMapConnectRequest]) (*connect.Response[v1.ProductMapConnectResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product_iface.v1.ProductService.ProductMapConnect is not implemented"))
}

func (UnimplementedProductServiceHandler) ProductByIDs(context.Context, *connect.Request[v1.ProductByIDsRequest]) (*connect.Response[v1.ProductByIDsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("product_iface.v1.ProductService.ProductByIDs is not implemented"))
}
