// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: devel_iface/v1/service.proto

package devel_ifaceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pdcgo/schema/services/devel_iface/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DevelToolServiceName is the fully-qualified name of the DevelToolService service.
	DevelToolServiceName = "devel_iface.v1.DevelToolService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DevelToolServiceSendEventProcedure is the fully-qualified name of the DevelToolService's
	// SendEvent RPC.
	DevelToolServiceSendEventProcedure = "/devel_iface.v1.DevelToolService/SendEvent"
	// DevelToolServiceSubmitTiktokWithdrawalProcedure is the fully-qualified name of the
	// DevelToolService's SubmitTiktokWithdrawal RPC.
	DevelToolServiceSubmitTiktokWithdrawalProcedure = "/devel_iface.v1.DevelToolService/SubmitTiktokWithdrawal"
)

// DevelToolServiceClient is a client for the devel_iface.v1.DevelToolService service.
type DevelToolServiceClient interface {
	SendEvent(context.Context, *connect.Request[v1.SendEventRequest]) (*connect.Response[v1.SendEventResponse], error)
	SubmitTiktokWithdrawal(context.Context, *connect.Request[v1.SubmitTiktokWithdrawalRequest]) (*connect.ServerStreamForClient[v1.SubmitTiktokWithdrawalResponse], error)
}

// NewDevelToolServiceClient constructs a client for the devel_iface.v1.DevelToolService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDevelToolServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DevelToolServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	develToolServiceMethods := v1.File_devel_iface_v1_service_proto.Services().ByName("DevelToolService").Methods()
	return &develToolServiceClient{
		sendEvent: connect.NewClient[v1.SendEventRequest, v1.SendEventResponse](
			httpClient,
			baseURL+DevelToolServiceSendEventProcedure,
			connect.WithSchema(develToolServiceMethods.ByName("SendEvent")),
			connect.WithClientOptions(opts...),
		),
		submitTiktokWithdrawal: connect.NewClient[v1.SubmitTiktokWithdrawalRequest, v1.SubmitTiktokWithdrawalResponse](
			httpClient,
			baseURL+DevelToolServiceSubmitTiktokWithdrawalProcedure,
			connect.WithSchema(develToolServiceMethods.ByName("SubmitTiktokWithdrawal")),
			connect.WithClientOptions(opts...),
		),
	}
}

// develToolServiceClient implements DevelToolServiceClient.
type develToolServiceClient struct {
	sendEvent              *connect.Client[v1.SendEventRequest, v1.SendEventResponse]
	submitTiktokWithdrawal *connect.Client[v1.SubmitTiktokWithdrawalRequest, v1.SubmitTiktokWithdrawalResponse]
}

// SendEvent calls devel_iface.v1.DevelToolService.SendEvent.
func (c *develToolServiceClient) SendEvent(ctx context.Context, req *connect.Request[v1.SendEventRequest]) (*connect.Response[v1.SendEventResponse], error) {
	return c.sendEvent.CallUnary(ctx, req)
}

// SubmitTiktokWithdrawal calls devel_iface.v1.DevelToolService.SubmitTiktokWithdrawal.
func (c *develToolServiceClient) SubmitTiktokWithdrawal(ctx context.Context, req *connect.Request[v1.SubmitTiktokWithdrawalRequest]) (*connect.ServerStreamForClient[v1.SubmitTiktokWithdrawalResponse], error) {
	return c.submitTiktokWithdrawal.CallServerStream(ctx, req)
}

// DevelToolServiceHandler is an implementation of the devel_iface.v1.DevelToolService service.
type DevelToolServiceHandler interface {
	SendEvent(context.Context, *connect.Request[v1.SendEventRequest]) (*connect.Response[v1.SendEventResponse], error)
	SubmitTiktokWithdrawal(context.Context, *connect.Request[v1.SubmitTiktokWithdrawalRequest], *connect.ServerStream[v1.SubmitTiktokWithdrawalResponse]) error
}

// NewDevelToolServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDevelToolServiceHandler(svc DevelToolServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	develToolServiceMethods := v1.File_devel_iface_v1_service_proto.Services().ByName("DevelToolService").Methods()
	develToolServiceSendEventHandler := connect.NewUnaryHandler(
		DevelToolServiceSendEventProcedure,
		svc.SendEvent,
		connect.WithSchema(develToolServiceMethods.ByName("SendEvent")),
		connect.WithHandlerOptions(opts...),
	)
	develToolServiceSubmitTiktokWithdrawalHandler := connect.NewServerStreamHandler(
		DevelToolServiceSubmitTiktokWithdrawalProcedure,
		svc.SubmitTiktokWithdrawal,
		connect.WithSchema(develToolServiceMethods.ByName("SubmitTiktokWithdrawal")),
		connect.WithHandlerOptions(opts...),
	)
	return "/devel_iface.v1.DevelToolService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DevelToolServiceSendEventProcedure:
			develToolServiceSendEventHandler.ServeHTTP(w, r)
		case DevelToolServiceSubmitTiktokWithdrawalProcedure:
			develToolServiceSubmitTiktokWithdrawalHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDevelToolServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDevelToolServiceHandler struct{}

func (UnimplementedDevelToolServiceHandler) SendEvent(context.Context, *connect.Request[v1.SendEventRequest]) (*connect.Response[v1.SendEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("devel_iface.v1.DevelToolService.SendEvent is not implemented"))
}

func (UnimplementedDevelToolServiceHandler) SubmitTiktokWithdrawal(context.Context, *connect.Request[v1.SubmitTiktokWithdrawalRequest], *connect.ServerStream[v1.SubmitTiktokWithdrawalResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("devel_iface.v1.DevelToolService.SubmitTiktokWithdrawal is not implemented"))
}
