// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: accounting_iface/v1/core.proto

package accounting_iface

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CoaCode int32

const (
	CoaCode_COA_CODE_UNSPECIFIED CoaCode = 0
	CoaCode_COA_CODE_ASSET       CoaCode = 10
	CoaCode_COA_CODE_LIABILITY   CoaCode = 20
	CoaCode_COA_CODE_EQUITY      CoaCode = 30
	CoaCode_COA_CODE_REVENUE     CoaCode = 40
	CoaCode_COA_CODE_EXPENSE     CoaCode = 50
)

// Enum value maps for CoaCode.
var (
	CoaCode_name = map[int32]string{
		0:  "COA_CODE_UNSPECIFIED",
		10: "COA_CODE_ASSET",
		20: "COA_CODE_LIABILITY",
		30: "COA_CODE_EQUITY",
		40: "COA_CODE_REVENUE",
		50: "COA_CODE_EXPENSE",
	}
	CoaCode_value = map[string]int32{
		"COA_CODE_UNSPECIFIED": 0,
		"COA_CODE_ASSET":       10,
		"COA_CODE_LIABILITY":   20,
		"COA_CODE_EQUITY":      30,
		"COA_CODE_REVENUE":     40,
		"COA_CODE_EXPENSE":     50,
	}
)

func (x CoaCode) Enum() *CoaCode {
	p := new(CoaCode)
	*p = x
	return p
}

func (x CoaCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CoaCode) Descriptor() protoreflect.EnumDescriptor {
	return file_accounting_iface_v1_core_proto_enumTypes[0].Descriptor()
}

func (CoaCode) Type() protoreflect.EnumType {
	return &file_accounting_iface_v1_core_proto_enumTypes[0]
}

func (x CoaCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CoaCode.Descriptor instead.
func (CoaCode) EnumDescriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{0}
}

type BalanceType int32

const (
	BalanceType_BALANCE_TYPE_UNSPECIFIED BalanceType = 0
	BalanceType_BALANCE_TYPE_DEBIT       BalanceType = 1
	BalanceType_BALANCE_TYPE_CREDIT      BalanceType = 2
)

// Enum value maps for BalanceType.
var (
	BalanceType_name = map[int32]string{
		0: "BALANCE_TYPE_UNSPECIFIED",
		1: "BALANCE_TYPE_DEBIT",
		2: "BALANCE_TYPE_CREDIT",
	}
	BalanceType_value = map[string]int32{
		"BALANCE_TYPE_UNSPECIFIED": 0,
		"BALANCE_TYPE_DEBIT":       1,
		"BALANCE_TYPE_CREDIT":      2,
	}
)

func (x BalanceType) Enum() *BalanceType {
	p := new(BalanceType)
	*p = x
	return p
}

func (x BalanceType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BalanceType) Descriptor() protoreflect.EnumDescriptor {
	return file_accounting_iface_v1_core_proto_enumTypes[1].Descriptor()
}

func (BalanceType) Type() protoreflect.EnumType {
	return &file_accounting_iface_v1_core_proto_enumTypes[1]
}

func (x BalanceType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BalanceType.Descriptor instead.
func (BalanceType) EnumDescriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{1}
}

// untuk labeling
type LabelKey int32

const (
	LabelKey_LABEL_KEY_UNSPECIFIED                LabelKey = 0
	LabelKey_LABEL_KEY_MARKETPLACE                LabelKey = 1
	LabelKey_LABEL_KEY_WAREHOUSE_TRANSACTION_TYPE LabelKey = 2
	LabelKey_LABEL_KEY_REVENUE_SOURCE             LabelKey = 3
	LabelKey_LABEL_KEY_ORDER_TYPE                 LabelKey = 4
)

// Enum value maps for LabelKey.
var (
	LabelKey_name = map[int32]string{
		0: "LABEL_KEY_UNSPECIFIED",
		1: "LABEL_KEY_MARKETPLACE",
		2: "LABEL_KEY_WAREHOUSE_TRANSACTION_TYPE",
		3: "LABEL_KEY_REVENUE_SOURCE",
		4: "LABEL_KEY_ORDER_TYPE",
	}
	LabelKey_value = map[string]int32{
		"LABEL_KEY_UNSPECIFIED":                0,
		"LABEL_KEY_MARKETPLACE":                1,
		"LABEL_KEY_WAREHOUSE_TRANSACTION_TYPE": 2,
		"LABEL_KEY_REVENUE_SOURCE":             3,
		"LABEL_KEY_ORDER_TYPE":                 4,
	}
)

func (x LabelKey) Enum() *LabelKey {
	p := new(LabelKey)
	*p = x
	return p
}

func (x LabelKey) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelKey) Descriptor() protoreflect.EnumDescriptor {
	return file_accounting_iface_v1_core_proto_enumTypes[2].Descriptor()
}

func (LabelKey) Type() protoreflect.EnumType {
	return &file_accounting_iface_v1_core_proto_enumTypes[2]
}

func (x LabelKey) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelKey.Descriptor instead.
func (LabelKey) EnumDescriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{2}
}

type TypeLabelValueListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Key           LabelKey               `protobuf:"varint,2,opt,name=key,proto3,enum=accounting_iface.v1.LabelKey" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeLabelValueListRequest) Reset() {
	*x = TypeLabelValueListRequest{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeLabelValueListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeLabelValueListRequest) ProtoMessage() {}

func (x *TypeLabelValueListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeLabelValueListRequest.ProtoReflect.Descriptor instead.
func (*TypeLabelValueListRequest) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{0}
}

func (x *TypeLabelValueListRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *TypeLabelValueListRequest) GetKey() LabelKey {
	if x != nil {
		return x.Key
	}
	return LabelKey_LABEL_KEY_UNSPECIFIED
}

type TypeLabelValueListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []string               `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeLabelValueListResponse) Reset() {
	*x = TypeLabelValueListResponse{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeLabelValueListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeLabelValueListResponse) ProtoMessage() {}

func (x *TypeLabelValueListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeLabelValueListResponse.ProtoReflect.Descriptor instead.
func (*TypeLabelValueListResponse) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{1}
}

func (x *TypeLabelValueListResponse) GetList() []string {
	if x != nil {
		return x.List
	}
	return nil
}

type TypeLabelListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeLabelListRequest) Reset() {
	*x = TypeLabelListRequest{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeLabelListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeLabelListRequest) ProtoMessage() {}

func (x *TypeLabelListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeLabelListRequest.ProtoReflect.Descriptor instead.
func (*TypeLabelListRequest) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{2}
}

type TypeLabelListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TypeLabel           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeLabelListResponse) Reset() {
	*x = TypeLabelListResponse{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeLabelListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeLabelListResponse) ProtoMessage() {}

func (x *TypeLabelListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeLabelListResponse.ProtoReflect.Descriptor instead.
func (*TypeLabelListResponse) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{3}
}

func (x *TypeLabelListResponse) GetList() []*TypeLabel {
	if x != nil {
		return x.List
	}
	return nil
}

type CoaDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          CoaCode                `protobuf:"varint,1,opt,name=code,proto3,enum=accounting_iface.v1.CoaCode" json:"code,omitempty"`
	TrueAccount   bool                   `protobuf:"varint,2,opt,name=true_account,json=trueAccount,proto3" json:"true_account,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CoaDetail) Reset() {
	*x = CoaDetail{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CoaDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CoaDetail) ProtoMessage() {}

func (x *CoaDetail) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CoaDetail.ProtoReflect.Descriptor instead.
func (*CoaDetail) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{4}
}

func (x *CoaDetail) GetCode() CoaCode {
	if x != nil {
		return x.Code
	}
	return CoaCode_COA_CODE_UNSPECIFIED
}

func (x *CoaDetail) GetTrueAccount() bool {
	if x != nil {
		return x.TrueAccount
	}
	return false
}

// untuk custom filter data account entah spesifik cs, supplier atau custom tag
type AccountFilterExtra struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Cs              bool                   `protobuf:"varint,1,opt,name=cs,proto3" json:"cs,omitempty"`
	Supplier        bool                   `protobuf:"varint,2,opt,name=supplier,proto3" json:"supplier,omitempty"`
	Shop            bool                   `protobuf:"varint,3,opt,name=shop,proto3" json:"shop,omitempty"`
	CustomTag       bool                   `protobuf:"varint,4,opt,name=custom_tag,json=customTag,proto3" json:"custom_tag,omitempty"`
	AllowedLabelKey []LabelKey             `protobuf:"varint,6,rep,packed,name=allowed_label_key,json=allowedLabelKey,proto3,enum=accounting_iface.v1.LabelKey" json:"allowed_label_key,omitempty"`
	Team            bool                   `protobuf:"varint,5,opt,name=team,proto3" json:"team,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AccountFilterExtra) Reset() {
	*x = AccountFilterExtra{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountFilterExtra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountFilterExtra) ProtoMessage() {}

func (x *AccountFilterExtra) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountFilterExtra.ProtoReflect.Descriptor instead.
func (*AccountFilterExtra) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{5}
}

func (x *AccountFilterExtra) GetCs() bool {
	if x != nil {
		return x.Cs
	}
	return false
}

func (x *AccountFilterExtra) GetSupplier() bool {
	if x != nil {
		return x.Supplier
	}
	return false
}

func (x *AccountFilterExtra) GetShop() bool {
	if x != nil {
		return x.Shop
	}
	return false
}

func (x *AccountFilterExtra) GetCustomTag() bool {
	if x != nil {
		return x.CustomTag
	}
	return false
}

func (x *AccountFilterExtra) GetAllowedLabelKey() []LabelKey {
	if x != nil {
		return x.AllowedLabelKey
	}
	return nil
}

func (x *AccountFilterExtra) GetTeam() bool {
	if x != nil {
		return x.Team
	}
	return false
}

type AccountKeyItem struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Key         string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Coa         CoaCode                `protobuf:"varint,2,opt,name=coa,proto3,enum=accounting_iface.v1.CoaCode" json:"coa,omitempty"`
	BalanceType BalanceType            `protobuf:"varint,3,opt,name=balance_type,json=balanceType,proto3,enum=accounting_iface.v1.BalanceType" json:"balance_type,omitempty"`
	// @gotags: gorm:"-"
	FilterExtra *AccountFilterExtra `protobuf:"bytes,4,opt,name=filter_extra,json=filterExtra,proto3" json:"filter_extra,omitempty" gorm:"-"`
	// @gotags: gorm:"-"
	CoaDetail     *CoaDetail `protobuf:"bytes,5,opt,name=coa_detail,json=coaDetail,proto3" json:"coa_detail,omitempty" gorm:"-"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountKeyItem) Reset() {
	*x = AccountKeyItem{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountKeyItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountKeyItem) ProtoMessage() {}

func (x *AccountKeyItem) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountKeyItem.ProtoReflect.Descriptor instead.
func (*AccountKeyItem) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{6}
}

func (x *AccountKeyItem) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *AccountKeyItem) GetCoa() CoaCode {
	if x != nil {
		return x.Coa
	}
	return CoaCode_COA_CODE_UNSPECIFIED
}

func (x *AccountKeyItem) GetBalanceType() BalanceType {
	if x != nil {
		return x.BalanceType
	}
	return BalanceType_BALANCE_TYPE_UNSPECIFIED
}

func (x *AccountKeyItem) GetFilterExtra() *AccountFilterExtra {
	if x != nil {
		return x.FilterExtra
	}
	return nil
}

func (x *AccountKeyItem) GetCoaDetail() *CoaDetail {
	if x != nil {
		return x.CoaDetail
	}
	return nil
}

type AccountKeyListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	TeamId        uint64                 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountKeyListRequest) Reset() {
	*x = AccountKeyListRequest{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountKeyListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountKeyListRequest) ProtoMessage() {}

func (x *AccountKeyListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountKeyListRequest.ProtoReflect.Descriptor instead.
func (*AccountKeyListRequest) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{7}
}

func (x *AccountKeyListRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *AccountKeyListRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

type AccountKeyListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*AccountKeyItem      `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountKeyListResponse) Reset() {
	*x = AccountKeyListResponse{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountKeyListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountKeyListResponse) ProtoMessage() {}

func (x *AccountKeyListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountKeyListResponse.ProtoReflect.Descriptor instead.
func (*AccountKeyListResponse) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{8}
}

func (x *AccountKeyListResponse) GetKeys() []*AccountKeyItem {
	if x != nil {
		return x.Keys
	}
	return nil
}

type TypeLabel struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// @gotags: gorm:"index:keyval,unique"
	Key LabelKey `protobuf:"varint,1,opt,name=key,proto3,enum=accounting_iface.v1.LabelKey" json:"key,omitempty" gorm:"index:keyval,unique"`
	// @gotags: gorm:"index:keyval,unique"
	Label         string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty" gorm:"index:keyval,unique"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeLabel) Reset() {
	*x = TypeLabel{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeLabel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeLabel) ProtoMessage() {}

func (x *TypeLabel) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeLabel.ProtoReflect.Descriptor instead.
func (*TypeLabel) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{9}
}

func (x *TypeLabel) GetKey() LabelKey {
	if x != nil {
		return x.Key
	}
	return LabelKey_LABEL_KEY_UNSPECIFIED
}

func (x *TypeLabel) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

type TypeLabelList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*TypeLabel           `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TypeLabelList) Reset() {
	*x = TypeLabelList{}
	mi := &file_accounting_iface_v1_core_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TypeLabelList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TypeLabelList) ProtoMessage() {}

func (x *TypeLabelList) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_core_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TypeLabelList.ProtoReflect.Descriptor instead.
func (*TypeLabelList) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_core_proto_rawDescGZIP(), []int{10}
}

func (x *TypeLabelList) GetList() []*TypeLabel {
	if x != nil {
		return x.List
	}
	return nil
}

var File_accounting_iface_v1_core_proto protoreflect.FileDescriptor

const file_accounting_iface_v1_core_proto_rawDesc = "" +
	"\n" +
	"\x1eaccounting_iface/v1/core.proto\x12\x13accounting_iface.v1\x1a\x1bbuf/validate/validate.proto\"Z\n" +
	"\x19TypeLabelValueListRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12/\n" +
	"\x03key\x18\x02 \x01(\x0e2\x1d.accounting_iface.v1.LabelKeyR\x03key\"0\n" +
	"\x1aTypeLabelValueListResponse\x12\x12\n" +
	"\x04list\x18\x01 \x03(\tR\x04list\"\x16\n" +
	"\x14TypeLabelListRequest\"K\n" +
	"\x15TypeLabelListResponse\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.accounting_iface.v1.TypeLabelR\x04list\"`\n" +
	"\tCoaDetail\x120\n" +
	"\x04code\x18\x01 \x01(\x0e2\x1c.accounting_iface.v1.CoaCodeR\x04code\x12!\n" +
	"\ftrue_account\x18\x02 \x01(\bR\vtrueAccount\"\xd2\x01\n" +
	"\x12AccountFilterExtra\x12\x0e\n" +
	"\x02cs\x18\x01 \x01(\bR\x02cs\x12\x1a\n" +
	"\bsupplier\x18\x02 \x01(\bR\bsupplier\x12\x12\n" +
	"\x04shop\x18\x03 \x01(\bR\x04shop\x12\x1d\n" +
	"\n" +
	"custom_tag\x18\x04 \x01(\bR\tcustomTag\x12I\n" +
	"\x11allowed_label_key\x18\x06 \x03(\x0e2\x1d.accounting_iface.v1.LabelKeyR\x0fallowedLabelKey\x12\x12\n" +
	"\x04team\x18\x05 \x01(\bR\x04team\"\xa2\x02\n" +
	"\x0eAccountKeyItem\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12.\n" +
	"\x03coa\x18\x02 \x01(\x0e2\x1c.accounting_iface.v1.CoaCodeR\x03coa\x12C\n" +
	"\fbalance_type\x18\x03 \x01(\x0e2 .accounting_iface.v1.BalanceTypeR\vbalanceType\x12J\n" +
	"\ffilter_extra\x18\x04 \x01(\v2'.accounting_iface.v1.AccountFilterExtraR\vfilterExtra\x12=\n" +
	"\n" +
	"coa_detail\x18\x05 \x01(\v2\x1e.accounting_iface.v1.CoaDetailR\tcoaDetail\"G\n" +
	"\x15AccountKeyListRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12 \n" +
	"\ateam_id\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x06teamId\"Q\n" +
	"\x16AccountKeyListResponse\x127\n" +
	"\x04keys\x18\x01 \x03(\v2#.accounting_iface.v1.AccountKeyItemR\x04keys\"R\n" +
	"\tTypeLabel\x12/\n" +
	"\x03key\x18\x01 \x01(\x0e2\x1d.accounting_iface.v1.LabelKeyR\x03key\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\"C\n" +
	"\rTypeLabelList\x122\n" +
	"\x04list\x18\x01 \x03(\v2\x1e.accounting_iface.v1.TypeLabelR\x04list*\x90\x01\n" +
	"\aCoaCode\x12\x18\n" +
	"\x14COA_CODE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eCOA_CODE_ASSET\x10\n" +
	"\x12\x16\n" +
	"\x12COA_CODE_LIABILITY\x10\x14\x12\x13\n" +
	"\x0fCOA_CODE_EQUITY\x10\x1e\x12\x14\n" +
	"\x10COA_CODE_REVENUE\x10(\x12\x14\n" +
	"\x10COA_CODE_EXPENSE\x102*\\\n" +
	"\vBalanceType\x12\x1c\n" +
	"\x18BALANCE_TYPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12BALANCE_TYPE_DEBIT\x10\x01\x12\x17\n" +
	"\x13BALANCE_TYPE_CREDIT\x10\x02*\xa2\x01\n" +
	"\bLabelKey\x12\x19\n" +
	"\x15LABEL_KEY_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15LABEL_KEY_MARKETPLACE\x10\x01\x12(\n" +
	"$LABEL_KEY_WAREHOUSE_TRANSACTION_TYPE\x10\x02\x12\x1c\n" +
	"\x18LABEL_KEY_REVENUE_SOURCE\x10\x03\x12\x18\n" +
	"\x14LABEL_KEY_ORDER_TYPE\x10\x042\xe0\x01\n" +
	"\vCoreService\x12i\n" +
	"\x0eAccountKeyList\x12*.accounting_iface.v1.AccountKeyListRequest\x1a+.accounting_iface.v1.AccountKeyListResponse\x12f\n" +
	"\rTypeLabelList\x12).accounting_iface.v1.TypeLabelListRequest\x1a*.accounting_iface.v1.TypeLabelListResponseB\xd4\x01\n" +
	"\x17com.accounting_iface.v1B\tCoreProtoP\x01ZEgithub.com/pdcgo/schema/services/accounting_iface/v1;accounting_iface\xa2\x02\x03AXX\xaa\x02\x12AccountingIface.V1\xca\x02\x12AccountingIface\\V1\xe2\x02\x1eAccountingIface\\V1\\GPBMetadata\xea\x02\x13AccountingIface::V1b\x06proto3"

var (
	file_accounting_iface_v1_core_proto_rawDescOnce sync.Once
	file_accounting_iface_v1_core_proto_rawDescData []byte
)

func file_accounting_iface_v1_core_proto_rawDescGZIP() []byte {
	file_accounting_iface_v1_core_proto_rawDescOnce.Do(func() {
		file_accounting_iface_v1_core_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounting_iface_v1_core_proto_rawDesc), len(file_accounting_iface_v1_core_proto_rawDesc)))
	})
	return file_accounting_iface_v1_core_proto_rawDescData
}

var file_accounting_iface_v1_core_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_accounting_iface_v1_core_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_accounting_iface_v1_core_proto_goTypes = []any{
	(CoaCode)(0),                       // 0: accounting_iface.v1.CoaCode
	(BalanceType)(0),                   // 1: accounting_iface.v1.BalanceType
	(LabelKey)(0),                      // 2: accounting_iface.v1.LabelKey
	(*TypeLabelValueListRequest)(nil),  // 3: accounting_iface.v1.TypeLabelValueListRequest
	(*TypeLabelValueListResponse)(nil), // 4: accounting_iface.v1.TypeLabelValueListResponse
	(*TypeLabelListRequest)(nil),       // 5: accounting_iface.v1.TypeLabelListRequest
	(*TypeLabelListResponse)(nil),      // 6: accounting_iface.v1.TypeLabelListResponse
	(*CoaDetail)(nil),                  // 7: accounting_iface.v1.CoaDetail
	(*AccountFilterExtra)(nil),         // 8: accounting_iface.v1.AccountFilterExtra
	(*AccountKeyItem)(nil),             // 9: accounting_iface.v1.AccountKeyItem
	(*AccountKeyListRequest)(nil),      // 10: accounting_iface.v1.AccountKeyListRequest
	(*AccountKeyListResponse)(nil),     // 11: accounting_iface.v1.AccountKeyListResponse
	(*TypeLabel)(nil),                  // 12: accounting_iface.v1.TypeLabel
	(*TypeLabelList)(nil),              // 13: accounting_iface.v1.TypeLabelList
}
var file_accounting_iface_v1_core_proto_depIdxs = []int32{
	2,  // 0: accounting_iface.v1.TypeLabelValueListRequest.key:type_name -> accounting_iface.v1.LabelKey
	12, // 1: accounting_iface.v1.TypeLabelListResponse.list:type_name -> accounting_iface.v1.TypeLabel
	0,  // 2: accounting_iface.v1.CoaDetail.code:type_name -> accounting_iface.v1.CoaCode
	2,  // 3: accounting_iface.v1.AccountFilterExtra.allowed_label_key:type_name -> accounting_iface.v1.LabelKey
	0,  // 4: accounting_iface.v1.AccountKeyItem.coa:type_name -> accounting_iface.v1.CoaCode
	1,  // 5: accounting_iface.v1.AccountKeyItem.balance_type:type_name -> accounting_iface.v1.BalanceType
	8,  // 6: accounting_iface.v1.AccountKeyItem.filter_extra:type_name -> accounting_iface.v1.AccountFilterExtra
	7,  // 7: accounting_iface.v1.AccountKeyItem.coa_detail:type_name -> accounting_iface.v1.CoaDetail
	9,  // 8: accounting_iface.v1.AccountKeyListResponse.keys:type_name -> accounting_iface.v1.AccountKeyItem
	2,  // 9: accounting_iface.v1.TypeLabel.key:type_name -> accounting_iface.v1.LabelKey
	12, // 10: accounting_iface.v1.TypeLabelList.list:type_name -> accounting_iface.v1.TypeLabel
	10, // 11: accounting_iface.v1.CoreService.AccountKeyList:input_type -> accounting_iface.v1.AccountKeyListRequest
	5,  // 12: accounting_iface.v1.CoreService.TypeLabelList:input_type -> accounting_iface.v1.TypeLabelListRequest
	11, // 13: accounting_iface.v1.CoreService.AccountKeyList:output_type -> accounting_iface.v1.AccountKeyListResponse
	6,  // 14: accounting_iface.v1.CoreService.TypeLabelList:output_type -> accounting_iface.v1.TypeLabelListResponse
	13, // [13:15] is the sub-list for method output_type
	11, // [11:13] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_accounting_iface_v1_core_proto_init() }
func file_accounting_iface_v1_core_proto_init() {
	if File_accounting_iface_v1_core_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounting_iface_v1_core_proto_rawDesc), len(file_accounting_iface_v1_core_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounting_iface_v1_core_proto_goTypes,
		DependencyIndexes: file_accounting_iface_v1_core_proto_depIdxs,
		EnumInfos:         file_accounting_iface_v1_core_proto_enumTypes,
		MessageInfos:      file_accounting_iface_v1_core_proto_msgTypes,
	}.Build()
	File_accounting_iface_v1_core_proto = out.File
	file_accounting_iface_v1_core_proto_goTypes = nil
	file_accounting_iface_v1_core_proto_depIdxs = nil
}
