// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: accounting_iface/v1/tag.proto

package accounting_iface

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TagCreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagCreateRequest) Reset() {
	*x = TagCreateRequest{}
	mi := &file_accounting_iface_v1_tag_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCreateRequest) ProtoMessage() {}

func (x *TagCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_tag_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCreateRequest.ProtoReflect.Descriptor instead.
func (*TagCreateRequest) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_tag_proto_rawDescGZIP(), []int{0}
}

func (x *TagCreateRequest) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type TagCreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagCreateResponse) Reset() {
	*x = TagCreateResponse{}
	mi := &file_accounting_iface_v1_tag_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagCreateResponse) ProtoMessage() {}

func (x *TagCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_tag_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagCreateResponse.ProtoReflect.Descriptor instead.
func (*TagCreateResponse) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_tag_proto_rawDescGZIP(), []int{1}
}

type TagListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Q             string                 `protobuf:"bytes,1,opt,name=q,proto3" json:"q,omitempty"`
	Limit         uint64                 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        uint64                 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListRequest) Reset() {
	*x = TagListRequest{}
	mi := &file_accounting_iface_v1_tag_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListRequest) ProtoMessage() {}

func (x *TagListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_tag_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListRequest.ProtoReflect.Descriptor instead.
func (*TagListRequest) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_tag_proto_rawDescGZIP(), []int{2}
}

func (x *TagListRequest) GetQ() string {
	if x != nil {
		return x.Q
	}
	return ""
}

func (x *TagListRequest) GetLimit() uint64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *TagListRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type TagListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tags          []string               `protobuf:"bytes,1,rep,name=tags,proto3" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TagListResponse) Reset() {
	*x = TagListResponse{}
	mi := &file_accounting_iface_v1_tag_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TagListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TagListResponse) ProtoMessage() {}

func (x *TagListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_accounting_iface_v1_tag_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TagListResponse.ProtoReflect.Descriptor instead.
func (*TagListResponse) Descriptor() ([]byte, []int) {
	return file_accounting_iface_v1_tag_proto_rawDescGZIP(), []int{3}
}

func (x *TagListResponse) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

var File_accounting_iface_v1_tag_proto protoreflect.FileDescriptor

const file_accounting_iface_v1_tag_proto_rawDesc = "" +
	"\n" +
	"\x1daccounting_iface/v1/tag.proto\x12\x13accounting_iface.v1\x1a\x1bbuf/validate/validate.proto\"9\n" +
	"\x10TagCreateRequest\x12%\n" +
	"\x04tags\x18\x01 \x03(\tB\x11\xbaH\x0e\x92\x01\v\b\x01\x10\x14\"\x05r\x03\x18\xc8\x01R\x04tags\"\x13\n" +
	"\x11TagCreateResponse\"a\n" +
	"\x0eTagListRequest\x12\f\n" +
	"\x01q\x18\x01 \x01(\tR\x01q\x12 \n" +
	"\x05limit\x18\x02 \x01(\x04B\n" +
	"\xbaH\a2\x05\x10\xac\x02(\n" +
	"R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x03 \x01(\x04B\a\xbaH\x042\x02(\x00R\x06offset\"%\n" +
	"\x0fTagListResponse\x12\x12\n" +
	"\x04tags\x18\x01 \x03(\tR\x04tags2\xbe\x01\n" +
	"\n" +
	"TagService\x12Z\n" +
	"\tTagCreate\x12%.accounting_iface.v1.TagCreateRequest\x1a&.accounting_iface.v1.TagCreateResponse\x12T\n" +
	"\aTagList\x12#.accounting_iface.v1.TagListRequest\x1a$.accounting_iface.v1.TagListResponseB\xd3\x01\n" +
	"\x17com.accounting_iface.v1B\bTagProtoP\x01ZEgithub.com/pdcgo/schema/services/accounting_iface/v1;accounting_iface\xa2\x02\x03AXX\xaa\x02\x12AccountingIface.V1\xca\x02\x12AccountingIface\\V1\xe2\x02\x1eAccountingIface\\V1\\GPBMetadata\xea\x02\x13AccountingIface::V1b\x06proto3"

var (
	file_accounting_iface_v1_tag_proto_rawDescOnce sync.Once
	file_accounting_iface_v1_tag_proto_rawDescData []byte
)

func file_accounting_iface_v1_tag_proto_rawDescGZIP() []byte {
	file_accounting_iface_v1_tag_proto_rawDescOnce.Do(func() {
		file_accounting_iface_v1_tag_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_accounting_iface_v1_tag_proto_rawDesc), len(file_accounting_iface_v1_tag_proto_rawDesc)))
	})
	return file_accounting_iface_v1_tag_proto_rawDescData
}

var file_accounting_iface_v1_tag_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_accounting_iface_v1_tag_proto_goTypes = []any{
	(*TagCreateRequest)(nil),  // 0: accounting_iface.v1.TagCreateRequest
	(*TagCreateResponse)(nil), // 1: accounting_iface.v1.TagCreateResponse
	(*TagListRequest)(nil),    // 2: accounting_iface.v1.TagListRequest
	(*TagListResponse)(nil),   // 3: accounting_iface.v1.TagListResponse
}
var file_accounting_iface_v1_tag_proto_depIdxs = []int32{
	0, // 0: accounting_iface.v1.TagService.TagCreate:input_type -> accounting_iface.v1.TagCreateRequest
	2, // 1: accounting_iface.v1.TagService.TagList:input_type -> accounting_iface.v1.TagListRequest
	1, // 2: accounting_iface.v1.TagService.TagCreate:output_type -> accounting_iface.v1.TagCreateResponse
	3, // 3: accounting_iface.v1.TagService.TagList:output_type -> accounting_iface.v1.TagListResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_accounting_iface_v1_tag_proto_init() }
func file_accounting_iface_v1_tag_proto_init() {
	if File_accounting_iface_v1_tag_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_accounting_iface_v1_tag_proto_rawDesc), len(file_accounting_iface_v1_tag_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_accounting_iface_v1_tag_proto_goTypes,
		DependencyIndexes: file_accounting_iface_v1_tag_proto_depIdxs,
		MessageInfos:      file_accounting_iface_v1_tag_proto_msgTypes,
	}.Build()
	File_accounting_iface_v1_tag_proto = out.File
	file_accounting_iface_v1_tag_proto_goTypes = nil
	file_accounting_iface_v1_tag_proto_depIdxs = nil
}
