// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: inventory_iface/v1/service.proto

package inventory_ifaceconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1 "github.com/pdcgo/schema/services/inventory_iface/v1"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InventoryServiceName is the fully-qualified name of the InventoryService service.
	InventoryServiceName = "inventory_iface.v1.InventoryService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InventoryServiceOrderProcedure is the fully-qualified name of the InventoryService's Order RPC.
	InventoryServiceOrderProcedure = "/inventory_iface.v1.InventoryService/Order"
	// InventoryServiceStockMovementProcedure is the fully-qualified name of the InventoryService's
	// StockMovement RPC.
	InventoryServiceStockMovementProcedure = "/inventory_iface.v1.InventoryService/StockMovement"
	// InventoryServicePushStockEventProcedure is the fully-qualified name of the InventoryService's
	// PushStockEvent RPC.
	InventoryServicePushStockEventProcedure = "/inventory_iface.v1.InventoryService/PushStockEvent"
	// InventoryServiceTransactionCreateProcedure is the fully-qualified name of the InventoryService's
	// TransactionCreate RPC.
	InventoryServiceTransactionCreateProcedure = "/inventory_iface.v1.InventoryService/TransactionCreate"
	// InventoryServiceTransactionCancelProcedure is the fully-qualified name of the InventoryService's
	// TransactionCancel RPC.
	InventoryServiceTransactionCancelProcedure = "/inventory_iface.v1.InventoryService/TransactionCancel"
	// InventoryServiceProductPlacementListProcedure is the fully-qualified name of the
	// InventoryService's ProductPlacementList RPC.
	InventoryServiceProductPlacementListProcedure = "/inventory_iface.v1.InventoryService/ProductPlacementList"
	// InventoryServiceProductPlacementLogProcedure is the fully-qualified name of the
	// InventoryService's ProductPlacementLog RPC.
	InventoryServiceProductPlacementLogProcedure = "/inventory_iface.v1.InventoryService/ProductPlacementLog"
	// InventoryServiceProductBatchListProcedure is the fully-qualified name of the InventoryService's
	// ProductBatchList RPC.
	InventoryServiceProductBatchListProcedure = "/inventory_iface.v1.InventoryService/ProductBatchList"
	// InventoryServiceProductReconcileProcedure is the fully-qualified name of the InventoryService's
	// ProductReconcile RPC.
	InventoryServiceProductReconcileProcedure = "/inventory_iface.v1.InventoryService/ProductReconcile"
	// InventoryServiceRackCreateProcedure is the fully-qualified name of the InventoryService's
	// RackCreate RPC.
	InventoryServiceRackCreateProcedure = "/inventory_iface.v1.InventoryService/RackCreate"
	// InventoryServiceRackUpdateProcedure is the fully-qualified name of the InventoryService's
	// RackUpdate RPC.
	InventoryServiceRackUpdateProcedure = "/inventory_iface.v1.InventoryService/RackUpdate"
	// InventoryServiceRackDeleteProcedure is the fully-qualified name of the InventoryService's
	// RackDelete RPC.
	InventoryServiceRackDeleteProcedure = "/inventory_iface.v1.InventoryService/RackDelete"
	// InventoryServiceRackDetailProcedure is the fully-qualified name of the InventoryService's
	// RackDetail RPC.
	InventoryServiceRackDetailProcedure = "/inventory_iface.v1.InventoryService/RackDetail"
	// InventoryServiceRackListProcedure is the fully-qualified name of the InventoryService's RackList
	// RPC.
	InventoryServiceRackListProcedure = "/inventory_iface.v1.InventoryService/RackList"
	// InventoryServiceProductConfigProcedure is the fully-qualified name of the InventoryService's
	// ProductConfig RPC.
	InventoryServiceProductConfigProcedure = "/inventory_iface.v1.InventoryService/ProductConfig"
	// InventoryServiceProductConfigUpdateProcedure is the fully-qualified name of the
	// InventoryService's ProductConfigUpdate RPC.
	InventoryServiceProductConfigUpdateProcedure = "/inventory_iface.v1.InventoryService/ProductConfigUpdate"
	// InventoryServiceProductListProcedure is the fully-qualified name of the InventoryService's
	// ProductList RPC.
	InventoryServiceProductListProcedure = "/inventory_iface.v1.InventoryService/ProductList"
	// InventoryServiceProductDetailProcedure is the fully-qualified name of the InventoryService's
	// ProductDetail RPC.
	InventoryServiceProductDetailProcedure = "/inventory_iface.v1.InventoryService/ProductDetail"
)

// InventoryServiceClient is a client for the inventory_iface.v1.InventoryService service.
type InventoryServiceClient interface {
	Order(context.Context, *connect.Request[v1.OrderRequest]) (*connect.Response[v1.OrderResponse], error)
	StockMovement(context.Context, *connect.Request[v1.StockMovementRequest]) (*connect.Response[v1.StockMovementResponse], error)
	// PushStockEvent ingests a warehouse StockEvent (the RPC counterpart of the
	// Pub/Sub push handler) and applies it to inventory state in one transaction.
	PushStockEvent(context.Context, *connect.Request[v1.PushStockEventRequest]) (*connect.Response[v1.PushStockEventResponse], error)
	// Transaction management: a request-driven, inventory-owned stock mutation
	// (order/restock/return/found_back/problem). TransactionCancel reverses one.
	TransactionCreate(context.Context, *connect.Request[v1.TransactionCreateRequest]) (*connect.Response[v1.TransactionCreateResponse], error)
	TransactionCancel(context.Context, *connect.Request[v1.TransactionCancelRequest]) (*connect.Response[v1.TransactionCancelResponse], error)
	ProductPlacementList(context.Context, *connect.Request[v1.ProductPlacementListRequest]) (*connect.Response[v1.ProductPlacementListResponse], error)
	ProductPlacementLog(context.Context, *connect.Request[v1.ProductPlacementLogRequest]) (*connect.Response[v1.ProductPlacementLogResponse], error)
	ProductBatchList(context.Context, *connect.Request[v1.ProductBatchListRequest]) (*connect.Response[v1.ProductBatchListResponse], error)
	// untuk rekonsiliasi legacy
	ProductReconcile(context.Context, *connect.Request[v1.ProductReconcileRequest]) (*connect.ServerStreamForClient[v1.ProductReconcileResponse], error)
	// Rack management. All except RackList are scoped by warehouse_id.
	RackCreate(context.Context, *connect.Request[v1.RackCreateRequest]) (*connect.Response[v1.RackCreateResponse], error)
	RackUpdate(context.Context, *connect.Request[v1.RackUpdateRequest]) (*connect.Response[v1.RackUpdateResponse], error)
	RackDelete(context.Context, *connect.Request[v1.RackDeleteRequest]) (*connect.Response[v1.RackDeleteResponse], error)
	RackDetail(context.Context, *connect.Request[v1.RackDetailRequest]) (*connect.Response[v1.RackDetailResponse], error)
	RackList(context.Context, *connect.Request[v1.RackListRequest]) (*connect.Response[v1.RackListResponse], error)
	// Product management (config + views), scoped by warehouse_id.
	ProductConfig(context.Context, *connect.Request[v1.ProductConfigRequest]) (*connect.Response[v1.ProductConfigResponse], error)
	ProductConfigUpdate(context.Context, *connect.Request[v1.ProductConfigUpdateRequest]) (*connect.Response[v1.ProductConfigUpdateResponse], error)
	ProductList(context.Context, *connect.Request[v1.ProductListRequest]) (*connect.Response[v1.ProductListResponse], error)
	ProductDetail(context.Context, *connect.Request[v1.ProductDetailRequest]) (*connect.Response[v1.ProductDetailResponse], error)
}

// NewInventoryServiceClient constructs a client for the inventory_iface.v1.InventoryService
// service. By default, it uses the Connect protocol with the binary Protobuf Codec, asks for
// gzipped responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply
// the connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInventoryServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InventoryServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	inventoryServiceMethods := v1.File_inventory_iface_v1_service_proto.Services().ByName("InventoryService").Methods()
	return &inventoryServiceClient{
		order: connect.NewClient[v1.OrderRequest, v1.OrderResponse](
			httpClient,
			baseURL+InventoryServiceOrderProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("Order")),
			connect.WithClientOptions(opts...),
		),
		stockMovement: connect.NewClient[v1.StockMovementRequest, v1.StockMovementResponse](
			httpClient,
			baseURL+InventoryServiceStockMovementProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("StockMovement")),
			connect.WithClientOptions(opts...),
		),
		pushStockEvent: connect.NewClient[v1.PushStockEventRequest, v1.PushStockEventResponse](
			httpClient,
			baseURL+InventoryServicePushStockEventProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("PushStockEvent")),
			connect.WithClientOptions(opts...),
		),
		transactionCreate: connect.NewClient[v1.TransactionCreateRequest, v1.TransactionCreateResponse](
			httpClient,
			baseURL+InventoryServiceTransactionCreateProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("TransactionCreate")),
			connect.WithClientOptions(opts...),
		),
		transactionCancel: connect.NewClient[v1.TransactionCancelRequest, v1.TransactionCancelResponse](
			httpClient,
			baseURL+InventoryServiceTransactionCancelProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("TransactionCancel")),
			connect.WithClientOptions(opts...),
		),
		productPlacementList: connect.NewClient[v1.ProductPlacementListRequest, v1.ProductPlacementListResponse](
			httpClient,
			baseURL+InventoryServiceProductPlacementListProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ProductPlacementList")),
			connect.WithClientOptions(opts...),
		),
		productPlacementLog: connect.NewClient[v1.ProductPlacementLogRequest, v1.ProductPlacementLogResponse](
			httpClient,
			baseURL+InventoryServiceProductPlacementLogProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ProductPlacementLog")),
			connect.WithClientOptions(opts...),
		),
		productBatchList: connect.NewClient[v1.ProductBatchListRequest, v1.ProductBatchListResponse](
			httpClient,
			baseURL+InventoryServiceProductBatchListProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ProductBatchList")),
			connect.WithClientOptions(opts...),
		),
		productReconcile: connect.NewClient[v1.ProductReconcileRequest, v1.ProductReconcileResponse](
			httpClient,
			baseURL+InventoryServiceProductReconcileProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ProductReconcile")),
			connect.WithClientOptions(opts...),
		),
		rackCreate: connect.NewClient[v1.RackCreateRequest, v1.RackCreateResponse](
			httpClient,
			baseURL+InventoryServiceRackCreateProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("RackCreate")),
			connect.WithClientOptions(opts...),
		),
		rackUpdate: connect.NewClient[v1.RackUpdateRequest, v1.RackUpdateResponse](
			httpClient,
			baseURL+InventoryServiceRackUpdateProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("RackUpdate")),
			connect.WithClientOptions(opts...),
		),
		rackDelete: connect.NewClient[v1.RackDeleteRequest, v1.RackDeleteResponse](
			httpClient,
			baseURL+InventoryServiceRackDeleteProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("RackDelete")),
			connect.WithClientOptions(opts...),
		),
		rackDetail: connect.NewClient[v1.RackDetailRequest, v1.RackDetailResponse](
			httpClient,
			baseURL+InventoryServiceRackDetailProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("RackDetail")),
			connect.WithClientOptions(opts...),
		),
		rackList: connect.NewClient[v1.RackListRequest, v1.RackListResponse](
			httpClient,
			baseURL+InventoryServiceRackListProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("RackList")),
			connect.WithClientOptions(opts...),
		),
		productConfig: connect.NewClient[v1.ProductConfigRequest, v1.ProductConfigResponse](
			httpClient,
			baseURL+InventoryServiceProductConfigProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ProductConfig")),
			connect.WithClientOptions(opts...),
		),
		productConfigUpdate: connect.NewClient[v1.ProductConfigUpdateRequest, v1.ProductConfigUpdateResponse](
			httpClient,
			baseURL+InventoryServiceProductConfigUpdateProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ProductConfigUpdate")),
			connect.WithClientOptions(opts...),
		),
		productList: connect.NewClient[v1.ProductListRequest, v1.ProductListResponse](
			httpClient,
			baseURL+InventoryServiceProductListProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ProductList")),
			connect.WithClientOptions(opts...),
		),
		productDetail: connect.NewClient[v1.ProductDetailRequest, v1.ProductDetailResponse](
			httpClient,
			baseURL+InventoryServiceProductDetailProcedure,
			connect.WithSchema(inventoryServiceMethods.ByName("ProductDetail")),
			connect.WithClientOptions(opts...),
		),
	}
}

// inventoryServiceClient implements InventoryServiceClient.
type inventoryServiceClient struct {
	order                *connect.Client[v1.OrderRequest, v1.OrderResponse]
	stockMovement        *connect.Client[v1.StockMovementRequest, v1.StockMovementResponse]
	pushStockEvent       *connect.Client[v1.PushStockEventRequest, v1.PushStockEventResponse]
	transactionCreate    *connect.Client[v1.TransactionCreateRequest, v1.TransactionCreateResponse]
	transactionCancel    *connect.Client[v1.TransactionCancelRequest, v1.TransactionCancelResponse]
	productPlacementList *connect.Client[v1.ProductPlacementListRequest, v1.ProductPlacementListResponse]
	productPlacementLog  *connect.Client[v1.ProductPlacementLogRequest, v1.ProductPlacementLogResponse]
	productBatchList     *connect.Client[v1.ProductBatchListRequest, v1.ProductBatchListResponse]
	productReconcile     *connect.Client[v1.ProductReconcileRequest, v1.ProductReconcileResponse]
	rackCreate           *connect.Client[v1.RackCreateRequest, v1.RackCreateResponse]
	rackUpdate           *connect.Client[v1.RackUpdateRequest, v1.RackUpdateResponse]
	rackDelete           *connect.Client[v1.RackDeleteRequest, v1.RackDeleteResponse]
	rackDetail           *connect.Client[v1.RackDetailRequest, v1.RackDetailResponse]
	rackList             *connect.Client[v1.RackListRequest, v1.RackListResponse]
	productConfig        *connect.Client[v1.ProductConfigRequest, v1.ProductConfigResponse]
	productConfigUpdate  *connect.Client[v1.ProductConfigUpdateRequest, v1.ProductConfigUpdateResponse]
	productList          *connect.Client[v1.ProductListRequest, v1.ProductListResponse]
	productDetail        *connect.Client[v1.ProductDetailRequest, v1.ProductDetailResponse]
}

// Order calls inventory_iface.v1.InventoryService.Order.
func (c *inventoryServiceClient) Order(ctx context.Context, req *connect.Request[v1.OrderRequest]) (*connect.Response[v1.OrderResponse], error) {
	return c.order.CallUnary(ctx, req)
}

// StockMovement calls inventory_iface.v1.InventoryService.StockMovement.
func (c *inventoryServiceClient) StockMovement(ctx context.Context, req *connect.Request[v1.StockMovementRequest]) (*connect.Response[v1.StockMovementResponse], error) {
	return c.stockMovement.CallUnary(ctx, req)
}

// PushStockEvent calls inventory_iface.v1.InventoryService.PushStockEvent.
func (c *inventoryServiceClient) PushStockEvent(ctx context.Context, req *connect.Request[v1.PushStockEventRequest]) (*connect.Response[v1.PushStockEventResponse], error) {
	return c.pushStockEvent.CallUnary(ctx, req)
}

// TransactionCreate calls inventory_iface.v1.InventoryService.TransactionCreate.
func (c *inventoryServiceClient) TransactionCreate(ctx context.Context, req *connect.Request[v1.TransactionCreateRequest]) (*connect.Response[v1.TransactionCreateResponse], error) {
	return c.transactionCreate.CallUnary(ctx, req)
}

// TransactionCancel calls inventory_iface.v1.InventoryService.TransactionCancel.
func (c *inventoryServiceClient) TransactionCancel(ctx context.Context, req *connect.Request[v1.TransactionCancelRequest]) (*connect.Response[v1.TransactionCancelResponse], error) {
	return c.transactionCancel.CallUnary(ctx, req)
}

// ProductPlacementList calls inventory_iface.v1.InventoryService.ProductPlacementList.
func (c *inventoryServiceClient) ProductPlacementList(ctx context.Context, req *connect.Request[v1.ProductPlacementListRequest]) (*connect.Response[v1.ProductPlacementListResponse], error) {
	return c.productPlacementList.CallUnary(ctx, req)
}

// ProductPlacementLog calls inventory_iface.v1.InventoryService.ProductPlacementLog.
func (c *inventoryServiceClient) ProductPlacementLog(ctx context.Context, req *connect.Request[v1.ProductPlacementLogRequest]) (*connect.Response[v1.ProductPlacementLogResponse], error) {
	return c.productPlacementLog.CallUnary(ctx, req)
}

// ProductBatchList calls inventory_iface.v1.InventoryService.ProductBatchList.
func (c *inventoryServiceClient) ProductBatchList(ctx context.Context, req *connect.Request[v1.ProductBatchListRequest]) (*connect.Response[v1.ProductBatchListResponse], error) {
	return c.productBatchList.CallUnary(ctx, req)
}

// ProductReconcile calls inventory_iface.v1.InventoryService.ProductReconcile.
func (c *inventoryServiceClient) ProductReconcile(ctx context.Context, req *connect.Request[v1.ProductReconcileRequest]) (*connect.ServerStreamForClient[v1.ProductReconcileResponse], error) {
	return c.productReconcile.CallServerStream(ctx, req)
}

// RackCreate calls inventory_iface.v1.InventoryService.RackCreate.
func (c *inventoryServiceClient) RackCreate(ctx context.Context, req *connect.Request[v1.RackCreateRequest]) (*connect.Response[v1.RackCreateResponse], error) {
	return c.rackCreate.CallUnary(ctx, req)
}

// RackUpdate calls inventory_iface.v1.InventoryService.RackUpdate.
func (c *inventoryServiceClient) RackUpdate(ctx context.Context, req *connect.Request[v1.RackUpdateRequest]) (*connect.Response[v1.RackUpdateResponse], error) {
	return c.rackUpdate.CallUnary(ctx, req)
}

// RackDelete calls inventory_iface.v1.InventoryService.RackDelete.
func (c *inventoryServiceClient) RackDelete(ctx context.Context, req *connect.Request[v1.RackDeleteRequest]) (*connect.Response[v1.RackDeleteResponse], error) {
	return c.rackDelete.CallUnary(ctx, req)
}

// RackDetail calls inventory_iface.v1.InventoryService.RackDetail.
func (c *inventoryServiceClient) RackDetail(ctx context.Context, req *connect.Request[v1.RackDetailRequest]) (*connect.Response[v1.RackDetailResponse], error) {
	return c.rackDetail.CallUnary(ctx, req)
}

// RackList calls inventory_iface.v1.InventoryService.RackList.
func (c *inventoryServiceClient) RackList(ctx context.Context, req *connect.Request[v1.RackListRequest]) (*connect.Response[v1.RackListResponse], error) {
	return c.rackList.CallUnary(ctx, req)
}

// ProductConfig calls inventory_iface.v1.InventoryService.ProductConfig.
func (c *inventoryServiceClient) ProductConfig(ctx context.Context, req *connect.Request[v1.ProductConfigRequest]) (*connect.Response[v1.ProductConfigResponse], error) {
	return c.productConfig.CallUnary(ctx, req)
}

// ProductConfigUpdate calls inventory_iface.v1.InventoryService.ProductConfigUpdate.
func (c *inventoryServiceClient) ProductConfigUpdate(ctx context.Context, req *connect.Request[v1.ProductConfigUpdateRequest]) (*connect.Response[v1.ProductConfigUpdateResponse], error) {
	return c.productConfigUpdate.CallUnary(ctx, req)
}

// ProductList calls inventory_iface.v1.InventoryService.ProductList.
func (c *inventoryServiceClient) ProductList(ctx context.Context, req *connect.Request[v1.ProductListRequest]) (*connect.Response[v1.ProductListResponse], error) {
	return c.productList.CallUnary(ctx, req)
}

// ProductDetail calls inventory_iface.v1.InventoryService.ProductDetail.
func (c *inventoryServiceClient) ProductDetail(ctx context.Context, req *connect.Request[v1.ProductDetailRequest]) (*connect.Response[v1.ProductDetailResponse], error) {
	return c.productDetail.CallUnary(ctx, req)
}

// InventoryServiceHandler is an implementation of the inventory_iface.v1.InventoryService service.
type InventoryServiceHandler interface {
	Order(context.Context, *connect.Request[v1.OrderRequest]) (*connect.Response[v1.OrderResponse], error)
	StockMovement(context.Context, *connect.Request[v1.StockMovementRequest]) (*connect.Response[v1.StockMovementResponse], error)
	// PushStockEvent ingests a warehouse StockEvent (the RPC counterpart of the
	// Pub/Sub push handler) and applies it to inventory state in one transaction.
	PushStockEvent(context.Context, *connect.Request[v1.PushStockEventRequest]) (*connect.Response[v1.PushStockEventResponse], error)
	// Transaction management: a request-driven, inventory-owned stock mutation
	// (order/restock/return/found_back/problem). TransactionCancel reverses one.
	TransactionCreate(context.Context, *connect.Request[v1.TransactionCreateRequest]) (*connect.Response[v1.TransactionCreateResponse], error)
	TransactionCancel(context.Context, *connect.Request[v1.TransactionCancelRequest]) (*connect.Response[v1.TransactionCancelResponse], error)
	ProductPlacementList(context.Context, *connect.Request[v1.ProductPlacementListRequest]) (*connect.Response[v1.ProductPlacementListResponse], error)
	ProductPlacementLog(context.Context, *connect.Request[v1.ProductPlacementLogRequest]) (*connect.Response[v1.ProductPlacementLogResponse], error)
	ProductBatchList(context.Context, *connect.Request[v1.ProductBatchListRequest]) (*connect.Response[v1.ProductBatchListResponse], error)
	// untuk rekonsiliasi legacy
	ProductReconcile(context.Context, *connect.Request[v1.ProductReconcileRequest], *connect.ServerStream[v1.ProductReconcileResponse]) error
	// Rack management. All except RackList are scoped by warehouse_id.
	RackCreate(context.Context, *connect.Request[v1.RackCreateRequest]) (*connect.Response[v1.RackCreateResponse], error)
	RackUpdate(context.Context, *connect.Request[v1.RackUpdateRequest]) (*connect.Response[v1.RackUpdateResponse], error)
	RackDelete(context.Context, *connect.Request[v1.RackDeleteRequest]) (*connect.Response[v1.RackDeleteResponse], error)
	RackDetail(context.Context, *connect.Request[v1.RackDetailRequest]) (*connect.Response[v1.RackDetailResponse], error)
	RackList(context.Context, *connect.Request[v1.RackListRequest]) (*connect.Response[v1.RackListResponse], error)
	// Product management (config + views), scoped by warehouse_id.
	ProductConfig(context.Context, *connect.Request[v1.ProductConfigRequest]) (*connect.Response[v1.ProductConfigResponse], error)
	ProductConfigUpdate(context.Context, *connect.Request[v1.ProductConfigUpdateRequest]) (*connect.Response[v1.ProductConfigUpdateResponse], error)
	ProductList(context.Context, *connect.Request[v1.ProductListRequest]) (*connect.Response[v1.ProductListResponse], error)
	ProductDetail(context.Context, *connect.Request[v1.ProductDetailRequest]) (*connect.Response[v1.ProductDetailResponse], error)
}

// NewInventoryServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInventoryServiceHandler(svc InventoryServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	inventoryServiceMethods := v1.File_inventory_iface_v1_service_proto.Services().ByName("InventoryService").Methods()
	inventoryServiceOrderHandler := connect.NewUnaryHandler(
		InventoryServiceOrderProcedure,
		svc.Order,
		connect.WithSchema(inventoryServiceMethods.ByName("Order")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceStockMovementHandler := connect.NewUnaryHandler(
		InventoryServiceStockMovementProcedure,
		svc.StockMovement,
		connect.WithSchema(inventoryServiceMethods.ByName("StockMovement")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServicePushStockEventHandler := connect.NewUnaryHandler(
		InventoryServicePushStockEventProcedure,
		svc.PushStockEvent,
		connect.WithSchema(inventoryServiceMethods.ByName("PushStockEvent")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceTransactionCreateHandler := connect.NewUnaryHandler(
		InventoryServiceTransactionCreateProcedure,
		svc.TransactionCreate,
		connect.WithSchema(inventoryServiceMethods.ByName("TransactionCreate")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceTransactionCancelHandler := connect.NewUnaryHandler(
		InventoryServiceTransactionCancelProcedure,
		svc.TransactionCancel,
		connect.WithSchema(inventoryServiceMethods.ByName("TransactionCancel")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceProductPlacementListHandler := connect.NewUnaryHandler(
		InventoryServiceProductPlacementListProcedure,
		svc.ProductPlacementList,
		connect.WithSchema(inventoryServiceMethods.ByName("ProductPlacementList")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceProductPlacementLogHandler := connect.NewUnaryHandler(
		InventoryServiceProductPlacementLogProcedure,
		svc.ProductPlacementLog,
		connect.WithSchema(inventoryServiceMethods.ByName("ProductPlacementLog")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceProductBatchListHandler := connect.NewUnaryHandler(
		InventoryServiceProductBatchListProcedure,
		svc.ProductBatchList,
		connect.WithSchema(inventoryServiceMethods.ByName("ProductBatchList")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceProductReconcileHandler := connect.NewServerStreamHandler(
		InventoryServiceProductReconcileProcedure,
		svc.ProductReconcile,
		connect.WithSchema(inventoryServiceMethods.ByName("ProductReconcile")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceRackCreateHandler := connect.NewUnaryHandler(
		InventoryServiceRackCreateProcedure,
		svc.RackCreate,
		connect.WithSchema(inventoryServiceMethods.ByName("RackCreate")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceRackUpdateHandler := connect.NewUnaryHandler(
		InventoryServiceRackUpdateProcedure,
		svc.RackUpdate,
		connect.WithSchema(inventoryServiceMethods.ByName("RackUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceRackDeleteHandler := connect.NewUnaryHandler(
		InventoryServiceRackDeleteProcedure,
		svc.RackDelete,
		connect.WithSchema(inventoryServiceMethods.ByName("RackDelete")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceRackDetailHandler := connect.NewUnaryHandler(
		InventoryServiceRackDetailProcedure,
		svc.RackDetail,
		connect.WithSchema(inventoryServiceMethods.ByName("RackDetail")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceRackListHandler := connect.NewUnaryHandler(
		InventoryServiceRackListProcedure,
		svc.RackList,
		connect.WithSchema(inventoryServiceMethods.ByName("RackList")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceProductConfigHandler := connect.NewUnaryHandler(
		InventoryServiceProductConfigProcedure,
		svc.ProductConfig,
		connect.WithSchema(inventoryServiceMethods.ByName("ProductConfig")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceProductConfigUpdateHandler := connect.NewUnaryHandler(
		InventoryServiceProductConfigUpdateProcedure,
		svc.ProductConfigUpdate,
		connect.WithSchema(inventoryServiceMethods.ByName("ProductConfigUpdate")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceProductListHandler := connect.NewUnaryHandler(
		InventoryServiceProductListProcedure,
		svc.ProductList,
		connect.WithSchema(inventoryServiceMethods.ByName("ProductList")),
		connect.WithHandlerOptions(opts...),
	)
	inventoryServiceProductDetailHandler := connect.NewUnaryHandler(
		InventoryServiceProductDetailProcedure,
		svc.ProductDetail,
		connect.WithSchema(inventoryServiceMethods.ByName("ProductDetail")),
		connect.WithHandlerOptions(opts...),
	)
	return "/inventory_iface.v1.InventoryService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InventoryServiceOrderProcedure:
			inventoryServiceOrderHandler.ServeHTTP(w, r)
		case InventoryServiceStockMovementProcedure:
			inventoryServiceStockMovementHandler.ServeHTTP(w, r)
		case InventoryServicePushStockEventProcedure:
			inventoryServicePushStockEventHandler.ServeHTTP(w, r)
		case InventoryServiceTransactionCreateProcedure:
			inventoryServiceTransactionCreateHandler.ServeHTTP(w, r)
		case InventoryServiceTransactionCancelProcedure:
			inventoryServiceTransactionCancelHandler.ServeHTTP(w, r)
		case InventoryServiceProductPlacementListProcedure:
			inventoryServiceProductPlacementListHandler.ServeHTTP(w, r)
		case InventoryServiceProductPlacementLogProcedure:
			inventoryServiceProductPlacementLogHandler.ServeHTTP(w, r)
		case InventoryServiceProductBatchListProcedure:
			inventoryServiceProductBatchListHandler.ServeHTTP(w, r)
		case InventoryServiceProductReconcileProcedure:
			inventoryServiceProductReconcileHandler.ServeHTTP(w, r)
		case InventoryServiceRackCreateProcedure:
			inventoryServiceRackCreateHandler.ServeHTTP(w, r)
		case InventoryServiceRackUpdateProcedure:
			inventoryServiceRackUpdateHandler.ServeHTTP(w, r)
		case InventoryServiceRackDeleteProcedure:
			inventoryServiceRackDeleteHandler.ServeHTTP(w, r)
		case InventoryServiceRackDetailProcedure:
			inventoryServiceRackDetailHandler.ServeHTTP(w, r)
		case InventoryServiceRackListProcedure:
			inventoryServiceRackListHandler.ServeHTTP(w, r)
		case InventoryServiceProductConfigProcedure:
			inventoryServiceProductConfigHandler.ServeHTTP(w, r)
		case InventoryServiceProductConfigUpdateProcedure:
			inventoryServiceProductConfigUpdateHandler.ServeHTTP(w, r)
		case InventoryServiceProductListProcedure:
			inventoryServiceProductListHandler.ServeHTTP(w, r)
		case InventoryServiceProductDetailProcedure:
			inventoryServiceProductDetailHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInventoryServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInventoryServiceHandler struct{}

func (UnimplementedInventoryServiceHandler) Order(context.Context, *connect.Request[v1.OrderRequest]) (*connect.Response[v1.OrderResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.Order is not implemented"))
}

func (UnimplementedInventoryServiceHandler) StockMovement(context.Context, *connect.Request[v1.StockMovementRequest]) (*connect.Response[v1.StockMovementResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.StockMovement is not implemented"))
}

func (UnimplementedInventoryServiceHandler) PushStockEvent(context.Context, *connect.Request[v1.PushStockEventRequest]) (*connect.Response[v1.PushStockEventResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.PushStockEvent is not implemented"))
}

func (UnimplementedInventoryServiceHandler) TransactionCreate(context.Context, *connect.Request[v1.TransactionCreateRequest]) (*connect.Response[v1.TransactionCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.TransactionCreate is not implemented"))
}

func (UnimplementedInventoryServiceHandler) TransactionCancel(context.Context, *connect.Request[v1.TransactionCancelRequest]) (*connect.Response[v1.TransactionCancelResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.TransactionCancel is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ProductPlacementList(context.Context, *connect.Request[v1.ProductPlacementListRequest]) (*connect.Response[v1.ProductPlacementListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.ProductPlacementList is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ProductPlacementLog(context.Context, *connect.Request[v1.ProductPlacementLogRequest]) (*connect.Response[v1.ProductPlacementLogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.ProductPlacementLog is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ProductBatchList(context.Context, *connect.Request[v1.ProductBatchListRequest]) (*connect.Response[v1.ProductBatchListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.ProductBatchList is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ProductReconcile(context.Context, *connect.Request[v1.ProductReconcileRequest], *connect.ServerStream[v1.ProductReconcileResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.ProductReconcile is not implemented"))
}

func (UnimplementedInventoryServiceHandler) RackCreate(context.Context, *connect.Request[v1.RackCreateRequest]) (*connect.Response[v1.RackCreateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.RackCreate is not implemented"))
}

func (UnimplementedInventoryServiceHandler) RackUpdate(context.Context, *connect.Request[v1.RackUpdateRequest]) (*connect.Response[v1.RackUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.RackUpdate is not implemented"))
}

func (UnimplementedInventoryServiceHandler) RackDelete(context.Context, *connect.Request[v1.RackDeleteRequest]) (*connect.Response[v1.RackDeleteResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.RackDelete is not implemented"))
}

func (UnimplementedInventoryServiceHandler) RackDetail(context.Context, *connect.Request[v1.RackDetailRequest]) (*connect.Response[v1.RackDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.RackDetail is not implemented"))
}

func (UnimplementedInventoryServiceHandler) RackList(context.Context, *connect.Request[v1.RackListRequest]) (*connect.Response[v1.RackListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.RackList is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ProductConfig(context.Context, *connect.Request[v1.ProductConfigRequest]) (*connect.Response[v1.ProductConfigResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.ProductConfig is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ProductConfigUpdate(context.Context, *connect.Request[v1.ProductConfigUpdateRequest]) (*connect.Response[v1.ProductConfigUpdateResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.ProductConfigUpdate is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ProductList(context.Context, *connect.Request[v1.ProductListRequest]) (*connect.Response[v1.ProductListResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.ProductList is not implemented"))
}

func (UnimplementedInventoryServiceHandler) ProductDetail(context.Context, *connect.Request[v1.ProductDetailRequest]) (*connect.Response[v1.ProductDetailResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("inventory_iface.v1.InventoryService.ProductDetail is not implemented"))
}
