// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: selling_iface/v1/team_metric/v1/order_metric.proto

package team_metric

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TeamOrderMetricSort int32

const (
	TeamOrderMetricSort_TEAM_ORDER_METRIC_SORT_UNSPECIFIED         TeamOrderMetricSort = 0
	TeamOrderMetricSort_TEAM_ORDER_METRIC_SORT_TRANSACTION_COUNT   TeamOrderMetricSort = 1
	TeamOrderMetricSort_TEAM_ORDER_METRIC_SORT_PIECE_COUNT         TeamOrderMetricSort = 2
	TeamOrderMetricSort_TEAM_ORDER_METRIC_SORT_TOTAL_AMOUNT        TeamOrderMetricSort = 3
	TeamOrderMetricSort_TEAM_ORDER_METRIC_SORT_AVERAGE_ORDER_VALUE TeamOrderMetricSort = 4
)

// Enum value maps for TeamOrderMetricSort.
var (
	TeamOrderMetricSort_name = map[int32]string{
		0: "TEAM_ORDER_METRIC_SORT_UNSPECIFIED",
		1: "TEAM_ORDER_METRIC_SORT_TRANSACTION_COUNT",
		2: "TEAM_ORDER_METRIC_SORT_PIECE_COUNT",
		3: "TEAM_ORDER_METRIC_SORT_TOTAL_AMOUNT",
		4: "TEAM_ORDER_METRIC_SORT_AVERAGE_ORDER_VALUE",
	}
	TeamOrderMetricSort_value = map[string]int32{
		"TEAM_ORDER_METRIC_SORT_UNSPECIFIED":         0,
		"TEAM_ORDER_METRIC_SORT_TRANSACTION_COUNT":   1,
		"TEAM_ORDER_METRIC_SORT_PIECE_COUNT":         2,
		"TEAM_ORDER_METRIC_SORT_TOTAL_AMOUNT":        3,
		"TEAM_ORDER_METRIC_SORT_AVERAGE_ORDER_VALUE": 4,
	}
)

func (x TeamOrderMetricSort) Enum() *TeamOrderMetricSort {
	p := new(TeamOrderMetricSort)
	*p = x
	return p
}

func (x TeamOrderMetricSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TeamOrderMetricSort) Descriptor() protoreflect.EnumDescriptor {
	return file_selling_iface_v1_team_metric_v1_order_metric_proto_enumTypes[0].Descriptor()
}

func (TeamOrderMetricSort) Type() protoreflect.EnumType {
	return &file_selling_iface_v1_team_metric_v1_order_metric_proto_enumTypes[0]
}

func (x TeamOrderMetricSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TeamOrderMetricSort.Descriptor instead.
func (TeamOrderMetricSort) EnumDescriptor() ([]byte, []int) {
	return file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescGZIP(), []int{0}
}

type TeamOrderItem struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TeamId            uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TransactionCount  int64                  `protobuf:"varint,2,opt,name=transaction_count,json=transactionCount,proto3" json:"transaction_count,omitempty"`
	PieceCount        int64                  `protobuf:"varint,3,opt,name=piece_count,json=pieceCount,proto3" json:"piece_count,omitempty"`
	TotalAmount       float64                `protobuf:"fixed64,4,opt,name=total_amount,json=totalAmount,proto3" json:"total_amount,omitempty"`
	AverageOrderValue float64                `protobuf:"fixed64,5,opt,name=average_order_value,json=averageOrderValue,proto3" json:"average_order_value,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *TeamOrderItem) Reset() {
	*x = TeamOrderItem{}
	mi := &file_selling_iface_v1_team_metric_v1_order_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamOrderItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamOrderItem) ProtoMessage() {}

func (x *TeamOrderItem) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_team_metric_v1_order_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamOrderItem.ProtoReflect.Descriptor instead.
func (*TeamOrderItem) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescGZIP(), []int{0}
}

func (x *TeamOrderItem) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *TeamOrderItem) GetTransactionCount() int64 {
	if x != nil {
		return x.TransactionCount
	}
	return 0
}

func (x *TeamOrderItem) GetPieceCount() int64 {
	if x != nil {
		return x.PieceCount
	}
	return 0
}

func (x *TeamOrderItem) GetTotalAmount() float64 {
	if x != nil {
		return x.TotalAmount
	}
	return 0
}

func (x *TeamOrderItem) GetAverageOrderValue() float64 {
	if x != nil {
		return x.AverageOrderValue
	}
	return 0
}

type TeamOrderMetric struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Data          map[uint64]*TeamOrderItem `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TeamOrderMetric) Reset() {
	*x = TeamOrderMetric{}
	mi := &file_selling_iface_v1_team_metric_v1_order_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TeamOrderMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TeamOrderMetric) ProtoMessage() {}

func (x *TeamOrderMetric) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_team_metric_v1_order_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TeamOrderMetric.ProtoReflect.Descriptor instead.
func (*TeamOrderMetric) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescGZIP(), []int{1}
}

func (x *TeamOrderMetric) GetData() map[uint64]*TeamOrderItem {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_selling_iface_v1_team_metric_v1_order_metric_proto protoreflect.FileDescriptor

const file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDesc = "" +
	"\n" +
	"2selling_iface/v1/team_metric/v1/order_metric.proto\x12\x1fselling_iface.v1.team_metric.v1\"\xc9\x01\n" +
	"\rTeamOrderItem\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\x12+\n" +
	"\x11transaction_count\x18\x02 \x01(\x03R\x10transactionCount\x12\x1f\n" +
	"\vpiece_count\x18\x03 \x01(\x03R\n" +
	"pieceCount\x12!\n" +
	"\ftotal_amount\x18\x04 \x01(\x01R\vtotalAmount\x12.\n" +
	"\x13average_order_value\x18\x05 \x01(\x01R\x11averageOrderValue\"\xca\x01\n" +
	"\x0fTeamOrderMetric\x12N\n" +
	"\x04data\x18\x01 \x03(\v2:.selling_iface.v1.team_metric.v1.TeamOrderMetric.DataEntryR\x04data\x1ag\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12D\n" +
	"\x05value\x18\x02 \x01(\v2..selling_iface.v1.team_metric.v1.TeamOrderItemR\x05value:\x028\x01*\xec\x01\n" +
	"\x13TeamOrderMetricSort\x12&\n" +
	"\"TEAM_ORDER_METRIC_SORT_UNSPECIFIED\x10\x00\x12,\n" +
	"(TEAM_ORDER_METRIC_SORT_TRANSACTION_COUNT\x10\x01\x12&\n" +
	"\"TEAM_ORDER_METRIC_SORT_PIECE_COUNT\x10\x02\x12'\n" +
	"#TEAM_ORDER_METRIC_SORT_TOTAL_AMOUNT\x10\x03\x12.\n" +
	"*TEAM_ORDER_METRIC_SORT_AVERAGE_ORDER_VALUE\x10\x04B\x9c\x02\n" +
	"#com.selling_iface.v1.team_metric.v1B\x10OrderMetricProtoP\x01ZLgithub.com/pdcgo/schema/services/selling_iface/v1/team_metric/v1;team_metric\xa2\x02\x03SVT\xaa\x02\x1dSellingIface.V1.TeamMetric.V1\xca\x02\x1dSellingIface\\V1\\TeamMetric\\V1\xe2\x02)SellingIface\\V1\\TeamMetric\\V1\\GPBMetadata\xea\x02 SellingIface::V1::TeamMetric::V1b\x06proto3"

var (
	file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescOnce sync.Once
	file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescData []byte
)

func file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescGZIP() []byte {
	file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescOnce.Do(func() {
		file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDesc), len(file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDesc)))
	})
	return file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDescData
}

var file_selling_iface_v1_team_metric_v1_order_metric_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_selling_iface_v1_team_metric_v1_order_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_selling_iface_v1_team_metric_v1_order_metric_proto_goTypes = []any{
	(TeamOrderMetricSort)(0), // 0: selling_iface.v1.team_metric.v1.TeamOrderMetricSort
	(*TeamOrderItem)(nil),    // 1: selling_iface.v1.team_metric.v1.TeamOrderItem
	(*TeamOrderMetric)(nil),  // 2: selling_iface.v1.team_metric.v1.TeamOrderMetric
	nil,                      // 3: selling_iface.v1.team_metric.v1.TeamOrderMetric.DataEntry
}
var file_selling_iface_v1_team_metric_v1_order_metric_proto_depIdxs = []int32{
	3, // 0: selling_iface.v1.team_metric.v1.TeamOrderMetric.data:type_name -> selling_iface.v1.team_metric.v1.TeamOrderMetric.DataEntry
	1, // 1: selling_iface.v1.team_metric.v1.TeamOrderMetric.DataEntry.value:type_name -> selling_iface.v1.team_metric.v1.TeamOrderItem
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_selling_iface_v1_team_metric_v1_order_metric_proto_init() }
func file_selling_iface_v1_team_metric_v1_order_metric_proto_init() {
	if File_selling_iface_v1_team_metric_v1_order_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDesc), len(file_selling_iface_v1_team_metric_v1_order_metric_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_selling_iface_v1_team_metric_v1_order_metric_proto_goTypes,
		DependencyIndexes: file_selling_iface_v1_team_metric_v1_order_metric_proto_depIdxs,
		EnumInfos:         file_selling_iface_v1_team_metric_v1_order_metric_proto_enumTypes,
		MessageInfos:      file_selling_iface_v1_team_metric_v1_order_metric_proto_msgTypes,
	}.Build()
	File_selling_iface_v1_team_metric_v1_order_metric_proto = out.File
	file_selling_iface_v1_team_metric_v1_order_metric_proto_goTypes = nil
	file_selling_iface_v1_team_metric_v1_order_metric_proto_depIdxs = nil
}
