// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: common/v1/stock.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InboundSource int32

const (
	InboundSource_INBOUND_SOURCE_UNSPECIFIED InboundSource = 0
	InboundSource_INBOUND_SOURCE_RESTOCK     InboundSource = 1
	InboundSource_INBOUND_SOURCE_RETURN      InboundSource = 2
	InboundSource_INBOUND_SOURCE_TRANSFER    InboundSource = 3
)

// Enum value maps for InboundSource.
var (
	InboundSource_name = map[int32]string{
		0: "INBOUND_SOURCE_UNSPECIFIED",
		1: "INBOUND_SOURCE_RESTOCK",
		2: "INBOUND_SOURCE_RETURN",
		3: "INBOUND_SOURCE_TRANSFER",
	}
	InboundSource_value = map[string]int32{
		"INBOUND_SOURCE_UNSPECIFIED": 0,
		"INBOUND_SOURCE_RESTOCK":     1,
		"INBOUND_SOURCE_RETURN":      2,
		"INBOUND_SOURCE_TRANSFER":    3,
	}
)

func (x InboundSource) Enum() *InboundSource {
	p := new(InboundSource)
	*p = x
	return p
}

func (x InboundSource) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InboundSource) Descriptor() protoreflect.EnumDescriptor {
	return file_common_v1_stock_proto_enumTypes[0].Descriptor()
}

func (InboundSource) Type() protoreflect.EnumType {
	return &file_common_v1_stock_proto_enumTypes[0]
}

func (x InboundSource) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InboundSource.Descriptor instead.
func (InboundSource) EnumDescriptor() ([]byte, []int) {
	return file_common_v1_stock_proto_rawDescGZIP(), []int{0}
}

var File_common_v1_stock_proto protoreflect.FileDescriptor

const file_common_v1_stock_proto_rawDesc = "" +
	"\n" +
	"\x15common/v1/stock.proto\x12\tcommon.v1*\x83\x01\n" +
	"\rInboundSource\x12\x1e\n" +
	"\x1aINBOUND_SOURCE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16INBOUND_SOURCE_RESTOCK\x10\x01\x12\x19\n" +
	"\x15INBOUND_SOURCE_RETURN\x10\x02\x12\x1b\n" +
	"\x17INBOUND_SOURCE_TRANSFER\x10\x03B\x93\x01\n" +
	"\rcom.common.v1B\n" +
	"StockProtoP\x01Z1github.com/pdcgo/schema/services/common/v1;common\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1b\x06proto3"

var (
	file_common_v1_stock_proto_rawDescOnce sync.Once
	file_common_v1_stock_proto_rawDescData []byte
)

func file_common_v1_stock_proto_rawDescGZIP() []byte {
	file_common_v1_stock_proto_rawDescOnce.Do(func() {
		file_common_v1_stock_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_stock_proto_rawDesc), len(file_common_v1_stock_proto_rawDesc)))
	})
	return file_common_v1_stock_proto_rawDescData
}

var file_common_v1_stock_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_v1_stock_proto_goTypes = []any{
	(InboundSource)(0), // 0: common.v1.InboundSource
}
var file_common_v1_stock_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_v1_stock_proto_init() }
func file_common_v1_stock_proto_init() {
	if File_common_v1_stock_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_stock_proto_rawDesc), len(file_common_v1_stock_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_v1_stock_proto_goTypes,
		DependencyIndexes: file_common_v1_stock_proto_depIdxs,
		EnumInfos:         file_common_v1_stock_proto_enumTypes,
	}.Build()
	File_common_v1_stock_proto = out.File
	file_common_v1_stock_proto_goTypes = nil
	file_common_v1_stock_proto_depIdxs = nil
}
