// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/v1/supplier.proto

package common

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PublicSupplierIDsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []uint64               `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicSupplierIDsRequest) Reset() {
	*x = PublicSupplierIDsRequest{}
	mi := &file_common_v1_supplier_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicSupplierIDsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSupplierIDsRequest) ProtoMessage() {}

func (x *PublicSupplierIDsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_supplier_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSupplierIDsRequest.ProtoReflect.Descriptor instead.
func (*PublicSupplierIDsRequest) Descriptor() ([]byte, []int) {
	return file_common_v1_supplier_proto_rawDescGZIP(), []int{0}
}

func (x *PublicSupplierIDsRequest) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type Supplier struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TeamId           uint64                 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	SupplierName     string                 `protobuf:"bytes,3,opt,name=supplier_name,json=supplierName,proto3" json:"supplier_name,omitempty"`
	SupplierUsername string                 `protobuf:"bytes,4,opt,name=supplier_username,json=supplierUsername,proto3" json:"supplier_username,omitempty"`
	MarketplaceType  MarketplaceType        `protobuf:"varint,5,opt,name=marketplace_type,json=marketplaceType,proto3,enum=common.v1.MarketplaceType" json:"marketplace_type,omitempty"`
	Uri              string                 `protobuf:"bytes,6,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Supplier) Reset() {
	*x = Supplier{}
	mi := &file_common_v1_supplier_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Supplier) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Supplier) ProtoMessage() {}

func (x *Supplier) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_supplier_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Supplier.ProtoReflect.Descriptor instead.
func (*Supplier) Descriptor() ([]byte, []int) {
	return file_common_v1_supplier_proto_rawDescGZIP(), []int{1}
}

func (x *Supplier) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Supplier) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *Supplier) GetSupplierName() string {
	if x != nil {
		return x.SupplierName
	}
	return ""
}

func (x *Supplier) GetSupplierUsername() string {
	if x != nil {
		return x.SupplierUsername
	}
	return ""
}

func (x *Supplier) GetMarketplaceType() MarketplaceType {
	if x != nil {
		return x.MarketplaceType
	}
	return MarketplaceType_MARKETPLACE_TYPE_UNSPECIFIED
}

func (x *Supplier) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type PublicSupplierIDsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          map[uint64]*Supplier   `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublicSupplierIDsResponse) Reset() {
	*x = PublicSupplierIDsResponse{}
	mi := &file_common_v1_supplier_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublicSupplierIDsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublicSupplierIDsResponse) ProtoMessage() {}

func (x *PublicSupplierIDsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_v1_supplier_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublicSupplierIDsResponse.ProtoReflect.Descriptor instead.
func (*PublicSupplierIDsResponse) Descriptor() ([]byte, []int) {
	return file_common_v1_supplier_proto_rawDescGZIP(), []int{2}
}

func (x *PublicSupplierIDsResponse) GetData() map[uint64]*Supplier {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_common_v1_supplier_proto protoreflect.FileDescriptor

const file_common_v1_supplier_proto_rawDesc = "" +
	"\n" +
	"\x18common/v1/supplier.proto\x12\tcommon.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/v1/common.proto\"A\n" +
	"\x18PublicSupplierIDsRequest\x12%\n" +
	"\x03ids\x18\x01 \x03(\x04B\x13\xbaH\x10\x92\x01\r\b\x01\x10\xc8\x01\x18\x01\"\x042\x02 \x00R\x03ids\"\xde\x01\n" +
	"\bSupplier\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x17\n" +
	"\ateam_id\x18\x02 \x01(\x04R\x06teamId\x12#\n" +
	"\rsupplier_name\x18\x03 \x01(\tR\fsupplierName\x12+\n" +
	"\x11supplier_username\x18\x04 \x01(\tR\x10supplierUsername\x12E\n" +
	"\x10marketplace_type\x18\x05 \x01(\x0e2\x1a.common.v1.MarketplaceTypeR\x0fmarketplaceType\x12\x10\n" +
	"\x03uri\x18\x06 \x01(\tR\x03uri\"\xad\x01\n" +
	"\x19PublicSupplierIDsResponse\x12B\n" +
	"\x04data\x18\x01 \x03(\v2..common.v1.PublicSupplierIDsResponse.DataEntryR\x04data\x1aL\n" +
	"\tDataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x04R\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.common.v1.SupplierR\x05value:\x028\x012q\n" +
	"\x0fSupplierService\x12^\n" +
	"\x11PublicSupplierIDs\x12#.common.v1.PublicSupplierIDsRequest\x1a$.common.v1.PublicSupplierIDsResponseB\x96\x01\n" +
	"\rcom.common.v1B\rSupplierProtoP\x01Z1github.com/pdcgo/schema/services/common/v1;common\xa2\x02\x03CXX\xaa\x02\tCommon.V1\xca\x02\tCommon\\V1\xe2\x02\x15Common\\V1\\GPBMetadata\xea\x02\n" +
	"Common::V1b\x06proto3"

var (
	file_common_v1_supplier_proto_rawDescOnce sync.Once
	file_common_v1_supplier_proto_rawDescData []byte
)

func file_common_v1_supplier_proto_rawDescGZIP() []byte {
	file_common_v1_supplier_proto_rawDescOnce.Do(func() {
		file_common_v1_supplier_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_v1_supplier_proto_rawDesc), len(file_common_v1_supplier_proto_rawDesc)))
	})
	return file_common_v1_supplier_proto_rawDescData
}

var file_common_v1_supplier_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_v1_supplier_proto_goTypes = []any{
	(*PublicSupplierIDsRequest)(nil),  // 0: common.v1.PublicSupplierIDsRequest
	(*Supplier)(nil),                  // 1: common.v1.Supplier
	(*PublicSupplierIDsResponse)(nil), // 2: common.v1.PublicSupplierIDsResponse
	nil,                               // 3: common.v1.PublicSupplierIDsResponse.DataEntry
	(MarketplaceType)(0),              // 4: common.v1.MarketplaceType
}
var file_common_v1_supplier_proto_depIdxs = []int32{
	4, // 0: common.v1.Supplier.marketplace_type:type_name -> common.v1.MarketplaceType
	3, // 1: common.v1.PublicSupplierIDsResponse.data:type_name -> common.v1.PublicSupplierIDsResponse.DataEntry
	1, // 2: common.v1.PublicSupplierIDsResponse.DataEntry.value:type_name -> common.v1.Supplier
	0, // 3: common.v1.SupplierService.PublicSupplierIDs:input_type -> common.v1.PublicSupplierIDsRequest
	2, // 4: common.v1.SupplierService.PublicSupplierIDs:output_type -> common.v1.PublicSupplierIDsResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_v1_supplier_proto_init() }
func file_common_v1_supplier_proto_init() {
	if File_common_v1_supplier_proto != nil {
		return
	}
	file_common_v1_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_v1_supplier_proto_rawDesc), len(file_common_v1_supplier_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_common_v1_supplier_proto_goTypes,
		DependencyIndexes: file_common_v1_supplier_proto_depIdxs,
		MessageInfos:      file_common_v1_supplier_proto_msgTypes,
	}.Build()
	File_common_v1_supplier_proto = out.File
	file_common_v1_supplier_proto_goTypes = nil
	file_common_v1_supplier_proto_depIdxs = nil
}
