// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: selling_iface/v1/metric.proto

package selling_iface

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricType int32

const (
	MetricType_METRIC_TYPE_UNSPECIFIED                MetricType = 0
	MetricType_METRIC_TYPE_TOTAL_STOCK                MetricType = 1
	MetricType_METRIC_TYPE_ONGOING_STOCK              MetricType = 2
	MetricType_METRIC_TYPE_READY_STOCK                MetricType = 3
	MetricType_METRIC_TYPE_PAYABLE                    MetricType = 4
	MetricType_METRIC_TYPE_RECEIVABLE                 MetricType = 5
	MetricType_METRIC_TYPE_PRODUCT_SOLD               MetricType = 6
	MetricType_METRIC_TYPE_HISTORY_PRODUCT_SOLD       MetricType = 8
	MetricType_METRIC_TYPE_ORDER_ACTIVE               MetricType = 7
	MetricType_METRIC_TYPE_HISTORY_ORDER              MetricType = 9
	MetricType_METRIC_TYPE_TOP_PRODUCT_SOLD           MetricType = 10
	MetricType_METRIC_TYPE_TOP_PRODUCT_UNSOLD         MetricType = 11
	MetricType_METRIC_TYPE_HISTORY_RESTOCK            MetricType = 14
	MetricType_METRIC_TYPE_HISTORY_RESTOCK_CANCEL     MetricType = 23
	MetricType_METRIC_TYPE_HISTORY_TRANSFER           MetricType = 24
	MetricType_METRIC_TYPE_HISTORY_TRANSFER_CANCEL    MetricType = 25
	MetricType_METRIC_TYPE_HISTORY_RETURN             MetricType = 15
	MetricType_METRIC_TYPE_HISTORY_STOCK_RESOLUTION   MetricType = 16
	MetricType_METRIC_TYPE_HISTORY_STOCK_ORDER        MetricType = 17
	MetricType_METRIC_TYPE_HISTORY_STOCK_ORDER_CANCEL MetricType = 22
	MetricType_METRIC_TYPE_HISTORY_SHIPMENT_PROBLEM   MetricType = 18
	MetricType_METRIC_TYPE_HISTORY_WAREHOUSE_PROBLEM  MetricType = 19
	MetricType_METRIC_TYPE_HISTORY_READY_STOCK        MetricType = 20
	MetricType_METRIC_TYPE_HISTORY_WAREHOUSE_COD_COST MetricType = 21
)

// Enum value maps for MetricType.
var (
	MetricType_name = map[int32]string{
		0:  "METRIC_TYPE_UNSPECIFIED",
		1:  "METRIC_TYPE_TOTAL_STOCK",
		2:  "METRIC_TYPE_ONGOING_STOCK",
		3:  "METRIC_TYPE_READY_STOCK",
		4:  "METRIC_TYPE_PAYABLE",
		5:  "METRIC_TYPE_RECEIVABLE",
		6:  "METRIC_TYPE_PRODUCT_SOLD",
		8:  "METRIC_TYPE_HISTORY_PRODUCT_SOLD",
		7:  "METRIC_TYPE_ORDER_ACTIVE",
		9:  "METRIC_TYPE_HISTORY_ORDER",
		10: "METRIC_TYPE_TOP_PRODUCT_SOLD",
		11: "METRIC_TYPE_TOP_PRODUCT_UNSOLD",
		14: "METRIC_TYPE_HISTORY_RESTOCK",
		23: "METRIC_TYPE_HISTORY_RESTOCK_CANCEL",
		24: "METRIC_TYPE_HISTORY_TRANSFER",
		25: "METRIC_TYPE_HISTORY_TRANSFER_CANCEL",
		15: "METRIC_TYPE_HISTORY_RETURN",
		16: "METRIC_TYPE_HISTORY_STOCK_RESOLUTION",
		17: "METRIC_TYPE_HISTORY_STOCK_ORDER",
		22: "METRIC_TYPE_HISTORY_STOCK_ORDER_CANCEL",
		18: "METRIC_TYPE_HISTORY_SHIPMENT_PROBLEM",
		19: "METRIC_TYPE_HISTORY_WAREHOUSE_PROBLEM",
		20: "METRIC_TYPE_HISTORY_READY_STOCK",
		21: "METRIC_TYPE_HISTORY_WAREHOUSE_COD_COST",
	}
	MetricType_value = map[string]int32{
		"METRIC_TYPE_UNSPECIFIED":                0,
		"METRIC_TYPE_TOTAL_STOCK":                1,
		"METRIC_TYPE_ONGOING_STOCK":              2,
		"METRIC_TYPE_READY_STOCK":                3,
		"METRIC_TYPE_PAYABLE":                    4,
		"METRIC_TYPE_RECEIVABLE":                 5,
		"METRIC_TYPE_PRODUCT_SOLD":               6,
		"METRIC_TYPE_HISTORY_PRODUCT_SOLD":       8,
		"METRIC_TYPE_ORDER_ACTIVE":               7,
		"METRIC_TYPE_HISTORY_ORDER":              9,
		"METRIC_TYPE_TOP_PRODUCT_SOLD":           10,
		"METRIC_TYPE_TOP_PRODUCT_UNSOLD":         11,
		"METRIC_TYPE_HISTORY_RESTOCK":            14,
		"METRIC_TYPE_HISTORY_RESTOCK_CANCEL":     23,
		"METRIC_TYPE_HISTORY_TRANSFER":           24,
		"METRIC_TYPE_HISTORY_TRANSFER_CANCEL":    25,
		"METRIC_TYPE_HISTORY_RETURN":             15,
		"METRIC_TYPE_HISTORY_STOCK_RESOLUTION":   16,
		"METRIC_TYPE_HISTORY_STOCK_ORDER":        17,
		"METRIC_TYPE_HISTORY_STOCK_ORDER_CANCEL": 22,
		"METRIC_TYPE_HISTORY_SHIPMENT_PROBLEM":   18,
		"METRIC_TYPE_HISTORY_WAREHOUSE_PROBLEM":  19,
		"METRIC_TYPE_HISTORY_READY_STOCK":        20,
		"METRIC_TYPE_HISTORY_WAREHOUSE_COD_COST": 21,
	}
)

func (x MetricType) Enum() *MetricType {
	p := new(MetricType)
	*p = x
	return p
}

func (x MetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_selling_iface_v1_metric_proto_enumTypes[0].Descriptor()
}

func (MetricType) Type() protoreflect.EnumType {
	return &file_selling_iface_v1_metric_proto_enumTypes[0]
}

func (x MetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MetricType.Descriptor instead.
func (MetricType) EnumDescriptor() ([]byte, []int) {
	return file_selling_iface_v1_metric_proto_rawDescGZIP(), []int{0}
}

var File_selling_iface_v1_metric_proto protoreflect.FileDescriptor

const file_selling_iface_v1_metric_proto_rawDesc = "" +
	"\n" +
	"\x1dselling_iface/v1/metric.proto\x12\x10selling_iface.v1*\xd3\x06\n" +
	"\n" +
	"MetricType\x12\x1b\n" +
	"\x17METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17METRIC_TYPE_TOTAL_STOCK\x10\x01\x12\x1d\n" +
	"\x19METRIC_TYPE_ONGOING_STOCK\x10\x02\x12\x1b\n" +
	"\x17METRIC_TYPE_READY_STOCK\x10\x03\x12\x17\n" +
	"\x13METRIC_TYPE_PAYABLE\x10\x04\x12\x1a\n" +
	"\x16METRIC_TYPE_RECEIVABLE\x10\x05\x12\x1c\n" +
	"\x18METRIC_TYPE_PRODUCT_SOLD\x10\x06\x12$\n" +
	" METRIC_TYPE_HISTORY_PRODUCT_SOLD\x10\b\x12\x1c\n" +
	"\x18METRIC_TYPE_ORDER_ACTIVE\x10\a\x12\x1d\n" +
	"\x19METRIC_TYPE_HISTORY_ORDER\x10\t\x12 \n" +
	"\x1cMETRIC_TYPE_TOP_PRODUCT_SOLD\x10\n" +
	"\x12\"\n" +
	"\x1eMETRIC_TYPE_TOP_PRODUCT_UNSOLD\x10\v\x12\x1f\n" +
	"\x1bMETRIC_TYPE_HISTORY_RESTOCK\x10\x0e\x12&\n" +
	"\"METRIC_TYPE_HISTORY_RESTOCK_CANCEL\x10\x17\x12 \n" +
	"\x1cMETRIC_TYPE_HISTORY_TRANSFER\x10\x18\x12'\n" +
	"#METRIC_TYPE_HISTORY_TRANSFER_CANCEL\x10\x19\x12\x1e\n" +
	"\x1aMETRIC_TYPE_HISTORY_RETURN\x10\x0f\x12(\n" +
	"$METRIC_TYPE_HISTORY_STOCK_RESOLUTION\x10\x10\x12#\n" +
	"\x1fMETRIC_TYPE_HISTORY_STOCK_ORDER\x10\x11\x12*\n" +
	"&METRIC_TYPE_HISTORY_STOCK_ORDER_CANCEL\x10\x16\x12(\n" +
	"$METRIC_TYPE_HISTORY_SHIPMENT_PROBLEM\x10\x12\x12)\n" +
	"%METRIC_TYPE_HISTORY_WAREHOUSE_PROBLEM\x10\x13\x12#\n" +
	"\x1fMETRIC_TYPE_HISTORY_READY_STOCK\x10\x14\x12*\n" +
	"&METRIC_TYPE_HISTORY_WAREHOUSE_COD_COST\x10\x15B\xc1\x01\n" +
	"\x14com.selling_iface.v1B\vMetricProtoP\x01Z?github.com/pdcgo/schema/services/selling_iface/v1;selling_iface\xa2\x02\x03SXX\xaa\x02\x0fSellingIface.V1\xca\x02\x0fSellingIface\\V1\xe2\x02\x1bSellingIface\\V1\\GPBMetadata\xea\x02\x10SellingIface::V1b\x06proto3"

var (
	file_selling_iface_v1_metric_proto_rawDescOnce sync.Once
	file_selling_iface_v1_metric_proto_rawDescData []byte
)

func file_selling_iface_v1_metric_proto_rawDescGZIP() []byte {
	file_selling_iface_v1_metric_proto_rawDescOnce.Do(func() {
		file_selling_iface_v1_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_selling_iface_v1_metric_proto_rawDesc), len(file_selling_iface_v1_metric_proto_rawDesc)))
	})
	return file_selling_iface_v1_metric_proto_rawDescData
}

var file_selling_iface_v1_metric_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_selling_iface_v1_metric_proto_goTypes = []any{
	(MetricType)(0), // 0: selling_iface.v1.MetricType
}
var file_selling_iface_v1_metric_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_selling_iface_v1_metric_proto_init() }
func file_selling_iface_v1_metric_proto_init() {
	if File_selling_iface_v1_metric_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_selling_iface_v1_metric_proto_rawDesc), len(file_selling_iface_v1_metric_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_selling_iface_v1_metric_proto_goTypes,
		DependencyIndexes: file_selling_iface_v1_metric_proto_depIdxs,
		EnumInfos:         file_selling_iface_v1_metric_proto_enumTypes,
	}.Build()
	File_selling_iface_v1_metric_proto = out.File
	file_selling_iface_v1_metric_proto_goTypes = nil
	file_selling_iface_v1_metric_proto_depIdxs = nil
}
