// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: selling_iface/v1/shop_stat_metric.proto

package selling_iface

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v11 "github.com/pdcgo/schema/services/common/v1"
	v1 "github.com/pdcgo/schema/services/selling_iface/v1/shop_metric/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ShopMetricType int32

const (
	ShopMetricType_SHOP_METRIC_TYPE_UNSPECIFIED       ShopMetricType = 0
	ShopMetricType_SHOP_METRIC_TYPE_ORDER             ShopMetricType = 1
	ShopMetricType_SHOP_METRIC_TYPE_ORDER_COMPLETED   ShopMetricType = 8
	ShopMetricType_SHOP_METRIC_TYPE_ORDER_CANCELLED   ShopMetricType = 9
	ShopMetricType_SHOP_METRIC_TYPE_ADS_EXPENSE       ShopMetricType = 2
	ShopMetricType_SHOP_METRIC_TYPE_RETURN_CREATED    ShopMetricType = 3
	ShopMetricType_SHOP_METRIC_TYPE_HOLD_AMOUNT       ShopMetricType = 4
	ShopMetricType_SHOP_METRIC_TYPE_PRODUCT_COST      ShopMetricType = 5
	ShopMetricType_SHOP_METRIC_TYPE_EXPORT_WITHDRAWAL ShopMetricType = 6
	ShopMetricType_SHOP_METRIC_TYPE_REAL_REVENUE      ShopMetricType = 7
)

// Enum value maps for ShopMetricType.
var (
	ShopMetricType_name = map[int32]string{
		0: "SHOP_METRIC_TYPE_UNSPECIFIED",
		1: "SHOP_METRIC_TYPE_ORDER",
		8: "SHOP_METRIC_TYPE_ORDER_COMPLETED",
		9: "SHOP_METRIC_TYPE_ORDER_CANCELLED",
		2: "SHOP_METRIC_TYPE_ADS_EXPENSE",
		3: "SHOP_METRIC_TYPE_RETURN_CREATED",
		4: "SHOP_METRIC_TYPE_HOLD_AMOUNT",
		5: "SHOP_METRIC_TYPE_PRODUCT_COST",
		6: "SHOP_METRIC_TYPE_EXPORT_WITHDRAWAL",
		7: "SHOP_METRIC_TYPE_REAL_REVENUE",
	}
	ShopMetricType_value = map[string]int32{
		"SHOP_METRIC_TYPE_UNSPECIFIED":       0,
		"SHOP_METRIC_TYPE_ORDER":             1,
		"SHOP_METRIC_TYPE_ORDER_COMPLETED":   8,
		"SHOP_METRIC_TYPE_ORDER_CANCELLED":   9,
		"SHOP_METRIC_TYPE_ADS_EXPENSE":       2,
		"SHOP_METRIC_TYPE_RETURN_CREATED":    3,
		"SHOP_METRIC_TYPE_HOLD_AMOUNT":       4,
		"SHOP_METRIC_TYPE_PRODUCT_COST":      5,
		"SHOP_METRIC_TYPE_EXPORT_WITHDRAWAL": 6,
		"SHOP_METRIC_TYPE_REAL_REVENUE":      7,
	}
)

func (x ShopMetricType) Enum() *ShopMetricType {
	p := new(ShopMetricType)
	*p = x
	return p
}

func (x ShopMetricType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopMetricType) Descriptor() protoreflect.EnumDescriptor {
	return file_selling_iface_v1_shop_stat_metric_proto_enumTypes[0].Descriptor()
}

func (ShopMetricType) Type() protoreflect.EnumType {
	return &file_selling_iface_v1_shop_stat_metric_proto_enumTypes[0]
}

func (x ShopMetricType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopMetricType.Descriptor instead.
func (ShopMetricType) EnumDescriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{0}
}

type ShopMetricSortType int32

const (
	ShopMetricSortType_SHOP_METRIC_SORT_TYPE_UNSPECIFIED ShopMetricSortType = 0
	ShopMetricSortType_SHOP_METRIC_SORT_TYPE_ASC         ShopMetricSortType = 1
	ShopMetricSortType_SHOP_METRIC_SORT_TYPE_DESC        ShopMetricSortType = 2
)

// Enum value maps for ShopMetricSortType.
var (
	ShopMetricSortType_name = map[int32]string{
		0: "SHOP_METRIC_SORT_TYPE_UNSPECIFIED",
		1: "SHOP_METRIC_SORT_TYPE_ASC",
		2: "SHOP_METRIC_SORT_TYPE_DESC",
	}
	ShopMetricSortType_value = map[string]int32{
		"SHOP_METRIC_SORT_TYPE_UNSPECIFIED": 0,
		"SHOP_METRIC_SORT_TYPE_ASC":         1,
		"SHOP_METRIC_SORT_TYPE_DESC":        2,
	}
)

func (x ShopMetricSortType) Enum() *ShopMetricSortType {
	p := new(ShopMetricSortType)
	*p = x
	return p
}

func (x ShopMetricSortType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ShopMetricSortType) Descriptor() protoreflect.EnumDescriptor {
	return file_selling_iface_v1_shop_stat_metric_proto_enumTypes[1].Descriptor()
}

func (ShopMetricSortType) Type() protoreflect.EnumType {
	return &file_selling_iface_v1_shop_stat_metric_proto_enumTypes[1]
}

func (x ShopMetricSortType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ShopMetricSortType.Descriptor instead.
func (ShopMetricSortType) EnumDescriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{1}
}

type CommonShopSort int32

const (
	CommonShopSort_COMMON_SHOP_SORT_UNSPECIFIED CommonShopSort = 0
	CommonShopSort_COMMON_SHOP_SORT_NAME        CommonShopSort = 1
	CommonShopSort_COMMON_SHOP_SORT_USERNAME    CommonShopSort = 2
)

// Enum value maps for CommonShopSort.
var (
	CommonShopSort_name = map[int32]string{
		0: "COMMON_SHOP_SORT_UNSPECIFIED",
		1: "COMMON_SHOP_SORT_NAME",
		2: "COMMON_SHOP_SORT_USERNAME",
	}
	CommonShopSort_value = map[string]int32{
		"COMMON_SHOP_SORT_UNSPECIFIED": 0,
		"COMMON_SHOP_SORT_NAME":        1,
		"COMMON_SHOP_SORT_USERNAME":    2,
	}
)

func (x CommonShopSort) Enum() *CommonShopSort {
	p := new(CommonShopSort)
	*p = x
	return p
}

func (x CommonShopSort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CommonShopSort) Descriptor() protoreflect.EnumDescriptor {
	return file_selling_iface_v1_shop_stat_metric_proto_enumTypes[2].Descriptor()
}

func (CommonShopSort) Type() protoreflect.EnumType {
	return &file_selling_iface_v1_shop_stat_metric_proto_enumTypes[2]
}

func (x CommonShopSort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CommonShopSort.Descriptor instead.
func (CommonShopSort) EnumDescriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{2}
}

type ShopMetricSort struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SortType ShopMetricSortType     `protobuf:"varint,1,opt,name=sort_type,json=sortType,proto3,enum=selling_iface.v1.ShopMetricSortType" json:"sort_type,omitempty"`
	// Types that are valid to be assigned to S:
	//
	//	*ShopMetricSort_CommonSort
	//	*ShopMetricSort_ShopOrderMetricSort
	//	*ShopMetricSort_ShopOrderCompletedMetricSort
	//	*ShopMetricSort_ShopOrderCancelledMetricSort
	//	*ShopMetricSort_ShopReturnMetricSort
	//	*ShopMetricSort_ShopReturnArrivedMetricSort
	//	*ShopMetricSort_ShopReturnCancelledMetricSort
	//	*ShopMetricSort_ShopProductCostMetricSort
	//	*ShopMetricSort_ShopAdsExpenseMetricSort
	//	*ShopMetricSort_ShopHoldAmountMetricSort
	S             isShopMetricSort_S `protobuf_oneof:"s"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopMetricSort) Reset() {
	*x = ShopMetricSort{}
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopMetricSort) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopMetricSort) ProtoMessage() {}

func (x *ShopMetricSort) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopMetricSort.ProtoReflect.Descriptor instead.
func (*ShopMetricSort) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{0}
}

func (x *ShopMetricSort) GetSortType() ShopMetricSortType {
	if x != nil {
		return x.SortType
	}
	return ShopMetricSortType_SHOP_METRIC_SORT_TYPE_UNSPECIFIED
}

func (x *ShopMetricSort) GetS() isShopMetricSort_S {
	if x != nil {
		return x.S
	}
	return nil
}

func (x *ShopMetricSort) GetCommonSort() CommonShopSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_CommonSort); ok {
			return x.CommonSort
		}
	}
	return CommonShopSort_COMMON_SHOP_SORT_UNSPECIFIED
}

func (x *ShopMetricSort) GetShopOrderMetricSort() v1.ShopOrderMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopOrderMetricSort); ok {
			return x.ShopOrderMetricSort
		}
	}
	return v1.ShopOrderMetricSort(0)
}

func (x *ShopMetricSort) GetShopOrderCompletedMetricSort() v1.ShopOrderCompletedMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopOrderCompletedMetricSort); ok {
			return x.ShopOrderCompletedMetricSort
		}
	}
	return v1.ShopOrderCompletedMetricSort(0)
}

func (x *ShopMetricSort) GetShopOrderCancelledMetricSort() v1.ShopOrderCancelledMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopOrderCancelledMetricSort); ok {
			return x.ShopOrderCancelledMetricSort
		}
	}
	return v1.ShopOrderCancelledMetricSort(0)
}

func (x *ShopMetricSort) GetShopReturnMetricSort() v1.ShopReturnMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopReturnMetricSort); ok {
			return x.ShopReturnMetricSort
		}
	}
	return v1.ShopReturnMetricSort(0)
}

func (x *ShopMetricSort) GetShopReturnArrivedMetricSort() v1.ShopReturnArrivedMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopReturnArrivedMetricSort); ok {
			return x.ShopReturnArrivedMetricSort
		}
	}
	return v1.ShopReturnArrivedMetricSort(0)
}

func (x *ShopMetricSort) GetShopReturnCancelledMetricSort() v1.ShopReturnCancelledMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopReturnCancelledMetricSort); ok {
			return x.ShopReturnCancelledMetricSort
		}
	}
	return v1.ShopReturnCancelledMetricSort(0)
}

func (x *ShopMetricSort) GetShopProductCostMetricSort() v1.ShopProductCostMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopProductCostMetricSort); ok {
			return x.ShopProductCostMetricSort
		}
	}
	return v1.ShopProductCostMetricSort(0)
}

func (x *ShopMetricSort) GetShopAdsExpenseMetricSort() v1.ShopAdsExpenseMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopAdsExpenseMetricSort); ok {
			return x.ShopAdsExpenseMetricSort
		}
	}
	return v1.ShopAdsExpenseMetricSort(0)
}

func (x *ShopMetricSort) GetShopHoldAmountMetricSort() v1.ShopHoldAmountMetricSort {
	if x != nil {
		if x, ok := x.S.(*ShopMetricSort_ShopHoldAmountMetricSort); ok {
			return x.ShopHoldAmountMetricSort
		}
	}
	return v1.ShopHoldAmountMetricSort(0)
}

type isShopMetricSort_S interface {
	isShopMetricSort_S()
}

type ShopMetricSort_CommonSort struct {
	CommonSort CommonShopSort `protobuf:"varint,2,opt,name=common_sort,json=commonSort,proto3,enum=selling_iface.v1.CommonShopSort,oneof"`
}

type ShopMetricSort_ShopOrderMetricSort struct {
	ShopOrderMetricSort v1.ShopOrderMetricSort `protobuf:"varint,3,opt,name=shop_order_metric_sort,json=shopOrderMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopOrderMetricSort,oneof"`
}

type ShopMetricSort_ShopOrderCompletedMetricSort struct {
	ShopOrderCompletedMetricSort v1.ShopOrderCompletedMetricSort `protobuf:"varint,7,opt,name=shop_order_completed_metric_sort,json=shopOrderCompletedMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopOrderCompletedMetricSort,oneof"`
}

type ShopMetricSort_ShopOrderCancelledMetricSort struct {
	ShopOrderCancelledMetricSort v1.ShopOrderCancelledMetricSort `protobuf:"varint,8,opt,name=shop_order_cancelled_metric_sort,json=shopOrderCancelledMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopOrderCancelledMetricSort,oneof"`
}

type ShopMetricSort_ShopReturnMetricSort struct {
	ShopReturnMetricSort v1.ShopReturnMetricSort `protobuf:"varint,9,opt,name=shop_return_metric_sort,json=shopReturnMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopReturnMetricSort,oneof"`
}

type ShopMetricSort_ShopReturnArrivedMetricSort struct {
	ShopReturnArrivedMetricSort v1.ShopReturnArrivedMetricSort `protobuf:"varint,10,opt,name=shop_return_arrived_metric_sort,json=shopReturnArrivedMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopReturnArrivedMetricSort,oneof"`
}

type ShopMetricSort_ShopReturnCancelledMetricSort struct {
	ShopReturnCancelledMetricSort v1.ShopReturnCancelledMetricSort `protobuf:"varint,11,opt,name=shop_return_cancelled_metric_sort,json=shopReturnCancelledMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopReturnCancelledMetricSort,oneof"`
}

type ShopMetricSort_ShopProductCostMetricSort struct {
	ShopProductCostMetricSort v1.ShopProductCostMetricSort `protobuf:"varint,4,opt,name=shop_product_cost_metric_sort,json=shopProductCostMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopProductCostMetricSort,oneof"`
}

type ShopMetricSort_ShopAdsExpenseMetricSort struct {
	ShopAdsExpenseMetricSort v1.ShopAdsExpenseMetricSort `protobuf:"varint,5,opt,name=shop_ads_expense_metric_sort,json=shopAdsExpenseMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopAdsExpenseMetricSort,oneof"`
}

type ShopMetricSort_ShopHoldAmountMetricSort struct {
	ShopHoldAmountMetricSort v1.ShopHoldAmountMetricSort `protobuf:"varint,6,opt,name=shop_hold_amount_metric_sort,json=shopHoldAmountMetricSort,proto3,enum=selling_iface.v1.shop_metric.v1.ShopHoldAmountMetricSort,oneof"`
}

func (*ShopMetricSort_CommonSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopOrderMetricSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopOrderCompletedMetricSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopOrderCancelledMetricSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopReturnMetricSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopReturnArrivedMetricSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopReturnCancelledMetricSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopProductCostMetricSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopAdsExpenseMetricSort) isShopMetricSort_S() {}

func (*ShopMetricSort_ShopHoldAmountMetricSort) isShopMetricSort_S() {}

type ShopMetric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Data:
	//
	//	*ShopMetric_ShopOrderMetric
	//	*ShopMetric_ShopOrderCompletedMetric
	//	*ShopMetric_ShopOrderCancelledMetric
	//	*ShopMetric_ShopReturnMetric
	//	*ShopMetric_ShopReturnArrivedMetric
	//	*ShopMetric_ShopReturnCancelledMetric
	//	*ShopMetric_ShopProductCostMetric
	//	*ShopMetric_ShopAdsExpenseMetric
	//	*ShopMetric_ShopHoldAmountMetric
	Data          isShopMetric_Data `protobuf_oneof:"data"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopMetric) Reset() {
	*x = ShopMetric{}
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopMetric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopMetric) ProtoMessage() {}

func (x *ShopMetric) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopMetric.ProtoReflect.Descriptor instead.
func (*ShopMetric) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{1}
}

func (x *ShopMetric) GetData() isShopMetric_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *ShopMetric) GetShopOrderMetric() *v1.ShopOrderMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopOrderMetric); ok {
			return x.ShopOrderMetric
		}
	}
	return nil
}

func (x *ShopMetric) GetShopOrderCompletedMetric() *v1.ShopOrderCompletedMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopOrderCompletedMetric); ok {
			return x.ShopOrderCompletedMetric
		}
	}
	return nil
}

func (x *ShopMetric) GetShopOrderCancelledMetric() *v1.ShopOrderCancelledMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopOrderCancelledMetric); ok {
			return x.ShopOrderCancelledMetric
		}
	}
	return nil
}

func (x *ShopMetric) GetShopReturnMetric() *v1.ShopReturnMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopReturnMetric); ok {
			return x.ShopReturnMetric
		}
	}
	return nil
}

func (x *ShopMetric) GetShopReturnArrivedMetric() *v1.ShopReturnArrivedMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopReturnArrivedMetric); ok {
			return x.ShopReturnArrivedMetric
		}
	}
	return nil
}

func (x *ShopMetric) GetShopReturnCancelledMetric() *v1.ShopReturnCancelledMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopReturnCancelledMetric); ok {
			return x.ShopReturnCancelledMetric
		}
	}
	return nil
}

func (x *ShopMetric) GetShopProductCostMetric() *v1.ShopProductCostMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopProductCostMetric); ok {
			return x.ShopProductCostMetric
		}
	}
	return nil
}

func (x *ShopMetric) GetShopAdsExpenseMetric() *v1.ShopAdsExpenseMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopAdsExpenseMetric); ok {
			return x.ShopAdsExpenseMetric
		}
	}
	return nil
}

func (x *ShopMetric) GetShopHoldAmountMetric() *v1.ShopHoldAmountMetric {
	if x != nil {
		if x, ok := x.Data.(*ShopMetric_ShopHoldAmountMetric); ok {
			return x.ShopHoldAmountMetric
		}
	}
	return nil
}

type isShopMetric_Data interface {
	isShopMetric_Data()
}

type ShopMetric_ShopOrderMetric struct {
	ShopOrderMetric *v1.ShopOrderMetric `protobuf:"bytes,1,opt,name=shop_order_metric,json=shopOrderMetric,proto3,oneof"`
}

type ShopMetric_ShopOrderCompletedMetric struct {
	ShopOrderCompletedMetric *v1.ShopOrderCompletedMetric `protobuf:"bytes,5,opt,name=shop_order_completed_metric,json=shopOrderCompletedMetric,proto3,oneof"`
}

type ShopMetric_ShopOrderCancelledMetric struct {
	ShopOrderCancelledMetric *v1.ShopOrderCancelledMetric `protobuf:"bytes,6,opt,name=shop_order_cancelled_metric,json=shopOrderCancelledMetric,proto3,oneof"`
}

type ShopMetric_ShopReturnMetric struct {
	ShopReturnMetric *v1.ShopReturnMetric `protobuf:"bytes,7,opt,name=shop_return_metric,json=shopReturnMetric,proto3,oneof"`
}

type ShopMetric_ShopReturnArrivedMetric struct {
	ShopReturnArrivedMetric *v1.ShopReturnArrivedMetric `protobuf:"bytes,8,opt,name=shop_return_arrived_metric,json=shopReturnArrivedMetric,proto3,oneof"`
}

type ShopMetric_ShopReturnCancelledMetric struct {
	ShopReturnCancelledMetric *v1.ShopReturnCancelledMetric `protobuf:"bytes,9,opt,name=shop_return_cancelled_metric,json=shopReturnCancelledMetric,proto3,oneof"`
}

type ShopMetric_ShopProductCostMetric struct {
	ShopProductCostMetric *v1.ShopProductCostMetric `protobuf:"bytes,2,opt,name=shop_product_cost_metric,json=shopProductCostMetric,proto3,oneof"`
}

type ShopMetric_ShopAdsExpenseMetric struct {
	ShopAdsExpenseMetric *v1.ShopAdsExpenseMetric `protobuf:"bytes,3,opt,name=shop_ads_expense_metric,json=shopAdsExpenseMetric,proto3,oneof"`
}

type ShopMetric_ShopHoldAmountMetric struct {
	ShopHoldAmountMetric *v1.ShopHoldAmountMetric `protobuf:"bytes,4,opt,name=shop_hold_amount_metric,json=shopHoldAmountMetric,proto3,oneof"`
}

func (*ShopMetric_ShopOrderMetric) isShopMetric_Data() {}

func (*ShopMetric_ShopOrderCompletedMetric) isShopMetric_Data() {}

func (*ShopMetric_ShopOrderCancelledMetric) isShopMetric_Data() {}

func (*ShopMetric_ShopReturnMetric) isShopMetric_Data() {}

func (*ShopMetric_ShopReturnArrivedMetric) isShopMetric_Data() {}

func (*ShopMetric_ShopReturnCancelledMetric) isShopMetric_Data() {}

func (*ShopMetric_ShopProductCostMetric) isShopMetric_Data() {}

func (*ShopMetric_ShopAdsExpenseMetric) isShopMetric_Data() {}

func (*ShopMetric_ShopHoldAmountMetric) isShopMetric_Data() {}

type ShopMetricExtra struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopMetricExtra) Reset() {
	*x = ShopMetricExtra{}
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopMetricExtra) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopMetricExtra) ProtoMessage() {}

func (x *ShopMetricExtra) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopMetricExtra.ProtoReflect.Descriptor instead.
func (*ShopMetricExtra) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{2}
}

type ShopStatMetricFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	WarehouseId   uint64                 `protobuf:"varint,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	ProductName   string                 `protobuf:"bytes,3,opt,name=product_name,json=productName,proto3" json:"product_name,omitempty"`
	Page          *v11.PageFilter        `protobuf:"bytes,4,opt,name=page,proto3" json:"page,omitempty"`
	Range         *ShopStatTimeRange     `protobuf:"bytes,5,opt,name=range,proto3" json:"range,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopStatMetricFilter) Reset() {
	*x = ShopStatMetricFilter{}
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopStatMetricFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopStatMetricFilter) ProtoMessage() {}

func (x *ShopStatMetricFilter) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopStatMetricFilter.ProtoReflect.Descriptor instead.
func (*ShopStatMetricFilter) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{3}
}

func (x *ShopStatMetricFilter) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *ShopStatMetricFilter) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *ShopStatMetricFilter) GetProductName() string {
	if x != nil {
		return x.ProductName
	}
	return ""
}

func (x *ShopStatMetricFilter) GetPage() *v11.PageFilter {
	if x != nil {
		return x.Page
	}
	return nil
}

func (x *ShopStatMetricFilter) GetRange() *ShopStatTimeRange {
	if x != nil {
		return x.Range
	}
	return nil
}

type ShopStatTimeRange struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Start         *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=start,proto3" json:"start,omitempty"`
	End           *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=end,proto3" json:"end,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopStatTimeRange) Reset() {
	*x = ShopStatTimeRange{}
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopStatTimeRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopStatTimeRange) ProtoMessage() {}

func (x *ShopStatTimeRange) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopStatTimeRange.ProtoReflect.Descriptor instead.
func (*ShopStatTimeRange) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{4}
}

func (x *ShopStatTimeRange) GetStart() *timestamppb.Timestamp {
	if x != nil {
		return x.Start
	}
	return nil
}

func (x *ShopStatTimeRange) GetEnd() *timestamppb.Timestamp {
	if x != nil {
		return x.End
	}
	return nil
}

type ShopStatMetricRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *ShopStatMetricFilter  `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Sort          *ShopMetricSort        `protobuf:"bytes,2,opt,name=sort,proto3" json:"sort,omitempty"`
	MetricExtras  []*ShopMetricExtra     `protobuf:"bytes,3,rep,name=metric_extras,json=metricExtras,proto3" json:"metric_extras,omitempty"`
	MetricTypes   []ShopMetricType       `protobuf:"varint,4,rep,packed,name=metric_types,json=metricTypes,proto3,enum=selling_iface.v1.ShopMetricType" json:"metric_types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopStatMetricRequest) Reset() {
	*x = ShopStatMetricRequest{}
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopStatMetricRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopStatMetricRequest) ProtoMessage() {}

func (x *ShopStatMetricRequest) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopStatMetricRequest.ProtoReflect.Descriptor instead.
func (*ShopStatMetricRequest) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{5}
}

func (x *ShopStatMetricRequest) GetFilter() *ShopStatMetricFilter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *ShopStatMetricRequest) GetSort() *ShopMetricSort {
	if x != nil {
		return x.Sort
	}
	return nil
}

func (x *ShopStatMetricRequest) GetMetricExtras() []*ShopMetricExtra {
	if x != nil {
		return x.MetricExtras
	}
	return nil
}

func (x *ShopStatMetricRequest) GetMetricTypes() []ShopMetricType {
	if x != nil {
		return x.MetricTypes
	}
	return nil
}

type ShopStatMetricResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metrics       []*ShopMetric          `protobuf:"bytes,1,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Ids           []uint64               `protobuf:"varint,2,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ShopStatMetricResponse) Reset() {
	*x = ShopStatMetricResponse{}
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShopStatMetricResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShopStatMetricResponse) ProtoMessage() {}

func (x *ShopStatMetricResponse) ProtoReflect() protoreflect.Message {
	mi := &file_selling_iface_v1_shop_stat_metric_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShopStatMetricResponse.ProtoReflect.Descriptor instead.
func (*ShopStatMetricResponse) Descriptor() ([]byte, []int) {
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP(), []int{6}
}

func (x *ShopStatMetricResponse) GetMetrics() []*ShopMetric {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ShopStatMetricResponse) GetIds() []uint64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

var File_selling_iface_v1_shop_stat_metric_proto protoreflect.FileDescriptor

const file_selling_iface_v1_shop_stat_metric_proto_rawDesc = "" +
	"\n" +
	"'selling_iface/v1/shop_stat_metric.proto\x12\x10selling_iface.v1\x1a\x1bbuf/validate/validate.proto\x1a\x16common/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a2selling_iface/v1/shop_metric/v1/order_metric.proto\"\x9c\n" +
	"\n" +
	"\x0eShopMetricSort\x12A\n" +
	"\tsort_type\x18\x01 \x01(\x0e2$.selling_iface.v1.ShopMetricSortTypeR\bsortType\x12C\n" +
	"\vcommon_sort\x18\x02 \x01(\x0e2 .selling_iface.v1.CommonShopSortH\x00R\n" +
	"commonSort\x12k\n" +
	"\x16shop_order_metric_sort\x18\x03 \x01(\x0e24.selling_iface.v1.shop_metric.v1.ShopOrderMetricSortH\x00R\x13shopOrderMetricSort\x12\x87\x01\n" +
	" shop_order_completed_metric_sort\x18\a \x01(\x0e2=.selling_iface.v1.shop_metric.v1.ShopOrderCompletedMetricSortH\x00R\x1cshopOrderCompletedMetricSort\x12\x87\x01\n" +
	" shop_order_cancelled_metric_sort\x18\b \x01(\x0e2=.selling_iface.v1.shop_metric.v1.ShopOrderCancelledMetricSortH\x00R\x1cshopOrderCancelledMetricSort\x12n\n" +
	"\x17shop_return_metric_sort\x18\t \x01(\x0e25.selling_iface.v1.shop_metric.v1.ShopReturnMetricSortH\x00R\x14shopReturnMetricSort\x12\x84\x01\n" +
	"\x1fshop_return_arrived_metric_sort\x18\n" +
	" \x01(\x0e2<.selling_iface.v1.shop_metric.v1.ShopReturnArrivedMetricSortH\x00R\x1bshopReturnArrivedMetricSort\x12\x8a\x01\n" +
	"!shop_return_cancelled_metric_sort\x18\v \x01(\x0e2>.selling_iface.v1.shop_metric.v1.ShopReturnCancelledMetricSortH\x00R\x1dshopReturnCancelledMetricSort\x12~\n" +
	"\x1dshop_product_cost_metric_sort\x18\x04 \x01(\x0e2:.selling_iface.v1.shop_metric.v1.ShopProductCostMetricSortH\x00R\x19shopProductCostMetricSort\x12{\n" +
	"\x1cshop_ads_expense_metric_sort\x18\x05 \x01(\x0e29.selling_iface.v1.shop_metric.v1.ShopAdsExpenseMetricSortH\x00R\x18shopAdsExpenseMetricSort\x12{\n" +
	"\x1cshop_hold_amount_metric_sort\x18\x06 \x01(\x0e29.selling_iface.v1.shop_metric.v1.ShopHoldAmountMetricSortH\x00R\x18shopHoldAmountMetricSortB\x03\n" +
	"\x01s\"\x9a\b\n" +
	"\n" +
	"ShopMetric\x12^\n" +
	"\x11shop_order_metric\x18\x01 \x01(\v20.selling_iface.v1.shop_metric.v1.ShopOrderMetricH\x00R\x0fshopOrderMetric\x12z\n" +
	"\x1bshop_order_completed_metric\x18\x05 \x01(\v29.selling_iface.v1.shop_metric.v1.ShopOrderCompletedMetricH\x00R\x18shopOrderCompletedMetric\x12z\n" +
	"\x1bshop_order_cancelled_metric\x18\x06 \x01(\v29.selling_iface.v1.shop_metric.v1.ShopOrderCancelledMetricH\x00R\x18shopOrderCancelledMetric\x12a\n" +
	"\x12shop_return_metric\x18\a \x01(\v21.selling_iface.v1.shop_metric.v1.ShopReturnMetricH\x00R\x10shopReturnMetric\x12w\n" +
	"\x1ashop_return_arrived_metric\x18\b \x01(\v28.selling_iface.v1.shop_metric.v1.ShopReturnArrivedMetricH\x00R\x17shopReturnArrivedMetric\x12}\n" +
	"\x1cshop_return_cancelled_metric\x18\t \x01(\v2:.selling_iface.v1.shop_metric.v1.ShopReturnCancelledMetricH\x00R\x19shopReturnCancelledMetric\x12q\n" +
	"\x18shop_product_cost_metric\x18\x02 \x01(\v26.selling_iface.v1.shop_metric.v1.ShopProductCostMetricH\x00R\x15shopProductCostMetric\x12n\n" +
	"\x17shop_ads_expense_metric\x18\x03 \x01(\v25.selling_iface.v1.shop_metric.v1.ShopAdsExpenseMetricH\x00R\x14shopAdsExpenseMetric\x12n\n" +
	"\x17shop_hold_amount_metric\x18\x04 \x01(\v25.selling_iface.v1.shop_metric.v1.ShopHoldAmountMetricH\x00R\x14shopHoldAmountMetricB\x06\n" +
	"\x04data\"\x11\n" +
	"\x0fShopMetricExtra\"\xe3\x01\n" +
	"\x14ShopStatMetricFilter\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\x04R\vwarehouseId\x12!\n" +
	"\fproduct_name\x18\x03 \x01(\tR\vproductName\x12)\n" +
	"\x04page\x18\x04 \x01(\v2\x15.common.v1.PageFilterR\x04page\x12A\n" +
	"\x05range\x18\x05 \x01(\v2#.selling_iface.v1.ShopStatTimeRangeB\x06\xbaH\x03\xc8\x01\x01R\x05range\"\x83\x01\n" +
	"\x11ShopStatTimeRange\x128\n" +
	"\x05start\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x05start\x124\n" +
	"\x03end\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\x03end\"\xaa\x02\n" +
	"\x15ShopStatMetricRequest\x12F\n" +
	"\x06filter\x18\x01 \x01(\v2&.selling_iface.v1.ShopStatMetricFilterB\x06\xbaH\x03\xc8\x01\x01R\x06filter\x12<\n" +
	"\x04sort\x18\x02 \x01(\v2 .selling_iface.v1.ShopMetricSortB\x06\xbaH\x03\xc8\x01\x01R\x04sort\x12F\n" +
	"\rmetric_extras\x18\x03 \x03(\v2!.selling_iface.v1.ShopMetricExtraR\fmetricExtras\x12C\n" +
	"\fmetric_types\x18\x04 \x03(\x0e2 .selling_iface.v1.ShopMetricTypeR\vmetricTypes\"b\n" +
	"\x16ShopStatMetricResponse\x126\n" +
	"\ametrics\x18\x01 \x03(\v2\x1c.selling_iface.v1.ShopMetricR\ametrics\x12\x10\n" +
	"\x03ids\x18\x02 \x03(\x04R\x03ids*\xf1\x02\n" +
	"\x0eShopMetricType\x12 \n" +
	"\x1cSHOP_METRIC_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16SHOP_METRIC_TYPE_ORDER\x10\x01\x12$\n" +
	" SHOP_METRIC_TYPE_ORDER_COMPLETED\x10\b\x12$\n" +
	" SHOP_METRIC_TYPE_ORDER_CANCELLED\x10\t\x12 \n" +
	"\x1cSHOP_METRIC_TYPE_ADS_EXPENSE\x10\x02\x12#\n" +
	"\x1fSHOP_METRIC_TYPE_RETURN_CREATED\x10\x03\x12 \n" +
	"\x1cSHOP_METRIC_TYPE_HOLD_AMOUNT\x10\x04\x12!\n" +
	"\x1dSHOP_METRIC_TYPE_PRODUCT_COST\x10\x05\x12&\n" +
	"\"SHOP_METRIC_TYPE_EXPORT_WITHDRAWAL\x10\x06\x12!\n" +
	"\x1dSHOP_METRIC_TYPE_REAL_REVENUE\x10\a*z\n" +
	"\x12ShopMetricSortType\x12%\n" +
	"!SHOP_METRIC_SORT_TYPE_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19SHOP_METRIC_SORT_TYPE_ASC\x10\x01\x12\x1e\n" +
	"\x1aSHOP_METRIC_SORT_TYPE_DESC\x10\x02*l\n" +
	"\x0eCommonShopSort\x12 \n" +
	"\x1cCOMMON_SHOP_SORT_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15COMMON_SHOP_SORT_NAME\x10\x01\x12\x1d\n" +
	"\x19COMMON_SHOP_SORT_USERNAME\x10\x02B\xc9\x01\n" +
	"\x14com.selling_iface.v1B\x13ShopStatMetricProtoP\x01Z?github.com/pdcgo/schema/services/selling_iface/v1;selling_iface\xa2\x02\x03SXX\xaa\x02\x0fSellingIface.V1\xca\x02\x0fSellingIface\\V1\xe2\x02\x1bSellingIface\\V1\\GPBMetadata\xea\x02\x10SellingIface::V1b\x06proto3"

var (
	file_selling_iface_v1_shop_stat_metric_proto_rawDescOnce sync.Once
	file_selling_iface_v1_shop_stat_metric_proto_rawDescData []byte
)

func file_selling_iface_v1_shop_stat_metric_proto_rawDescGZIP() []byte {
	file_selling_iface_v1_shop_stat_metric_proto_rawDescOnce.Do(func() {
		file_selling_iface_v1_shop_stat_metric_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_selling_iface_v1_shop_stat_metric_proto_rawDesc), len(file_selling_iface_v1_shop_stat_metric_proto_rawDesc)))
	})
	return file_selling_iface_v1_shop_stat_metric_proto_rawDescData
}

var file_selling_iface_v1_shop_stat_metric_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_selling_iface_v1_shop_stat_metric_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_selling_iface_v1_shop_stat_metric_proto_goTypes = []any{
	(ShopMetricType)(0),                   // 0: selling_iface.v1.ShopMetricType
	(ShopMetricSortType)(0),               // 1: selling_iface.v1.ShopMetricSortType
	(CommonShopSort)(0),                   // 2: selling_iface.v1.CommonShopSort
	(*ShopMetricSort)(nil),                // 3: selling_iface.v1.ShopMetricSort
	(*ShopMetric)(nil),                    // 4: selling_iface.v1.ShopMetric
	(*ShopMetricExtra)(nil),               // 5: selling_iface.v1.ShopMetricExtra
	(*ShopStatMetricFilter)(nil),          // 6: selling_iface.v1.ShopStatMetricFilter
	(*ShopStatTimeRange)(nil),             // 7: selling_iface.v1.ShopStatTimeRange
	(*ShopStatMetricRequest)(nil),         // 8: selling_iface.v1.ShopStatMetricRequest
	(*ShopStatMetricResponse)(nil),        // 9: selling_iface.v1.ShopStatMetricResponse
	(v1.ShopOrderMetricSort)(0),           // 10: selling_iface.v1.shop_metric.v1.ShopOrderMetricSort
	(v1.ShopOrderCompletedMetricSort)(0),  // 11: selling_iface.v1.shop_metric.v1.ShopOrderCompletedMetricSort
	(v1.ShopOrderCancelledMetricSort)(0),  // 12: selling_iface.v1.shop_metric.v1.ShopOrderCancelledMetricSort
	(v1.ShopReturnMetricSort)(0),          // 13: selling_iface.v1.shop_metric.v1.ShopReturnMetricSort
	(v1.ShopReturnArrivedMetricSort)(0),   // 14: selling_iface.v1.shop_metric.v1.ShopReturnArrivedMetricSort
	(v1.ShopReturnCancelledMetricSort)(0), // 15: selling_iface.v1.shop_metric.v1.ShopReturnCancelledMetricSort
	(v1.ShopProductCostMetricSort)(0),     // 16: selling_iface.v1.shop_metric.v1.ShopProductCostMetricSort
	(v1.ShopAdsExpenseMetricSort)(0),      // 17: selling_iface.v1.shop_metric.v1.ShopAdsExpenseMetricSort
	(v1.ShopHoldAmountMetricSort)(0),      // 18: selling_iface.v1.shop_metric.v1.ShopHoldAmountMetricSort
	(*v1.ShopOrderMetric)(nil),            // 19: selling_iface.v1.shop_metric.v1.ShopOrderMetric
	(*v1.ShopOrderCompletedMetric)(nil),   // 20: selling_iface.v1.shop_metric.v1.ShopOrderCompletedMetric
	(*v1.ShopOrderCancelledMetric)(nil),   // 21: selling_iface.v1.shop_metric.v1.ShopOrderCancelledMetric
	(*v1.ShopReturnMetric)(nil),           // 22: selling_iface.v1.shop_metric.v1.ShopReturnMetric
	(*v1.ShopReturnArrivedMetric)(nil),    // 23: selling_iface.v1.shop_metric.v1.ShopReturnArrivedMetric
	(*v1.ShopReturnCancelledMetric)(nil),  // 24: selling_iface.v1.shop_metric.v1.ShopReturnCancelledMetric
	(*v1.ShopProductCostMetric)(nil),      // 25: selling_iface.v1.shop_metric.v1.ShopProductCostMetric
	(*v1.ShopAdsExpenseMetric)(nil),       // 26: selling_iface.v1.shop_metric.v1.ShopAdsExpenseMetric
	(*v1.ShopHoldAmountMetric)(nil),       // 27: selling_iface.v1.shop_metric.v1.ShopHoldAmountMetric
	(*v11.PageFilter)(nil),                // 28: common.v1.PageFilter
	(*timestamppb.Timestamp)(nil),         // 29: google.protobuf.Timestamp
}
var file_selling_iface_v1_shop_stat_metric_proto_depIdxs = []int32{
	1,  // 0: selling_iface.v1.ShopMetricSort.sort_type:type_name -> selling_iface.v1.ShopMetricSortType
	2,  // 1: selling_iface.v1.ShopMetricSort.common_sort:type_name -> selling_iface.v1.CommonShopSort
	10, // 2: selling_iface.v1.ShopMetricSort.shop_order_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopOrderMetricSort
	11, // 3: selling_iface.v1.ShopMetricSort.shop_order_completed_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopOrderCompletedMetricSort
	12, // 4: selling_iface.v1.ShopMetricSort.shop_order_cancelled_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopOrderCancelledMetricSort
	13, // 5: selling_iface.v1.ShopMetricSort.shop_return_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopReturnMetricSort
	14, // 6: selling_iface.v1.ShopMetricSort.shop_return_arrived_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopReturnArrivedMetricSort
	15, // 7: selling_iface.v1.ShopMetricSort.shop_return_cancelled_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopReturnCancelledMetricSort
	16, // 8: selling_iface.v1.ShopMetricSort.shop_product_cost_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopProductCostMetricSort
	17, // 9: selling_iface.v1.ShopMetricSort.shop_ads_expense_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopAdsExpenseMetricSort
	18, // 10: selling_iface.v1.ShopMetricSort.shop_hold_amount_metric_sort:type_name -> selling_iface.v1.shop_metric.v1.ShopHoldAmountMetricSort
	19, // 11: selling_iface.v1.ShopMetric.shop_order_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopOrderMetric
	20, // 12: selling_iface.v1.ShopMetric.shop_order_completed_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopOrderCompletedMetric
	21, // 13: selling_iface.v1.ShopMetric.shop_order_cancelled_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopOrderCancelledMetric
	22, // 14: selling_iface.v1.ShopMetric.shop_return_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopReturnMetric
	23, // 15: selling_iface.v1.ShopMetric.shop_return_arrived_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopReturnArrivedMetric
	24, // 16: selling_iface.v1.ShopMetric.shop_return_cancelled_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopReturnCancelledMetric
	25, // 17: selling_iface.v1.ShopMetric.shop_product_cost_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopProductCostMetric
	26, // 18: selling_iface.v1.ShopMetric.shop_ads_expense_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopAdsExpenseMetric
	27, // 19: selling_iface.v1.ShopMetric.shop_hold_amount_metric:type_name -> selling_iface.v1.shop_metric.v1.ShopHoldAmountMetric
	28, // 20: selling_iface.v1.ShopStatMetricFilter.page:type_name -> common.v1.PageFilter
	7,  // 21: selling_iface.v1.ShopStatMetricFilter.range:type_name -> selling_iface.v1.ShopStatTimeRange
	29, // 22: selling_iface.v1.ShopStatTimeRange.start:type_name -> google.protobuf.Timestamp
	29, // 23: selling_iface.v1.ShopStatTimeRange.end:type_name -> google.protobuf.Timestamp
	6,  // 24: selling_iface.v1.ShopStatMetricRequest.filter:type_name -> selling_iface.v1.ShopStatMetricFilter
	3,  // 25: selling_iface.v1.ShopStatMetricRequest.sort:type_name -> selling_iface.v1.ShopMetricSort
	5,  // 26: selling_iface.v1.ShopStatMetricRequest.metric_extras:type_name -> selling_iface.v1.ShopMetricExtra
	0,  // 27: selling_iface.v1.ShopStatMetricRequest.metric_types:type_name -> selling_iface.v1.ShopMetricType
	4,  // 28: selling_iface.v1.ShopStatMetricResponse.metrics:type_name -> selling_iface.v1.ShopMetric
	29, // [29:29] is the sub-list for method output_type
	29, // [29:29] is the sub-list for method input_type
	29, // [29:29] is the sub-list for extension type_name
	29, // [29:29] is the sub-list for extension extendee
	0,  // [0:29] is the sub-list for field type_name
}

func init() { file_selling_iface_v1_shop_stat_metric_proto_init() }
func file_selling_iface_v1_shop_stat_metric_proto_init() {
	if File_selling_iface_v1_shop_stat_metric_proto != nil {
		return
	}
	file_selling_iface_v1_shop_stat_metric_proto_msgTypes[0].OneofWrappers = []any{
		(*ShopMetricSort_CommonSort)(nil),
		(*ShopMetricSort_ShopOrderMetricSort)(nil),
		(*ShopMetricSort_ShopOrderCompletedMetricSort)(nil),
		(*ShopMetricSort_ShopOrderCancelledMetricSort)(nil),
		(*ShopMetricSort_ShopReturnMetricSort)(nil),
		(*ShopMetricSort_ShopReturnArrivedMetricSort)(nil),
		(*ShopMetricSort_ShopReturnCancelledMetricSort)(nil),
		(*ShopMetricSort_ShopProductCostMetricSort)(nil),
		(*ShopMetricSort_ShopAdsExpenseMetricSort)(nil),
		(*ShopMetricSort_ShopHoldAmountMetricSort)(nil),
	}
	file_selling_iface_v1_shop_stat_metric_proto_msgTypes[1].OneofWrappers = []any{
		(*ShopMetric_ShopOrderMetric)(nil),
		(*ShopMetric_ShopOrderCompletedMetric)(nil),
		(*ShopMetric_ShopOrderCancelledMetric)(nil),
		(*ShopMetric_ShopReturnMetric)(nil),
		(*ShopMetric_ShopReturnArrivedMetric)(nil),
		(*ShopMetric_ShopReturnCancelledMetric)(nil),
		(*ShopMetric_ShopProductCostMetric)(nil),
		(*ShopMetric_ShopAdsExpenseMetric)(nil),
		(*ShopMetric_ShopHoldAmountMetric)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_selling_iface_v1_shop_stat_metric_proto_rawDesc), len(file_selling_iface_v1_shop_stat_metric_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_selling_iface_v1_shop_stat_metric_proto_goTypes,
		DependencyIndexes: file_selling_iface_v1_shop_stat_metric_proto_depIdxs,
		EnumInfos:         file_selling_iface_v1_shop_stat_metric_proto_enumTypes,
		MessageInfos:      file_selling_iface_v1_shop_stat_metric_proto_msgTypes,
	}.Build()
	File_selling_iface_v1_shop_stat_metric_proto = out.File
	file_selling_iface_v1_shop_stat_metric_proto_goTypes = nil
	file_selling_iface_v1_shop_stat_metric_proto_depIdxs = nil
}
