// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: revenue_iface/v1/revenue.proto

package revenue_iface

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderEvent int32

const (
	OrderEvent_ORDER_EVENT_UNSPECIFIED OrderEvent = 0
	OrderEvent_ORDER_EVENT_CREATED     OrderEvent = 1
	OrderEvent_ORDER_EVENT_RETURN      OrderEvent = 3
)

// Enum value maps for OrderEvent.
var (
	OrderEvent_name = map[int32]string{
		0: "ORDER_EVENT_UNSPECIFIED",
		1: "ORDER_EVENT_CREATED",
		3: "ORDER_EVENT_RETURN",
	}
	OrderEvent_value = map[string]int32{
		"ORDER_EVENT_UNSPECIFIED": 0,
		"ORDER_EVENT_CREATED":     1,
		"ORDER_EVENT_RETURN":      3,
	}
)

func (x OrderEvent) Enum() *OrderEvent {
	p := new(OrderEvent)
	*p = x
	return p
}

func (x OrderEvent) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OrderEvent) Descriptor() protoreflect.EnumDescriptor {
	return file_revenue_iface_v1_revenue_proto_enumTypes[0].Descriptor()
}

func (OrderEvent) Type() protoreflect.EnumType {
	return &file_revenue_iface_v1_revenue_proto_enumTypes[0]
}

func (x OrderEvent) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OrderEvent.Descriptor instead.
func (OrderEvent) EnumDescriptor() ([]byte, []int) {
	return file_revenue_iface_v1_revenue_proto_rawDescGZIP(), []int{0}
}

type WithdrawalRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	TeamId uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"` // must be > 0
	ShopId uint64                 `protobuf:"varint,2,opt,name=shop_id,json=shopId,proto3" json:"shop_id,omitempty"` // must be > 0
	// uint64 order_id = 3 [(buf.validate.field).uint64.gt = 0]; // must be > 0
	At            int64   `protobuf:"varint,4,opt,name=at,proto3" json:"at,omitempty"` // timestamp must be > 0
	Amount        float64 `protobuf:"fixed64,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawalRequest) Reset() {
	*x = WithdrawalRequest{}
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalRequest) ProtoMessage() {}

func (x *WithdrawalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalRequest.ProtoReflect.Descriptor instead.
func (*WithdrawalRequest) Descriptor() ([]byte, []int) {
	return file_revenue_iface_v1_revenue_proto_rawDescGZIP(), []int{0}
}

func (x *WithdrawalRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *WithdrawalRequest) GetShopId() uint64 {
	if x != nil {
		return x.ShopId
	}
	return 0
}

func (x *WithdrawalRequest) GetAt() int64 {
	if x != nil {
		return x.At
	}
	return 0
}

func (x *WithdrawalRequest) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type WithdrawalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WithdrawalResponse) Reset() {
	*x = WithdrawalResponse{}
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WithdrawalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WithdrawalResponse) ProtoMessage() {}

func (x *WithdrawalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WithdrawalResponse.ProtoReflect.Descriptor instead.
func (*WithdrawalResponse) Descriptor() ([]byte, []int) {
	return file_revenue_iface_v1_revenue_proto_rawDescGZIP(), []int{1}
}

type OrderCancelRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RefId         string                 `protobuf:"bytes,1,opt,name=ref_id,json=refId,proto3" json:"ref_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelRequest) Reset() {
	*x = OrderCancelRequest{}
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelRequest) ProtoMessage() {}

func (x *OrderCancelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelRequest.ProtoReflect.Descriptor instead.
func (*OrderCancelRequest) Descriptor() ([]byte, []int) {
	return file_revenue_iface_v1_revenue_proto_rawDescGZIP(), []int{2}
}

func (x *OrderCancelRequest) GetRefId() string {
	if x != nil {
		return x.RefId
	}
	return ""
}

type OrderCancelResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderCancelResponse) Reset() {
	*x = OrderCancelResponse{}
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderCancelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderCancelResponse) ProtoMessage() {}

func (x *OrderCancelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderCancelResponse.ProtoReflect.Descriptor instead.
func (*OrderCancelResponse) Descriptor() ([]byte, []int) {
	return file_revenue_iface_v1_revenue_proto_rawDescGZIP(), []int{3}
}

type BorrowStock struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TeamId        uint64                 `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	Amount        float64                `protobuf:"fixed64,2,opt,name=amount,proto3" json:"amount,omitempty"`
	SellAmount    float64                `protobuf:"fixed64,3,opt,name=sell_amount,json=sellAmount,proto3" json:"sell_amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BorrowStock) Reset() {
	*x = BorrowStock{}
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BorrowStock) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BorrowStock) ProtoMessage() {}

func (x *BorrowStock) ProtoReflect() protoreflect.Message {
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BorrowStock.ProtoReflect.Descriptor instead.
func (*BorrowStock) Descriptor() ([]byte, []int) {
	return file_revenue_iface_v1_revenue_proto_rawDescGZIP(), []int{4}
}

func (x *BorrowStock) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *BorrowStock) GetAmount() float64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *BorrowStock) GetSellAmount() float64 {
	if x != nil {
		return x.SellAmount
	}
	return 0
}

type OnOrderRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Token          string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	TeamId         uint64                 `protobuf:"varint,2,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	WarehouseId    uint64                 `protobuf:"varint,3,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	OrderId        uint64                 `protobuf:"varint,4,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	Event          OrderEvent             `protobuf:"varint,5,opt,name=event,proto3,enum=revenue_iface.v1.OrderEvent" json:"event,omitempty"`
	OrderAmount    float64                `protobuf:"fixed64,6,opt,name=order_amount,json=orderAmount,proto3" json:"order_amount,omitempty"`
	WarehouseFee   float64                `protobuf:"fixed64,7,opt,name=warehouse_fee,json=warehouseFee,proto3" json:"warehouse_fee,omitempty"`
	Description    string                 `protobuf:"bytes,8,opt,name=description,proto3" json:"description,omitempty"`
	BorrowStock    []*BorrowStock         `protobuf:"bytes,9,rep,name=borrow_stock,json=borrowStock,proto3" json:"borrow_stock,omitempty"`
	OwnStockAmount float64                `protobuf:"fixed64,10,opt,name=own_stock_amount,json=ownStockAmount,proto3" json:"own_stock_amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OnOrderRequest) Reset() {
	*x = OnOrderRequest{}
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOrderRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOrderRequest) ProtoMessage() {}

func (x *OnOrderRequest) ProtoReflect() protoreflect.Message {
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOrderRequest.ProtoReflect.Descriptor instead.
func (*OnOrderRequest) Descriptor() ([]byte, []int) {
	return file_revenue_iface_v1_revenue_proto_rawDescGZIP(), []int{5}
}

func (x *OnOrderRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *OnOrderRequest) GetTeamId() uint64 {
	if x != nil {
		return x.TeamId
	}
	return 0
}

func (x *OnOrderRequest) GetWarehouseId() uint64 {
	if x != nil {
		return x.WarehouseId
	}
	return 0
}

func (x *OnOrderRequest) GetOrderId() uint64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *OnOrderRequest) GetEvent() OrderEvent {
	if x != nil {
		return x.Event
	}
	return OrderEvent_ORDER_EVENT_UNSPECIFIED
}

func (x *OnOrderRequest) GetOrderAmount() float64 {
	if x != nil {
		return x.OrderAmount
	}
	return 0
}

func (x *OnOrderRequest) GetWarehouseFee() float64 {
	if x != nil {
		return x.WarehouseFee
	}
	return 0
}

func (x *OnOrderRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *OnOrderRequest) GetBorrowStock() []*BorrowStock {
	if x != nil {
		return x.BorrowStock
	}
	return nil
}

func (x *OnOrderRequest) GetOwnStockAmount() float64 {
	if x != nil {
		return x.OwnStockAmount
	}
	return 0
}

type OnOrderResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OnOrderResponse) Reset() {
	*x = OnOrderResponse{}
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OnOrderResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OnOrderResponse) ProtoMessage() {}

func (x *OnOrderResponse) ProtoReflect() protoreflect.Message {
	mi := &file_revenue_iface_v1_revenue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OnOrderResponse.ProtoReflect.Descriptor instead.
func (*OnOrderResponse) Descriptor() ([]byte, []int) {
	return file_revenue_iface_v1_revenue_proto_rawDescGZIP(), []int{6}
}

var File_revenue_iface_v1_revenue_proto protoreflect.FileDescriptor

const file_revenue_iface_v1_revenue_proto_rawDesc = "" +
	"\n" +
	"\x1erevenue_iface/v1/revenue.proto\x12\x10revenue_iface.v1\x1a\x1bbuf/validate/validate.proto\"\xa1\x01\n" +
	"\x11WithdrawalRequest\x12 \n" +
	"\ateam_id\x18\x01 \x01(\x04B\a\xbaH\x042\x02 \x00R\x06teamId\x12 \n" +
	"\ashop_id\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x06shopId\x12\x17\n" +
	"\x02at\x18\x04 \x01(\x03B\a\xbaH\x04\"\x02 \x00R\x02at\x12/\n" +
	"\x06amount\x18\x05 \x01(\x01B\x17\xbaH\x14\x12\x12\x19\x00\x00\x00\xa2\x94\x1amB!\x00\x00\x00\x00\x00\x00\x00\x00R\x06amount\"\x14\n" +
	"\x12WithdrawalResponse\"+\n" +
	"\x12OrderCancelRequest\x12\x15\n" +
	"\x06ref_id\x18\x01 \x01(\tR\x05refId\"\x15\n" +
	"\x13OrderCancelResponse\"_\n" +
	"\vBorrowStock\x12\x17\n" +
	"\ateam_id\x18\x01 \x01(\x04R\x06teamId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x01R\x06amount\x12\x1f\n" +
	"\vsell_amount\x18\x03 \x01(\x01R\n" +
	"sellAmount\"\xf7\x03\n" +
	"\x0eOnOrderRequest\x12\x1c\n" +
	"\x05token\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05token\x12 \n" +
	"\ateam_id\x18\x02 \x01(\x04B\a\xbaH\x042\x02 \x00R\x06teamId\x12*\n" +
	"\fwarehouse_id\x18\x03 \x01(\x04B\a\xbaH\x042\x02 \x00R\vwarehouseId\x12!\n" +
	"\border_id\x18\x04 \x01(\x04B\x06\xbaH\x03\xc8\x01\x01R\aorderId\x12<\n" +
	"\x05event\x18\x05 \x01(\x0e2\x1c.revenue_iface.v1.OrderEventB\b\xbaH\x05\x82\x01\x02\x10\x01R\x05event\x121\n" +
	"\forder_amount\x18\x06 \x01(\x01B\x0e\xbaH\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\vorderAmount\x123\n" +
	"\rwarehouse_fee\x18\a \x01(\x01B\x0e\xbaH\v\x12\t)\x00\x00\x00\x00\x00\x00\x00\x00R\fwarehouseFee\x12*\n" +
	"\vdescription\x18\b \x01(\tB\b\xbaH\x05r\x03\x18\x80\bR\vdescription\x12J\n" +
	"\fborrow_stock\x18\t \x03(\v2\x1d.revenue_iface.v1.BorrowStockB\b\xbaH\x05\x92\x01\x02\b\x00R\vborrowStock\x128\n" +
	"\x10own_stock_amount\x18\n" +
	" \x01(\x01B\x0e\xbaH\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x0eownStockAmount\"\x11\n" +
	"\x0fOnOrderResponse*Z\n" +
	"\n" +
	"OrderEvent\x12\x1b\n" +
	"\x17ORDER_EVENT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13ORDER_EVENT_CREATED\x10\x01\x12\x16\n" +
	"\x12ORDER_EVENT_RETURN\x10\x032\x97\x02\n" +
	"\x0eRevenueService\x12P\n" +
	"\aOnOrder\x12 .revenue_iface.v1.OnOrderRequest\x1a!.revenue_iface.v1.OnOrderResponse(\x01\x12Z\n" +
	"\vOrderCancel\x12$.revenue_iface.v1.OrderCancelRequest\x1a%.revenue_iface.v1.OrderCancelResponse\x12W\n" +
	"\n" +
	"Withdrawal\x12#.revenue_iface.v1.WithdrawalRequest\x1a$.revenue_iface.v1.WithdrawalResponseB\xc2\x01\n" +
	"\x14com.revenue_iface.v1B\fRevenueProtoP\x01Z?github.com/pdcgo/schema/services/revenue_iface/v1;revenue_iface\xa2\x02\x03RXX\xaa\x02\x0fRevenueIface.V1\xca\x02\x0fRevenueIface\\V1\xe2\x02\x1bRevenueIface\\V1\\GPBMetadata\xea\x02\x10RevenueIface::V1b\x06proto3"

var (
	file_revenue_iface_v1_revenue_proto_rawDescOnce sync.Once
	file_revenue_iface_v1_revenue_proto_rawDescData []byte
)

func file_revenue_iface_v1_revenue_proto_rawDescGZIP() []byte {
	file_revenue_iface_v1_revenue_proto_rawDescOnce.Do(func() {
		file_revenue_iface_v1_revenue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_revenue_iface_v1_revenue_proto_rawDesc), len(file_revenue_iface_v1_revenue_proto_rawDesc)))
	})
	return file_revenue_iface_v1_revenue_proto_rawDescData
}

var file_revenue_iface_v1_revenue_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_revenue_iface_v1_revenue_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_revenue_iface_v1_revenue_proto_goTypes = []any{
	(OrderEvent)(0),             // 0: revenue_iface.v1.OrderEvent
	(*WithdrawalRequest)(nil),   // 1: revenue_iface.v1.WithdrawalRequest
	(*WithdrawalResponse)(nil),  // 2: revenue_iface.v1.WithdrawalResponse
	(*OrderCancelRequest)(nil),  // 3: revenue_iface.v1.OrderCancelRequest
	(*OrderCancelResponse)(nil), // 4: revenue_iface.v1.OrderCancelResponse
	(*BorrowStock)(nil),         // 5: revenue_iface.v1.BorrowStock
	(*OnOrderRequest)(nil),      // 6: revenue_iface.v1.OnOrderRequest
	(*OnOrderResponse)(nil),     // 7: revenue_iface.v1.OnOrderResponse
}
var file_revenue_iface_v1_revenue_proto_depIdxs = []int32{
	0, // 0: revenue_iface.v1.OnOrderRequest.event:type_name -> revenue_iface.v1.OrderEvent
	5, // 1: revenue_iface.v1.OnOrderRequest.borrow_stock:type_name -> revenue_iface.v1.BorrowStock
	6, // 2: revenue_iface.v1.RevenueService.OnOrder:input_type -> revenue_iface.v1.OnOrderRequest
	3, // 3: revenue_iface.v1.RevenueService.OrderCancel:input_type -> revenue_iface.v1.OrderCancelRequest
	1, // 4: revenue_iface.v1.RevenueService.Withdrawal:input_type -> revenue_iface.v1.WithdrawalRequest
	7, // 5: revenue_iface.v1.RevenueService.OnOrder:output_type -> revenue_iface.v1.OnOrderResponse
	4, // 6: revenue_iface.v1.RevenueService.OrderCancel:output_type -> revenue_iface.v1.OrderCancelResponse
	2, // 7: revenue_iface.v1.RevenueService.Withdrawal:output_type -> revenue_iface.v1.WithdrawalResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_revenue_iface_v1_revenue_proto_init() }
func file_revenue_iface_v1_revenue_proto_init() {
	if File_revenue_iface_v1_revenue_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_revenue_iface_v1_revenue_proto_rawDesc), len(file_revenue_iface_v1_revenue_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_revenue_iface_v1_revenue_proto_goTypes,
		DependencyIndexes: file_revenue_iface_v1_revenue_proto_depIdxs,
		EnumInfos:         file_revenue_iface_v1_revenue_proto_enumTypes,
		MessageInfos:      file_revenue_iface_v1_revenue_proto_msgTypes,
	}.Build()
	File_revenue_iface_v1_revenue_proto = out.File
	file_revenue_iface_v1_revenue_proto_goTypes = nil
	file_revenue_iface_v1_revenue_proto_depIdxs = nil
}
